const test=require('node:test')
const assert=require('node:assert/strict')
const {DatabaseSync}=require('node:sqlite')
const {_testing:{buildPayload,applyPayload,reconcileOrderTotals}}=require('../electron/cloud-sync.cjs')

test('standalone vehicle keeps a null customer through cloud synchronization',()=>{
 const db=new DatabaseSync(':memory:')
 db.exec(`CREATE TABLE customers(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE vehicles(id INTEGER PRIMARY KEY,customer_id INTEGER,plate TEXT,make TEXT,cloud_id TEXT,updated_at TEXT);`)
 applyPayload(db,'vehicles','vehicle-solo',{customer_cloud_id:null,plate:'PO SOLO1',make:'Toyota'},'2026-09-10T12:00:00.000Z')
 const row=db.prepare("SELECT * FROM vehicles WHERE cloud_id='vehicle-solo'").get()
 assert.equal(row.customer_id,null)
 assert.equal(buildPayload(db,'vehicles',row).customer_cloud_id,null)
})

test('inventory part preserves barcode and supplier through cloud synchronization',()=>{
 const db=new DatabaseSync(':memory:')
 db.exec(`CREATE TABLE suppliers(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE inventory_parts(id INTEGER PRIMARY KEY,barcode TEXT,name TEXT,vehicle_fitment TEXT,cross_numbers TEXT,supplier_id INTEGER,cloud_id TEXT,updated_at TEXT); INSERT INTO suppliers VALUES(1,'supplier-cloud'); INSERT INTO inventory_parts VALUES(1,'4006381333931','Filtr oleju','BMW Seria 3 E90','11427508969',1,'part-cloud','2026-09-10T12:00:00.000Z');`)
 const payload=buildPayload(db,'inventory_parts',db.prepare('SELECT * FROM inventory_parts WHERE id=1').get())
 assert.equal(payload.barcode,'4006381333931')
 assert.equal(payload.vehicle_fitment,'BMW Seria 3 E90')
 assert.equal(payload.cross_numbers,'11427508969')
 assert.equal(payload.supplier_cloud_id,'supplier-cloud')
 applyPayload(db,'inventory_parts','remote-part',{barcode:'0049000006346',name:'Filtr kabinowy',vehicle_fitment:'Audi A4 B8',cross_numbers:'8K0819439',supplier_cloud_id:'supplier-cloud'},'2026-09-10T13:00:00.000Z')
 const remote=db.prepare("SELECT * FROM inventory_parts WHERE cloud_id='remote-part'").get()
 assert.equal(remote.barcode,'0049000006346')
 assert.equal(remote.vehicle_fitment,'Audi A4 B8')
 assert.equal(remote.cross_numbers,'8K0819439')
 assert.equal(remote.supplier_id,1)
})

test('order item preserves its inventory source through cloud synchronization',()=>{
 const db=new DatabaseSync(':memory:')
 db.exec(`CREATE TABLE inventory_parts(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE orders(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE order_items(id INTEGER PRIMARY KEY,order_id INTEGER,inventory_part_id INTEGER,name TEXT,cloud_id TEXT,updated_at TEXT); INSERT INTO inventory_parts VALUES(7,'inventory-cloud'); INSERT INTO orders VALUES(3,'order-cloud'); INSERT INTO order_items VALUES(11,3,7,'Filtr oleju','item-cloud','2026-09-11T10:00:00.000Z');`)
 const payload=buildPayload(db,'order_items',db.prepare('SELECT * FROM order_items WHERE id=11').get())
 assert.equal(payload.order_cloud_id,'order-cloud')
 assert.equal(payload.inventory_part_cloud_id,'inventory-cloud')
 assert.equal(payload.inventory_part_id,undefined)
 applyPayload(db,'order_items','remote-item',{order_cloud_id:'order-cloud',inventory_part_cloud_id:'inventory-cloud',name:'Filtr kabinowy'},'2026-09-11T11:00:00.000Z')
 const remote=db.prepare("SELECT * FROM order_items WHERE cloud_id='remote-item'").get()
 assert.equal(remote.order_id,3)
 assert.equal(remote.inventory_part_id,7)
})

test('ordered part maps its inventory source and OE data between devices',()=>{
 const db=new DatabaseSync(':memory:')
 db.exec(`CREATE TABLE suppliers(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE inventory_parts(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE orders(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE job_part_orders(id INTEGER PRIMARY KEY,order_id INTEGER,supplier_id INTEGER,inventory_part_id INTEGER,name TEXT,oe_number TEXT,vehicle_snapshot TEXT,cloud_id TEXT,updated_at TEXT); INSERT INTO suppliers VALUES(2,'supplier-cloud'); INSERT INTO inventory_parts VALUES(7,'inventory-cloud'); INSERT INTO orders VALUES(3,'order-cloud'); INSERT INTO job_part_orders VALUES(12,3,2,7,'Filtr oleju','11428507683','{"make":"BMW"}','job-part-cloud','2026-09-12T10:00:00.000Z');`)
 const payload=buildPayload(db,'job_part_orders',db.prepare('SELECT * FROM job_part_orders WHERE id=12').get())
 assert.equal(payload.order_cloud_id,'order-cloud')
 assert.equal(payload.supplier_cloud_id,'supplier-cloud')
 assert.equal(payload.inventory_part_cloud_id,'inventory-cloud')
 assert.equal(payload.inventory_part_id,undefined)
 assert.equal(payload.oe_number,'11428507683')
 applyPayload(db,'job_part_orders','remote-job-part',{order_cloud_id:'order-cloud',supplier_cloud_id:'supplier-cloud',inventory_part_cloud_id:'inventory-cloud',name:'Filtr kabinowy',oe_number:'64319313519',vehicle_snapshot:'{"make":"BMW"}'},'2026-09-12T11:00:00.000Z')
 const remote=db.prepare("SELECT * FROM job_part_orders WHERE cloud_id='remote-job-part'").get()
 assert.equal(remote.order_id,3)
 assert.equal(remote.supplier_id,2)
 assert.equal(remote.inventory_part_id,7)
 assert.equal(remote.oe_number,'64319313519')
})

test('recalculates order profitability after remote item changes',()=>{
 const db=new DatabaseSync(':memory:')
 db.exec(`CREATE TABLE orders(id INTEGER PRIMARY KEY,parts_cost REAL,parts_sale REAL,other_cost REAL,other_sale REAL); CREATE TABLE order_items(id INTEGER PRIMARY KEY,order_id INTEGER,kind TEXT,qty REAL,unit_cost REAL,unit_price REAL); INSERT INTO orders VALUES(3,999,999,999,999); INSERT INTO order_items VALUES(1,3,'CZESC',2,40,85); INSERT INTO order_items VALUES(2,3,'USLUGA_ZEW',1,60,100);`)
 reconcileOrderTotals(db)
 assert.deepEqual({...db.prepare('SELECT parts_cost,parts_sale,other_cost,other_sale FROM orders WHERE id=3').get()},{parts_cost:80,parts_sale:170,other_cost:60,other_sale:100})
})
