const test=require('node:test')
const assert=require('node:assert/strict')
const {DatabaseSync}=require('node:sqlite')
const {_testing:{buildPayload,applyPayload}}=require('../electron/cloud-sync.cjs')

test('standalone vehicle keeps a null customer through cloud synchronization',()=>{
 const db=new DatabaseSync(':memory:')
 db.exec(`CREATE TABLE customers(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE vehicles(id INTEGER PRIMARY KEY,customer_id INTEGER,plate TEXT,make TEXT,cloud_id TEXT,updated_at TEXT);`)
 applyPayload(db,'vehicles','vehicle-solo',{customer_cloud_id:null,plate:'PO SOLO1',make:'Toyota'},'2026-09-10T12:00:00.000Z')
 const row=db.prepare("SELECT * FROM vehicles WHERE cloud_id='vehicle-solo'").get()
 assert.equal(row.customer_id,null)
 assert.equal(buildPayload(db,'vehicles',row).customer_cloud_id,null)
})

test('inventory part preserves barcode and supplier through cloud synchronization',()=>{
 const db=new DatabaseSync(':memory:')
 db.exec(`CREATE TABLE suppliers(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE inventory_parts(id INTEGER PRIMARY KEY,barcode TEXT,name TEXT,supplier_id INTEGER,cloud_id TEXT,updated_at TEXT); INSERT INTO suppliers VALUES(1,'supplier-cloud'); INSERT INTO inventory_parts VALUES(1,'4006381333931','Filtr oleju',1,'part-cloud','2026-09-10T12:00:00.000Z');`)
 const payload=buildPayload(db,'inventory_parts',db.prepare('SELECT * FROM inventory_parts WHERE id=1').get())
 assert.equal(payload.barcode,'4006381333931')
 assert.equal(payload.supplier_cloud_id,'supplier-cloud')
 applyPayload(db,'inventory_parts','remote-part',{barcode:'0049000006346',name:'Filtr kabinowy',supplier_cloud_id:'supplier-cloud'},'2026-09-10T13:00:00.000Z')
 const remote=db.prepare("SELECT * FROM inventory_parts WHERE cloud_id='remote-part'").get()
 assert.equal(remote.barcode,'0049000006346')
 assert.equal(remote.supplier_id,1)
})

test('order item preserves its inventory source through cloud synchronization',()=>{
 const db=new DatabaseSync(':memory:')
 db.exec(`CREATE TABLE inventory_parts(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE orders(id INTEGER PRIMARY KEY,cloud_id TEXT); CREATE TABLE order_items(id INTEGER PRIMARY KEY,order_id INTEGER,inventory_part_id INTEGER,name TEXT,cloud_id TEXT,updated_at TEXT); INSERT INTO inventory_parts VALUES(7,'inventory-cloud'); INSERT INTO orders VALUES(3,'order-cloud'); INSERT INTO order_items VALUES(11,3,7,'Filtr oleju','item-cloud','2026-09-11T10:00:00.000Z');`)
 const payload=buildPayload(db,'order_items',db.prepare('SELECT * FROM order_items WHERE id=11').get())
 assert.equal(payload.order_cloud_id,'order-cloud')
 assert.equal(payload.inventory_part_cloud_id,'inventory-cloud')
 assert.equal(payload.inventory_part_id,undefined)
 applyPayload(db,'order_items','remote-item',{order_cloud_id:'order-cloud',inventory_part_cloud_id:'inventory-cloud',name:'Filtr kabinowy'},'2026-09-11T11:00:00.000Z')
 const remote=db.prepare("SELECT * FROM order_items WHERE cloud_id='remote-item'").get()
 assert.equal(remote.order_id,3)
 assert.equal(remote.inventory_part_id,7)
})
