import test from 'node:test'
import assert from 'node:assert/strict'
import {approvalRecordState,canonicalJson,sha256Hex,snapshotHashMatches,validApprovalToken,validateDecision,publicApproval} from '../supabase/functions/approval/model.mjs'

const png='data:image/png;base64,'+Buffer.from([137,80,78,71,...new Array(120).fill(1)]).toString('base64')
test('Edge canonical hash matches independent document ordering',async()=>{assert.equal(await sha256Hex(canonicalJson({b:2,a:{d:4,c:3}})),await sha256Hex(canonicalJson({a:{c:3,d:4},b:2})))})
test('approval requires checkbox and a non-empty PNG signature',()=>{assert.throws(()=>validateDecision({decision:'APPROVED',termsAccepted:false,signature:png,signaturePoints:10}),/TERMS_REQUIRED/);assert.throws(()=>validateDecision({decision:'APPROVED',termsAccepted:true,signature:'',signaturePoints:0}),/SIGNATURE_EMPTY/);assert.equal(validateDecision({decision:'APPROVED',termsAccepted:true,signature:png,signaturePoints:5}),true)})
test('decline needs no signature and exposes only approval snapshot fields',()=>{assert.equal(validateDecision({decision:'DECLINED',note:'Za drogo'}),true);const view=publicApproval({orderId:1,secret:'hide',vehicle:{plate:'ZPL'},items:[],totals:{gross:10}});assert.equal(view.secret,undefined);assert.equal(view.vehicle.plate,'ZPL')})
test('token validation rejects malformed links and expired or used records stay closed',()=>{assert.equal(validApprovalToken('a'.repeat(64)),true);assert.equal(validApprovalToken('../approval'),false);assert.equal(approvalRecordState(null),'INVALID');assert.equal(approvalRecordState({status:'PENDING',expires_at:'2026-01-01T00:00:00Z'},Date.parse('2026-01-02T00:00:00Z')),'EXPIRED');assert.equal(approvalRecordState({status:'APPROVED',expires_at:'2099-01-01T00:00:00Z'}),'USED')})
test('modified snapshot and incorrect hash fail integrity verification',async()=>{const snapshot={orderId:4,items:[{name:'Diagnostyka',value:200}]},hash=await sha256Hex(canonicalJson(snapshot));assert.equal(await snapshotHashMatches(snapshot,hash),true);assert.equal(await snapshotHashMatches({...snapshot,items:[{name:'Diagnostyka',value:201}]},hash),false);assert.equal(await snapshotHashMatches(snapshot,'0'.repeat(64)),false)})
