export const TERMS_VERSION='repair-approval-pl-v1'
export const TERMS_TEXT='Potwierdzam zapoznanie się z przedstawionym zakresem prac oraz kosztami i wyrażam zgodę na wykonanie wskazanych prac.'

export function stableValue(value){if(Array.isArray(value))return value.map(stableValue);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,stableValue(value[key])]));return value}
export function canonicalJson(value){return JSON.stringify(stableValue(value))}
export async function sha256Hex(value){const bytes=value instanceof Uint8Array?value:new TextEncoder().encode(String(value));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
export function validApprovalToken(value){return /^[a-f0-9]{48,128}$/i.test(String(value||''))}
export function approvalRecordState(record,now=Date.now()){if(!record)return 'INVALID';if(record.status!=='PENDING')return 'USED';return Date.parse(record.expires_at)<=Number(now)?'EXPIRED':'OPEN'}
export async function snapshotHashMatches(snapshot,expected){return (await sha256Hex(canonicalJson(snapshot)))===String(expected||'')}
export function parseSignatureDataUrl(value){const match=String(value||'').match(/^data:image\/png;base64,([A-Za-z0-9+/=]+)$/);if(!match)throw new Error('SIGNATURE_INVALID');const binary=atob(match[1]);if(binary.length<100||binary.length>750000)throw new Error('SIGNATURE_INVALID');const bytes=Uint8Array.from(binary,char=>char.charCodeAt(0));if(bytes[0]!==137||bytes[1]!==80||bytes[2]!==78||bytes[3]!==71)throw new Error('SIGNATURE_INVALID');return bytes}
export function validateDecision({decision,termsAccepted,signature,signaturePoints,note}){if(!['APPROVED','DECLINED'].includes(decision))throw new Error('DECISION_INVALID');if(String(note||'').length>1000)throw new Error('NOTE_TOO_LONG');if(decision==='APPROVED'){if(!termsAccepted)throw new Error('TERMS_REQUIRED');if(Number(signaturePoints||0)<3)throw new Error('SIGNATURE_EMPTY');parseSignatureDataUrl(signature)}return true}
export function publicApproval(snapshot){return {documentNo:snapshot.documentNo||'',approvalDocumentNo:snapshot.approvalDocumentNo||'',approvalSequence:Number(snapshot.approvalSequence||1),orderId:snapshot.orderId,vehicle:snapshot.vehicle||{},order:snapshot.order||{},items:Array.isArray(snapshot.items)?snapshot.items:[],totals:snapshot.totals||{},scope:snapshot.scope||'',additionalScope:!!snapshot.additionalScope,previouslyApprovedTotal:Number(snapshot.previouslyApprovedTotal||0),additionalTotal:Number(snapshot.additionalTotal||snapshot.totals?.gross||0),newCombinedTotal:Number(snapshot.newCombinedTotal||snapshot.totals?.gross||0),terms:snapshot.terms||{version:TERMS_VERSION,text:TERMS_TEXT}}}
