const {app}=require('electron')
const path=require('node:path')
const os=require('node:os')
const fs=require('node:fs')

app.whenReady().then(async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'autologika-migration-'))
 app.setPath('userData',dir)
 const Database=require('better-sqlite3')
 const legacy=new Database(path.join(dir,'autologika.db'))
 legacy.exec('CREATE TABLE legacy_marker(value TEXT); INSERT INTO legacy_marker(value) VALUES (\'DANE-ZACHOWANE\');')
 legacy.close()
 const {getDb,createVersionBackup,SCHEMA_VERSION}=require('../electron/db.cjs')
 const db=getDb()
 const columns=table=>new Set(db.prepare(`PRAGMA table_info(${table})`).all().map(row=>row.name))
 const required=['catalog_work_id','catalog_variant_id','work_name','variant_name','customer_description','hours_snapshot','price_snapshot']
 for(const table of ['order_items','quote_items'])for(const column of required)if(!columns(table).has(column))throw new Error(`${table}.${column} missing`)
 for(const table of ['work_procedure_runs','technical_data_entries','vehicle_findings','order_qc','work_templates','technical_manual_pages','technical_manual_hotspots','technical_manual_steps'])db.prepare(`SELECT 1 FROM ${table} LIMIT 1`).get()
 if(db.pragma('user_version',{simple:true})!==SCHEMA_VERSION)throw new Error('schema version not saved')
 if(db.prepare('SELECT value FROM legacy_marker').get().value!=='DANE-ZACHOWANE')throw new Error('legacy data lost')
 const migrationBackups=fs.readdirSync(path.join(dir,'backups')).filter(name=>name.includes('before-schema')&&name.endsWith('.db'))
 if(migrationBackups.length!==1)throw new Error(`expected one pre-migration backup, found ${migrationBackups.length}`)
 getDb()
 if(fs.readdirSync(path.join(dir,'backups')).filter(name=>name.includes('before-schema')&&name.endsWith('.db')).length!==1)throw new Error('migration repeated')
 const updateBackup=await createVersionBackup({currentVersion:'1.0.0',targetVersion:'1.0.1'})
 if(!fs.existsSync(updateBackup.file)||!fs.existsSync(updateBackup.manifestPath))throw new Error('update backup or manifest missing')
 console.log(JSON.stringify({ok:true,db:path.join(dir,'autologika.db'),schemaVersion:SCHEMA_VERSION,migrationBackup:migrationBackups[0],updateBackup:path.basename(updateBackup.file),snapshotColumns:required.length,extendedTables:8}))
 app.quit()
}).catch(error=>{console.error(error);app.exit(1)})
