// Isolated Electron smoke test: never opens the operator's database or cloud config.
const { app } = require('electron')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const assert = require('node:assert/strict')
app.setPath('userData', fs.mkdtempSync(path.join(os.tmpdir(), 'autologika-ui-')))
const output = path.join(__dirname, '..', 'artifacts', 'ui')
const registrationSample = fs.readFileSync(path.join(__dirname, '..', 'tests', 'fixtures', 'polish-registration-base64.txt'), 'utf8').trim()
fs.mkdirSync(output, { recursive: true })
const delay = ms => new Promise(resolve => setTimeout(resolve, ms))
const errors = []
setTimeout(() => { console.error('UI smoke test timed out'); app.exit(1) }, 55000).unref()
app.on('browser-window-created', (_, win) => {
  win.webContents.on('console-message', (_, level, message) => {
    if (level >= 3) errors.push(message)
  })
  win.webContents.once('did-finish-load', async () => {
    try {
      const capture = async name => fs.writeFileSync(path.join(output, `${name}.png`), (await win.webContents.capturePage()).toPNG())
      await delay(450)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.bootSplash') !== null`), true)
      await capture('boot-splash')
      await delay(750)
      const inspect = () => win.webContents.executeJavaScript(`({fatal:!!document.querySelector('.fatalScreen'),overflow:document.documentElement.scrollWidth>innerWidth,radar:document.querySelectorAll('.studioBlip').length,title:document.querySelector('header h1')?.textContent})`)
      const dashboard = await inspect()
      assert.equal(dashboard.fatal, false)
      assert.equal(dashboard.overflow, false)
      assert.equal(dashboard.radar, 6)
      console.log('DASHBOARD', JSON.stringify(dashboard))
      await capture('dashboard-1500')
      await win.webContents.executeJavaScript(`window.scrollTo(0,650)`)
      await delay(200)
      await capture('dashboard-details')
      await win.webContents.executeJavaScript(`window.scrollTo(0,0);document.querySelectorAll('.studioFilters button')[2].click()`)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.studioOrder').length`), 2)
      await win.webContents.executeJavaScript(`document.querySelector('.studioFilters button').click()`)
      win.setSize(1100, 800)
      await delay(400)
      const compact = await inspect()
      assert.equal(compact.overflow, false)
      assert.equal(compact.fatal, false)
      console.log('COMPACT', JSON.stringify(compact))
      await capture('dashboard-1100')
      win.setSize(1500, 940)
      await delay(300)
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Finanse / KPI"]').click()`)
      await delay(450)
      assert.equal((await inspect()).title,'Finanse i KPI')
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.financeKpi').length`),4)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.financeChartBar').length`),30)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.financeChartPlot').getBoundingClientRect().height>=260`),true)
      assert.equal((await inspect()).overflow,false)
      await capture('finance-kpi-1500')
      win.setSize(1100,800)
      await delay(350)
      assert.equal((await inspect()).overflow,false)
      await capture('finance-kpi-1100')
      win.setSize(1500,940)
      await delay(250)
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Ustawienia"]').click()`)
      await delay(250)
      await win.webContents.executeJavaScript(`{
        const target=document.querySelector('input');target.focus();
        for(const key of ${JSON.stringify(registrationSample)})target.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));
        target.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));
      }`)
      await delay(600)
      assert.equal((await inspect()).title,'Szybkie przyjęcie pojazdu')
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.formgrid label')].find(x=>x.textContent.startsWith('Marka')).querySelector('select').value`),'Toyota')
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.formgrid label')].find(x=>x.textContent.startsWith('Model')).querySelector('select').value`),'Corolla')
      console.log('GLOBAL_AZTEC_INTAKE','AZTEC captured over an active input and redirected from settings to populated quick intake')
      const inventoryDb=require('../electron/db.cjs').getDb()
      inventoryDb.prepare(`INSERT INTO inventory_parts(barcode,part_no,name,brand,stock,min_stock,unit_cost,sell_price,location) VALUES (?,?,?,?,?,?,?,?,?)`).run('4006381333931','W 712/95','Filtr oleju','MANN-FILTER',4,2,24.5,49,'A-03')
      await win.webContents.executeJavaScript(`{
        const target=document.querySelector('input');target.focus();
        for(const key of '4006381333931')target.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));
        target.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));
      }`)
      await delay(650)
      assert.equal((await inspect()).title,'Części i magazyn')
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.partsWorkspace .stockCard.selected')`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.stockLookupMessage')?.textContent.includes('Część jest już w Twoim magazynie')`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.stockCard.selected')?.textContent.includes('Filtr oleju')`),true)
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.stockCard.selected button')].some(button=>button.textContent.includes('Wydaj do zlecenia'))`),true)
      console.log('GLOBAL_PART_BARCODE','EAN captured globally and resolved directly from the local inventory')
      await capture('parts-inventory-scan')
      const temporaryOrder=inventoryDb.prepare(`INSERT INTO orders(vehicle_id,title,status,opened_at) VALUES (1,'Test wydania magazynowego','NAPRAWA',datetime('now','+1 day'))`).run().lastInsertRowid
      await win.webContents.executeJavaScript(`document.querySelector('.stockCard.selected .issueAction').click()`)
      await delay(300)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.issueModal')?.textContent.includes('Wydaj część do zlecenia')`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.issueModal select').value`),String(temporaryOrder))
      await capture('parts-issue-order')
      await win.webContents.executeJavaScript(`document.querySelector('.issueModal form').requestSubmit()`)
      await delay(450)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.stockLookupMessage')?.textContent.includes('Część wydana do zlecenia')`),true)
      const issuedItem=inventoryDb.prepare(`SELECT id,inventory_part_id FROM order_items WHERE inventory_part_id IS NOT NULL ORDER BY id DESC LIMIT 1`).get()
      assert.ok(issuedItem)
      assert.equal(inventoryDb.prepare('SELECT stock FROM inventory_parts WHERE id=?').get(issuedItem.inventory_part_id).stock,3)
      assert.equal(await win.webContents.executeJavaScript(`window.autologika.items.remove(${Number(issuedItem.id)})`),true)
      assert.equal(inventoryDb.prepare('SELECT stock FROM inventory_parts WHERE id=?').get(issuedItem.inventory_part_id).stock,4)
      inventoryDb.prepare('DELETE FROM orders WHERE id=?').run(temporaryOrder)
      console.log('INVENTORY_ISSUE','part issued to an active order and restored after removing the order item')
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Pulpit"]').click()`)
      await delay(350)
      // Test application-owned controls using their accessible labels.
      await win.webContents.executeJavaScript(`document.querySelector('.studioBlip').click()`)
      await delay(500)
      const destination = await inspect()
      assert.equal(destination.title, 'Centrum zlecenia')
      assert.equal(destination.fatal, false)
      console.log('RADAR_DESTINATION', JSON.stringify(destination))
      await capture('order-center')
      win.setSize(1100, 800)
      await delay(300)
      assert.equal((await inspect()).overflow, false)
      await capture('order-center-1100')
      win.setSize(1500, 940)
      const openOrderTab = async tab => {
        await win.webContents.executeJavaScript(`document.querySelector('[data-order-tab="${tab}"]').click()`)
        await delay(160)
        assert.equal((await inspect()).fatal, false, tab)
        assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.workspaceContent').textContent.trim().length > 0`), true, `${tab} must render content`)
      }
      for (const tab of ['diagnosis','quote','parts','time','docs','contact','settlement','reminders','timeline','release']) await openOrderTab(tab)
      await openOrderTab('diagnosis')
      await win.webContents.executeJavaScript(`{
        const field = [...document.querySelectorAll('.workspaceContent label')].find(x=>x.textContent==='Wniosek / przyczyna').querySelector('textarea');
        Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(field,'Wniosek testowy UI');
        field.dispatchEvent(new Event('input',{bubbles:true}));
      }`)
      await delay(100)
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.workspaceContent button')].find(x=>x.textContent==='Zapisz diagnostykę').click()`)
      await delay(450)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('[data-order-tab="diagnosis"]').getAttribute('aria-current')`), 'page')
      assert.equal(require('../electron/db.cjs').getDb().prepare('SELECT conclusion FROM diagnostics WHERE order_id=1').get().conclusion, 'Wniosek testowy UI')
      await openOrderTab('settlement')
      await capture('order-payment')
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.workspaceContent button')].find(x=>x.textContent.includes('Zapisz płatność')).click()`)
      await delay(450)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('[data-order-tab="settlement"]').getAttribute('aria-current')`), 'page')
      assert.equal(require('../electron/db.cjs').getDb().prepare('SELECT SUM(amount) n FROM payments WHERE order_id=1').get().n, 600)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.settlementSummary').dataset.paid`),'600.00')
      await openOrderTab('release')
      await capture('order-closeout')
      await win.webContents.executeJavaScript(`{
        const field=document.querySelector('select[aria-label="Wybierz zlecenie"]');
        Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(field,'2');
        field.dispatchEvent(new Event('change',{bubbles:true}));
      }`)
      await delay(350)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('select[aria-label="Wybierz zlecenie"]').value`), '2')
      await openOrderTab('settlement')
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.workspaceContent button')].find(x=>x.textContent.includes('Zapisz płatność')).click()`)
      await delay(400)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('select[aria-label="Wybierz zlecenie"]').value`), '2')
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('[data-order-tab="settlement"]').getAttribute('aria-current')`), 'page')
      assert.equal(require('../electron/db.cjs').getDb().prepare('SELECT SUM(amount) n FROM payments WHERE order_id=2').get().n, 2450)
      const centerDb=require('../electron/db.cjs').getDb()
      centerDb.prepare("INSERT INTO approvals(order_id,status,amount,scope,channel,decided_at) VALUES (2,'APPROVED',2450,'Pełny zakres','TEST',CURRENT_TIMESTAMP)").run()
      centerDb.prepare("INSERT INTO diagnostics(order_id,conclusion,recommendation) VALUES (2,'Naprawa wykonana','Wydanie pojazdu')").run()
      centerDb.prepare("INSERT INTO work_logs(order_id,worker,started_at,ended_at,duration_minutes) VALUES (2,'Test',datetime('now','-1 hour'),CURRENT_TIMESTAMP,60)").run()
      centerDb.prepare("INSERT INTO order_notes(order_id,release_notes) VALUES (2,'Zalecenia przekazane klientowi') ON CONFLICT(order_id) DO UPDATE SET release_notes=excluded.release_notes").run()
      centerDb.prepare("UPDATE job_part_orders SET status='ZAMONTOWANE' WHERE order_id=2").run()
      const qcInsert=centerDb.prepare("INSERT INTO order_qc(order_id,check_key,label,checked,checked_at) VALUES (2,?,?,1,CURRENT_TIMESTAMP) ON CONFLICT(order_id,check_key) DO UPDATE SET checked=1,checked_at=CURRENT_TIMESTAMP,deleted_at=NULL")
      for(const [key,label] of [['symptom','Objaw'],['dtc','DTC'],['leaks','Szczelność'],['torque','Momenty'],['road','Jazda'],['warning','Kontrolki'],['clean','Przygotowanie'],['recommend','Zalecenia']])qcInsert.run(key,label)
      await win.webContents.executeJavaScript(`{
        const field=document.querySelector('select[aria-label="Wybierz zlecenie"]');
        const set=value=>{Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(field,value);field.dispatchEvent(new Event('change',{bubbles:true}))};set('1')
      }`)
      await delay(350)
      await win.webContents.executeJavaScript(`{
        const field=document.querySelector('select[aria-label="Wybierz zlecenie"]');
        Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(field,'2');field.dispatchEvent(new Event('change',{bubbles:true}))
      }`)
      await delay(450)
      await openOrderTab('release')
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.closeoutChecks input')].every(x=>x.checked)`),true)
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.workspaceContent button')].find(x=>x.textContent.includes('ZAMKNIJ I OZNACZ')).disabled`),false)
      await win.webContents.executeJavaScript(`document.querySelector('.closeoutProgress').scrollIntoView({block:'center'})`)
      await delay(200)
      await capture('order-release-ready')
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.workspaceContent button')].find(x=>x.textContent.includes('ZAMKNIJ I OZNACZ')).click()`)
      await delay(600)
      assert.equal(centerDb.prepare('SELECT status FROM orders WHERE id=2').get().status,'WYDANE')
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('select[aria-label="Wybierz zlecenie"]').value`),'1')
      console.log('ORDER_TABS_AND_SAVES', 'connected stages rendered; payment updates settlement and completed checklist closes the order')
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Zlecenia"]').click()`)
      await delay(400)
      await win.webContents.executeJavaScript(`document.querySelector('.orderrow[data-order-id="1"]').click()`)
      await delay(450)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.repairCascade')`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.repairCascadeSteps select').length`),3)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.newRepairPosition')`),true)
      assert.equal((await inspect()).fatal,false)
      await capture('orders-repair-cascade')
      const laborBefore=require('../electron/db.cjs').getDb().prepare("SELECT COUNT(*) n FROM order_items WHERE order_id=1 AND kind='ROBOCIZNA'").get().n
      await win.webContents.executeJavaScript(`document.querySelector('.repairAddSelected').click()`)
      await delay(450)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.workCascade.bundleModal')`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.workCascade.bundleModal select').length >= 3`),true)
      await capture('orders-repair-package')
      await win.webContents.executeJavaScript(`document.querySelector('.workCascade.bundleModal .actionrow.right .primary').click()`)
      await delay(700)
      const laborAfter=require('../electron/db.cjs').getDb().prepare("SELECT COUNT(*) n FROM order_items WHERE order_id=1 AND kind='ROBOCIZNA'").get().n
      assert.equal(laborAfter,laborBefore+1)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.performedWork').length`),1)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.newRepairPosition')`),true)
      assert.equal((await inspect()).fatal,false)
      await win.webContents.executeJavaScript(`document.querySelector('.newRepairPosition').scrollIntoView({block:'center'})`)
      await delay(200)
      await capture('orders-repair-added')
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.orderRepairDetail .mini>div:nth-child(2) b').textContent===document.querySelector('.orderrow strong').textContent`),true)
      console.log('ORDER_REPAIR_CASCADE', 'repair selected from 3-level catalog and added as a procedure bundle')
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('button')].find(x=>x.textContent.includes('Nowe zlecenie')).click()`)
      await delay(350)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.vehicleChoiceList>button').length >= 6`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.newOrderMode>button').length`),2)
      assert.equal(await win.webContents.executeJavaScript(`getComputedStyle(document.querySelector('.modal')).backgroundColor!==getComputedStyle(document.querySelector('.newOrderStep')).backgroundColor`),true)
      await capture('new-order-existing-vehicle')
      const database=require('../electron/db.cjs').getDb()
      const countsBefore={customers:database.prepare('SELECT COUNT(*) n FROM customers').get().n,vehicles:database.prepare('SELECT COUNT(*) n FROM vehicles').get().n,orders:database.prepare('SELECT COUNT(*) n FROM orders').get().n}
      await win.webContents.executeJavaScript(`document.querySelector('[data-vehicle-mode="new"]').click()`)
      await delay(200)
      await win.webContents.executeJavaScript(`document.querySelector('.ownerMode button:last-child').click()`)
      await delay(100)
      await win.webContents.executeJavaScript(`{
        const setInput=(element,value)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(element,value);element.dispatchEvent(new Event('input',{bubbles:true}))};
        setInput(document.querySelector('input[aria-label="Nazwa nowego klienta"]'),'Klient z nowego zlecenia');
        const plate=[...document.querySelectorAll('.newOrderVehicleCatalog label')].find(x=>x.textContent.startsWith('Nr rej.')).querySelector('input');
        setInput(plate,'PO TEST1');
        const make=[...document.querySelectorAll('.newOrderVehicleCatalog label')].find(x=>x.textContent.startsWith('Marka')).querySelector('select');
        Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(make,'Audi');make.dispatchEvent(new Event('change',{bubbles:true}));
      }`)
      await delay(250)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.newOrderActions .primary').disabled`),false)
      await capture('new-order-new-vehicle')
      await win.webContents.executeJavaScript(`document.querySelector('.newOrderActions .primary').click()`)
      await delay(700)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM customers').get().n,countsBefore.customers+1)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM vehicles').get().n,countsBefore.vehicles+1)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM orders').get().n,countsBefore.orders+1)
      assert.equal(database.prepare("SELECT COUNT(*) n FROM vehicles WHERE plate='PO TEST1' AND make='Audi'").get().n,1)
      console.log('NEW_ORDER_VEHICLE', 'existing vehicle list and inline customer/vehicle creation verified')
      await delay(250)
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.orderrow')].find(x=>x.textContent.includes('PO TEST1')).click()`)
      await delay(250)
      await win.webContents.executeJavaScript(`window.confirm=()=>true;document.querySelector('.deleteOrderButton').click()`)
      await delay(450)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM orders').get().n,countsBefore.orders)
      assert.equal(database.prepare("SELECT COUNT(*) n FROM vehicles WHERE plate='PO TEST1'").get().n,1)
      const archiveBefore=database.prepare('SELECT COUNT(*) n FROM orders WHERE archived_at IS NOT NULL').get().n
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.orderrow')].find(x=>x.textContent.includes('Gotowe')).click()`)
      await delay(250)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.archiveOrderButton')`),true)
      await win.webContents.executeJavaScript(`document.querySelector('.archiveOrderButton').click()`)
      await delay(450)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM orders WHERE archived_at IS NOT NULL').get().n,archiveBefore+1)
      await win.webContents.executeJavaScript(`document.querySelector('[data-orders-view="archive"]').click()`)
      await delay(250)
      await win.webContents.executeJavaScript(`document.querySelector('.orderrow').click()`)
      await delay(250)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.archivedOrderDetail')`),true)
      await capture('orders-archive')
      await win.webContents.executeJavaScript(`document.querySelector('.archiveActions button').click()`)
      await delay(400)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM orders WHERE archived_at IS NOT NULL').get().n,archiveBefore)
      await win.webContents.executeJavaScript(`document.querySelector('[data-orders-view="active"]').click()`)
      await delay(200)
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.orderrow')].some(x=>x.textContent.includes('Gotowe'))`),true)
      console.log('ORDER_ARCHIVE_DELETE', 'archive, restore and permanent order deletion verified; vehicle retained')
      const vehicleOnlyCustomer=database.prepare("INSERT INTO customers(name) VALUES ('Klient Pojazdu UI')").run().lastInsertRowid
      const vehicleOnly=database.prepare("INSERT INTO vehicles(customer_id,plate,make,model) VALUES (?,'PO DELETE','Toyota','Yaris')").run(vehicleOnlyCustomer).lastInsertRowid
      const cascadeCustomer=database.prepare("INSERT INTO customers(name) VALUES ('Klient Kaskada UI')").run().lastInsertRowid
      const cascadeVehicle=database.prepare("INSERT INTO vehicles(customer_id,plate,make,model) VALUES (?,'PO CASCADE','Ford','Focus')").run(cascadeCustomer).lastInsertRowid
      const cascadeOrder=database.prepare("INSERT INTO orders(vehicle_id,title) VALUES (?,'Zlecenie do usunięcia')").run(cascadeVehicle).lastInsertRowid
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Klienci / auta"]').click()`)
      await delay(400)
      await win.webContents.executeJavaScript(`document.querySelector('[aria-label="Edytuj klienta Klient Pojazdu UI"]').click()`)
      await delay(200)
      await win.webContents.executeJavaScript(`{
        const field=[...document.querySelectorAll('.modal label')].find(x=>x.textContent.includes('Firma')).querySelector('input');
        Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(field,'Warsztat Testowy');
        field.dispatchEvent(new Event('input',{bubbles:true}));
        [...document.querySelectorAll('.modal button')].find(x=>x.textContent==='Zapisz').click();
      }`)
      await delay(300)
      assert.equal(database.prepare('SELECT company FROM customers WHERE id=?').get(vehicleOnlyCustomer).company,'Warsztat Testowy')
      await win.webContents.executeJavaScript(`document.querySelector('[aria-label="Edytuj pojazd PO DELETE"]').click()`)
      await delay(200)
      await win.webContents.executeJavaScript(`{
        const field=[...document.querySelectorAll('.modal label')].find(x=>x.textContent.includes('Przebieg')).querySelector('input');
        Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(field,'76543');
        field.dispatchEvent(new Event('input',{bubbles:true}));
        [...document.querySelectorAll('.modal button')].find(x=>x.textContent==='Zapisz pojazd').click();
      }`)
      await delay(300)
      assert.equal(database.prepare('SELECT mileage FROM vehicles WHERE id=?').get(vehicleOnly).mileage,76543)
      console.log('CUSTOMER_VEHICLE_EDIT','customer company and vehicle mileage editing verified')
      const profileOrder=database.prepare("INSERT INTO orders(vehicle_id,title,status,labor_hours,labor_rate,parts_sale,parts_cost) VALUES (?,'Rozrząd i serwis','NAPRAWA',2,220,300,120)").run(vehicleOnly).lastInsertRowid
      database.prepare("INSERT INTO payments(order_id,amount,method) VALUES (?,250,'KARTA')").run(profileOrder)
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.customerRecords tbody tr')].find(x=>x.textContent.includes('Klient Pojazdu UI')).click()`)
      await delay(350)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.customerProfileHero h2').textContent`),'Klient Pojazdu UI')
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.customerProfileMetrics').textContent.includes('740')`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.customerPaymentList').textContent.includes('250')`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.customerOrderHistory').textContent.includes('Rozrząd i serwis')`),true)
      await capture('customer-profile')
      await win.webContents.executeJavaScript(`document.querySelector('.customerVehicleCard').click()`)
      await delay(300)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.modalhead h2').textContent.includes('PO DELETE')`),true)
      await win.webContents.executeJavaScript(`document.querySelector('.modalhead button').click()`)
      await delay(200)
      console.log('CUSTOMER_PROFILE','customer totals, payments, orders and vehicle drill-down verified')
      const standaloneCustomersBefore=database.prepare('SELECT COUNT(*) n FROM customers').get().n
      await win.webContents.executeJavaScript(`document.querySelector('.standaloneVehicleButton').click()`)
      await delay(200)
      await win.webContents.executeJavaScript(`{
        const setInput=(label,value)=>{const field=[...document.querySelectorAll('.modal label')].find(x=>x.textContent.startsWith(label)).querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(field,value);field.dispatchEvent(new Event('input',{bubbles:true}))};
        setInput('Nr rej.','PO SOLO1');setInput('Marka','Toyota');setInput('Model','Corolla');
        [...document.querySelectorAll('.modal button')].find(x=>x.textContent==='Zapisz pojazd').click();
      }`)
      await delay(400)
      assert.equal(database.prepare("SELECT COUNT(*) n FROM vehicles WHERE plate='PO SOLO1' AND customer_id IS NULL").get().n,1)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM customers').get().n,standaloneCustomersBefore)
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.standaloneVehicleRow')].some(x=>x.textContent.includes('PO SOLO1')&&x.textContent.includes('Bez właściciela'))`),true)
      console.log('STANDALONE_VEHICLE','vehicle saved and displayed without creating or selecting a customer')
      await win.webContents.executeJavaScript(`window.confirm=()=>true;[...document.querySelectorAll('[aria-label]')].find(x=>x.getAttribute('aria-label').includes('PO DELETE')&&x.classList.contains('recordDelete')).click()` )
      await delay(350)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM vehicles WHERE id=?').get(vehicleOnly).n,0)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM customers WHERE id=?').get(vehicleOnlyCustomer).n,1)
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('[aria-label]')].find(x=>x.getAttribute('aria-label').includes('Klient Kaskada UI')&&x.classList.contains('recordDelete')).click()` )
      await delay(350)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM customers WHERE id=?').get(cascadeCustomer).n,0)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM vehicles WHERE id=?').get(cascadeVehicle).n,0)
      assert.equal(database.prepare('SELECT COUNT(*) n FROM orders WHERE id=?').get(cascadeOrder).n,0)
      console.log('CUSTOMER_VEHICLE_DELETE','vehicle-only and full customer cascade deletion verified')
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="VIN / AZTEC"]').click()`)
      await delay(400)
      await win.webContents.executeJavaScript(`{
        const field=document.querySelector('.scanRaw.lab');
        Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(field,'WVWZZZ1JZXW000001');
        field.dispatchEvent(new Event('input',{bubbles:true}));
      }`)
      await win.webContents.executeJavaScript(`document.querySelector('.scanRaw.lab').closest('.panel').querySelector('button.primary').click()`)
      await delay(350)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.scanResult b').textContent`),'WVWZZZ1JZXW000001')
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.scanSaved').classList.contains('ok')`),true)
      await capture('zebra-scanner')
      await win.webContents.executeJavaScript(`document.querySelector('.scanResult').closest('.panel').querySelector('.actionrow button.primary').click()`)
      await delay(400)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.scannerIntakeNotice').textContent.includes('WVWZZZ1JZXW000001')`),true)
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.formgrid label')].find(x=>x.textContent.startsWith('VIN')).querySelector('input').value`),'WVWZZZ1JZXW000001')
      console.log('ZEBRA_SCAN_INTAKE','captured scan persisted and VIN transferred to quick intake')
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="VIN / AZTEC"]').click()`)
      await delay(300)
      await win.webContents.executeJavaScript(`{
        const field=document.querySelector('.scanRaw.lab');
        Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(field,${JSON.stringify(registrationSample)});
        field.dispatchEvent(new Event('input',{bubbles:true}));
        field.closest('.panel').querySelector('button.primary').click();
      }`)
      await delay(500)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.registrationDecoded').textContent.includes('TOYOTA')`),true)
      await win.webContents.executeJavaScript(`document.querySelector('.scanResult').closest('.panel').querySelector('.actionrow button.primary').click()`)
      await delay(350)
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.formgrid label')].find(x=>x.textContent.startsWith('Marka')).querySelector('select').value`),'Toyota')
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.formgrid label')].find(x=>x.textContent.startsWith('Model')).querySelector('select').value`),'Corolla')
      console.log('AZTEC_VEHICLE_AUTOFILL','decoded uppercase make and model matched catalog values in quick intake')
      assert.equal(await win.webContents.executeJavaScript('window.scrollY'), 0)
      await capture('intake')
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Workflow"]').click()`)
      await delay(400)
      await capture('workflow')
      assert.equal((await inspect()).fatal, false)
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Workshop LIVE"]').click()`)
      await delay(650)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.wlRadar')`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.wlStage').length`),5)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.wlCar').length > 0`),true)
      assert.equal((await inspect()).overflow,false)
      await capture('workshop-live')
      win.setSize(1100,800)
      await delay(350)
      assert.equal((await inspect()).overflow,false)
      await capture('workshop-live-1100')
      win.setSize(1500,940)
      await delay(250)
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Cennik Autologiki"]').click()`)
      await delay(500)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.catalogVariantRows>button').length`),871)
      assert.equal((await inspect()).fatal,false)
      await capture('catalog-price-book')
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Szablony prac"]').click()`)
      await delay(500)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.ptCatalogCard').length`),48)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.ptStats').textContent.includes('871')`),true)
      assert.equal((await inspect()).fatal,false)
      await capture('procedure-templates')
      await win.webContents.executeJavaScript(`document.querySelector('.ptCatalogCard footer button').click()`)
      await delay(250)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.ptPreviewList').length`),6)
      await capture('procedure-template-preview')
      await win.webContents.executeJavaScript(`document.querySelector('.ptPreviewHead .primary').click()`)
      await delay(350)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.ptCustomCard').length`),1)
      assert.equal(require('../electron/db.cjs').getDb().prepare('SELECT COUNT(*) n FROM work_templates WHERE active=1').get().n,1)
      win.setSize(1100,800)
      await delay(300)
      assert.equal((await inspect()).overflow,false)
      await capture('procedure-templates-1100')
      win.setSize(1500,940)
      await delay(200)
      const monday = new Date()
      monday.setDate(monday.getDate()-((monday.getDay()+6)%7))
      monday.setHours(0,0,0,0)
      const overnightStart = new Date(monday)
      overnightStart.setDate(overnightStart.getDate()+1)
      overnightStart.setHours(22,30,0,0)
      const overnightEnd = new Date(overnightStart.getTime()+2*60*60*1000)
      const overnight = require('../electron/appointments.cjs').createAppointment(require('../electron/db.cjs').getDb(),{
        title:'Wizyta nocna UI',
        start_at:overnightStart.toISOString(),
        end_at:overnightEnd.toISOString(),
        bay:'Stanowisko 1',
        status:'PLAN'
      })
      const collisionStart = new Date(overnightStart.getTime()+30*60*1000)
      const collisionEnd = new Date(collisionStart.getTime()+45*60*1000)
      require('../electron/appointments.cjs').createAppointment(require('../electron/db.cjs').getDb(),{
        title:'Nakładająca się wizyta UI',
        start_at:collisionStart.toISOString(),
        end_at:collisionEnd.toISOString(),
        bay:'Stanowisko 1',
        status:'POTWIERDZONY'
      })
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Terminarz 2.0"]').click()`)
      await delay(500)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.plannerBoard')`),true)
      const overnightSegments = await win.webContents.executeJavaScript(`[
        ...document.querySelectorAll('[data-appointment-id="${overnight.id}"]')
      ].map(x=>x.textContent)`)
      assert.equal(overnightSegments.length,2)
      assert.equal(overnightSegments[0].includes('24:00'),true)
      assert.equal(overnightSegments[0].includes('1 h 30 min'),true)
      assert.equal(overnightSegments[1].includes('30 min'),true)
      assert.equal(overnightSegments[0].includes('Kolizja stanowiska'),true)
      await win.webContents.executeJavaScript(`document.querySelector('[data-appointment-id="${overnight.id}"]').click()`)
      await delay(150)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.plannerCollisionNotice')?.textContent.includes('Nakładająca się wizyta UI')`),true)
      await win.webContents.executeJavaScript(`document.querySelector('.plannerModal button[type="submit"]').click()`)
      await delay(100)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.plannerCollisionConfirm')`),true)
      await win.webContents.executeJavaScript(`document.querySelector('.plannerModalHead>button').click()`)
      assert.equal((await inspect()).fatal,false)
      console.log('SCHEDULE_OVERNIGHT','cross-day appointment rendered as two daily segments; collision preview and confirmation verified')
      await capture('schedule')
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Dokumentacja techniczna"]').click()`)
      await delay(500)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.manualModule')`),true)
      assert.equal((await inspect()).fatal,false)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.manualBranch>.manualBranchHead').length`),28)
      await capture('technical-manual')
      await win.webContents.executeJavaScript(`{
        [...document.querySelectorAll('.manualBranch>.manualBranchHead')].find(x=>x.querySelector('b')?.textContent==='Audi').click();
      }`)
      await delay(150)
      await win.webContents.executeJavaScript(`{
        [...document.querySelectorAll('.manualBranchDepth1>.manualBranchHead')].find(x=>x.querySelector('b')?.textContent==='A3').click();
      }`)
      await delay(150)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.manualVehicleLeaf').length > 0`),true)
      await win.webContents.executeJavaScript(`document.querySelector('.manualVehicleLeaf').click()`)
      await delay(150)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.manualWelcome h2').textContent`),'Audi A3')
      await capture('technical-manual-catalog')
      win.setSize(1100,800)
      await delay(350)
      assert.equal((await inspect()).overflow,false)
      await capture('technical-manual-1100')
      win.setSize(1500,940)
      await delay(250)
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Ustawienia"]').click()`)
      await delay(450)
      const expectedVersion=require('../package.json').version
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.updateBrand h2').textContent`),`Wersja ${expectedVersion}`)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.updateMessage').textContent.includes('trybie developerskim')`),true)
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.updateActions button')].some(x=>x.textContent.includes('Sprawdź aktualizacje'))`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.sidefoot').textContent.includes(${JSON.stringify(expectedVersion)})`),true)
      await capture('settings-updates')
      assert.equal((await inspect()).fatal,false)
      database.prepare("UPDATE orders SET status='WYDANE',archived_at=CURRENT_TIMESTAMP WHERE id=(SELECT o.id FROM orders o JOIN vehicles v ON v.id=o.vehicle_id WHERE v.plate='PO 3WN90')").run()
      await win.webContents.executeJavaScript(`document.querySelector('.commandLauncher').click()`)
      await delay(300)
      assert.equal(await win.webContents.executeJavaScript(`!!document.querySelector('.commandPalette')`), true)
      await capture('search')
      await win.webContents.executeJavaScript(`{const input=document.querySelector('.commandPalette input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'PO 3WN90');input.dispatchEvent(new Event('input',{bubbles:true}))}`)
      await delay(250)
      assert.equal(await win.webContents.executeJavaScript(`[...document.querySelectorAll('.paletteKind')].some(x=>x.textContent==='ARCHIWUM')`),true)
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.paletteResults button')].find(x=>x.querySelector('.paletteKind')?.textContent==='ARCHIWUM').click()`)
      await delay(300)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.centerHero').textContent.includes('PO 3WN90')`),true)
      await win.webContents.executeJavaScript(`document.querySelector('.commandLauncher').click()`)
      await delay(200)
      await win.webContents.executeJavaScript(`{const input=document.querySelector('.commandPalette input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Skoda');input.dispatchEvent(new Event('input',{bubbles:true}))}`)
      await delay(250)
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.paletteResults button')].find(x=>x.querySelector('.paletteKind')?.textContent==='POJAZD').click()`)
      await delay(300)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.modalhead h2').textContent.includes('PZ 291RT')`),true)
      await win.webContents.executeJavaScript(`document.querySelector('.modalhead button').click();document.querySelector('.commandLauncher').click()`)
      await delay(200)
      await win.webContents.executeJavaScript(`{const input=document.querySelector('.commandPalette input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Klient demo');input.dispatchEvent(new Event('input',{bubbles:true}))}`)
      await delay(250)
      await win.webContents.executeJavaScript(`[...document.querySelectorAll('.paletteResults button')].find(x=>x.querySelector('.paletteKind')?.textContent==='KLIENT').click()`)
      await delay(300)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.customerProfileHero h2').textContent`),'Klient demo')
      await win.webContents.executeJavaScript(`document.querySelector('.modalhead button').click()`)
      console.log('GLOBAL_SEARCH_DEEP_LINKS','archived order, normalized vehicle make and exact customer profiles open from Ctrl+K')
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Należności"]').click()`)
      await delay(350)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelectorAll('.debtorsTable tbody tr').length>0`),true)
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.debtorsTable').textContent.includes('Pozostało')`),true)
      await capture('debtors')
      await win.webContents.executeJavaScript(`document.querySelector('.debtorsTable tbody button').click()`)
      await delay(350)
      assert.equal((await inspect()).title,'Centrum zlecenia')
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('.centerHero').textContent.includes('PO 3WN90')`),true)
      const auditPages=['Do uwagi','Diagnostyka','Baza wiedzy','Asystent wiedzy','Pracownicy','Autologika Care','Dokumenty']
      for(const title of auditPages){
        await win.webContents.executeJavaScript(`document.querySelector('nav button[title=${JSON.stringify(title)}]').click()`)
        await delay(300)
        const state=await inspect()
        assert.equal(state.fatal,false,title)
        assert.equal(state.overflow,false,title)
      }
      console.log('NAVIGATION_AUDIT',`${auditPages.length+1} previously uncovered views rendered without errors; debtors open the linked order`)
      await win.webContents.executeJavaScript(`document.querySelector('nav button[title="Pulpit"]').click()`)
      await delay(400)
      // Verify the empty state using the same isolated database.
      require('../electron/db.cjs').getDb().prepare('DELETE FROM orders').run()
      win.webContents.reload()
      await new Promise(resolve => win.webContents.once('did-finish-load', resolve))
      await delay(400)
      assert.equal((await inspect()).radar, 0)
      assert.equal((await inspect()).fatal, false)
      await capture('dashboard-empty')
      console.log('RENDERER_ERRORS', JSON.stringify(errors))
      console.log('ARTIFACTS', output)
      app.exit(errors.length ? 1 : 0)
    } catch (e) { console.error('RENDERER_ERRORS', JSON.stringify(errors)); console.error(e); app.exit(1) }
  })
})
app.whenReady().then(() => {
  const db = require('../electron/db.cjs').getDb()
  const rows = [
    ['PO 7AK21','BMW','320d','Wymiana rozrządu','NAPRAWA','BRAK',2450],
    ['PZ 842KL','Audi','A4 Avant','Układ hamulcowy — oś przednia','AKCEPTACJA','DECYZJA',1820],
    ['PO 3WN90','Mercedes','C 220','Serwis olejowy i przegląd','GOTOWE','BRAK',890],
    ['PZ 291RT','Škoda','Octavia','Diagnostyka układu chłodzenia','DIAGNOZA','CZESCI',650],
    ['PO 9HG42','Volvo','XC60','Weryfikacja zawieszenia','PRZYJETE','BRAK',350],
  ]
  for(const [plate,make,model,title,status,wait,price] of rows){
    const v=db.prepare('INSERT INTO vehicles(customer_id,plate,make,model) VALUES (1,?,?,?)').run(plate,make,model)
    db.prepare('INSERT INTO orders(vehicle_id,title,status,wait_state,labor_hours,labor_rate,parts_cost,source) VALUES (?,?,?,?,?,?,?,?)').run(v.lastInsertRowid,title,status,wait,2,price/2,200,'polecenie')
  }
  db.prepare("INSERT INTO work_logs(order_id,worker,note) VALUES (2,'Diagnosta','Podgląd interfejsu')").run()
})
require('../electron/main.cjs')
