import React,{useEffect,useState} from 'react'
import {Icon} from './ui.jsx'

const searchKey=value=>String(value||'').trim().toLocaleLowerCase('pl-PL').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('ł','l').replaceAll('ø','o')

export function Care({api,openOrder,openVehicle,Panel,Empty,Modal}){
 const[rows,setRows]=useState([]),[vehicles,setVehicles]=useState([]),[show,setShow]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('ALL'),[busyId,setBusyId]=useState(null)
 const load=()=>api.reminders.list().then(setRows)
 useEffect(()=>{load();api.vehicles.list().then(setVehicles)},[])
 const counts={OVERDUE:rows.filter(x=>x.urgency==='OVERDUE').length,SOON:rows.filter(x=>x.urgency==='SOON').length,PLANNED:rows.filter(x=>x.urgency==='PLANNED').length}
 const visible=rows.filter(row=>(filter==='ALL'||row.urgency===filter)&&(!query.trim()||searchKey([row.plate,row.make,row.model,row.customer,row.title,row.note].join(' ')).includes(searchKey(query))))
 const finish=async id=>{setBusyId(id);try{await api.reminders.done(id);await load()}finally{setBusyId(null)}}
 const urgencyText=row=>row.urgency==='OVERDUE'?'PO TERMINIE':row.urgency==='SOON'?'WKRÓTCE':'ZAPLANOWANE'
 const dueText=row=>{const parts=[];if(row.due_date)parts.push(new Date(row.due_date+'T12:00:00').toLocaleDateString('pl-PL'));if(row.due_mileage)parts.push(Number(row.due_mileage).toLocaleString('pl-PL')+' km');return parts.join(' · ')||'Bez terminu'}
 return <section className="carePage">
  <div className="careHero"><div><span className="sectionEyebrow">AUTOLOGIKA CARE</span><h2>Serwis wraca do Ciebie <span>we właściwym czasie.</span></h2><p>Jedna lista przypomnień z Centrum zlecenia, profilu pojazdu i obsługi posprzedażowej.</p></div><button className="primary" onClick={()=>setShow(true)}>+ Nowe przypomnienie</button></div>
  <div className="careStats"><button className={filter==='OVERDUE'?'active overdue':''} onClick={()=>setFilter(filter==='OVERDUE'?'ALL':'OVERDUE')}><small>WYMAGAJĄ REAKCJI</small><b>{counts.OVERDUE}</b><span>po dacie lub przebiegu</span></button><button className={filter==='SOON'?'active soon':''} onClick={()=>setFilter(filter==='SOON'?'ALL':'SOON')}><small>NAJBLIŻSZE 30 DNI</small><b>{counts.SOON}</b><span>lub do 1500 km</span></button><button className={filter==='PLANNED'?'active':''} onClick={()=>setFilter(filter==='PLANNED'?'ALL':'PLANNED')}><small>DALSZY PLAN</small><b>{counts.PLANNED}</b><span>zaplanowane później</span></button></div>
  <div className="careToolbar"><label><Icon name="search" size={16}/><input aria-label="Szukaj przypomnienia" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rejestracja, klient, auto lub usługa…"/></label>{filter!=='ALL'&&<button onClick={()=>setFilter('ALL')}>Wyczyść filtr ×</button>}<span>{visible.length} {visible.length===1?'przypomnienie':'przypomnień'}</span></div>
  <div className="careList">{visible.map(row=><article className={'careCard '+row.urgency.toLowerCase()} key={row.id}><div className="careDate"><small>{urgencyText(row)}</small><b>{dueText(row)}</b>{row.mileage_remaining!==null&&<span>{row.mileage_remaining<=0?'przekroczono o '+Math.abs(row.mileage_remaining).toLocaleString('pl-PL')+' km':'pozostało '+row.mileage_remaining.toLocaleString('pl-PL')+' km'}</span>}</div><div className="careVehicle"><button onClick={()=>openVehicle?.(row.vehicle_id)}>{row.plate||'bez rej.'}</button><span>{row.make} {row.model}</span><small>{row.customer||'Bez przypisanego klienta'}</small></div><div className="careTask"><h3>{row.title}</h3>{row.note&&<p>{row.note}</p>}{row.order_id&&<button className="careOrder" onClick={()=>openOrder?.(row.order_id)}>Zlecenie #{row.order_id} · {row.order_title||'otwórz'} →</button>}</div><button className="careDone" disabled={busyId===row.id} onClick={()=>finish(row.id)}>{busyId===row.id?'Zapisywanie…':'✓ Wykonane'}</button></article>)}{!visible.length&&<Empty text={rows.length?'Brak przypomnień pasujących do filtra.':'Brak otwartych przypomnień serwisowych.'}/>}</div>
  {show&&<NewCareReminder api={api} Modal={Modal} vehicles={vehicles} close={()=>setShow(false)} saved={()=>{setShow(false);load()}}/>}
 </section>
}

function NewCareReminder({api,Modal,vehicles,close,saved}){
 const[d,setD]=useState({vehicle_id:vehicles[0]?.id||'',title:'Serwis olejowy',due_date:'',due_mileage:'',note:''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const save=async()=>{setBusy(true);setError('');try{await api.reminders.create(d);saved()}catch(e){setError(e.message||String(e));setBusy(false)}}
 return <Modal title="Nowe przypomnienie Autologika Care" close={close}><div className="formgrid"><label className="wide">Pojazd<select value={d.vehicle_id} onChange={e=>setD({...d,vehicle_id:e.target.value})}><option value="">Wybierz pojazd</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.plate||'bez rej.'} — {v.make} {v.model}</option>)}</select></label><label className="wide">Co przypomnieć<input value={d.title} onChange={e=>setD({...d,title:e.target.value})}/></label><label>Data<input type="date" value={d.due_date} onChange={e=>setD({...d,due_date:e.target.value})}/></label><label>Przebieg<input type="number" min="0" value={d.due_mileage} onChange={e=>setD({...d,due_mileage:e.target.value})}/></label><label className="wide">Notatka<textarea value={d.note} onChange={e=>setD({...d,note:e.target.value})} placeholder="Zakres obsługi, preferowany kontakt, ustalenia…"/></label></div>{error&&<p className="formError" role="alert">{error}</p>}<div className="modalactions"><button disabled={busy} onClick={close}>Anuluj</button><button className="primary" disabled={busy||!d.vehicle_id||!d.title.trim()} onClick={save}>{busy?'Zapisywanie…':'Zapisz przypomnienie'}</button></div></Modal>
}
