import React,{useEffect,useState} from 'react'

export function Finance({api,money,Loading,Modal,Empty}){
 const[d,setD]=useState(null),[a,setA]=useState(null),[monthTarget,setMonthTarget]=useState(50000),[selectedKpi,setSelectedKpi]=useState('')
 useEffect(()=>{Promise.all([api.dashboard(),api.finance.analytics(),api.settings?.monthlyTarget?.()||Promise.resolve(50000)]).then(([data,analytics,target])=>{setD(data);setA(analytics);setMonthTarget(Number(target)||50000)})},[])
 if(!d||!a)return <Loading/>
 const rev=Number(d.month.revenue),cost=Number(d.month.variableCost),actual=Number(a.current.actual_hours||0),margin=rev-cost,targetPct=Math.min(100,Math.round(rev/monthTarget*100)),paid=Number(a.current.paid||0),receivables=Number(a.current.receivables||0)
 const now=new Date(),daysInMonth=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),elapsed=Math.max(1,now.getDate()),forecast=rev/elapsed*daysInMonth
 const maxDay=Math.max(1,...a.daily.map(x=>Number(x.revenue||0)))
 const best=a.daily.reduce((winner,row)=>Number(row.revenue||0)>Number(winner?.revenue||0)?row:winner,null),activeDays=a.daily.filter(row=>Number(row.revenue)>0).length,maxMix=Math.max(1,...a.mix.map(row=>Number(row.revenue||0))),thresholds=[30000,50000,75000,100000,150000],nextThreshold=thresholds.find(value=>value>rev)
 const change=Number(a.current.previous_revenue)>0?(rev/Number(a.current.previous_revenue)-1)*100:null,marginPct=rev?margin/rev*100:0
 return <section className="financeDashboard">
  <div className="financeHero"><div className="financeHeroMain"><small>WYNIK WARSZTATU / BIEŻĄCY MIESIĄC</small><div className="financeRevenue"><div><span>WARTOŚĆ ZLECEŃ</span><h2>{money(rev)}</h2></div>{change!==null&&<em className={change>=0?'up':'down'}>{change>=0?'↗':'↘'} {Math.abs(change).toFixed(1)}% m/m</em>}</div><div className="targetTrack"><i style={{width:`${targetPct}%`}}/></div><div className="financeTargetLine"><span>{targetPct}% celu {money(monthTarget)}</span><b>{Math.max(0,monthTarget-rev)>0?`pozostało ${money(monthTarget-rev)}`:'cel osiągnięty'}</b></div><div className="financeCash"><div><span>WPŁACONO W MIESIĄCU</span><b>{money(paid)}</b></div><div><span>DO ROZLICZENIA</span><b>{money(receivables)}</b></div><div><span>ZLECENIA</span><b>{a.current.orders||0}</b></div></div></div><div className={forecast>=monthTarget?'financeForecast good':'financeForecast'} style={{'--forecast':`${Math.min(100,Math.round(forecast/monthTarget*100))}%`}}><div className="forecastRing"><span>PROGNOZA</span><b>{Math.round(forecast/monthTarget*100)}%</b></div><strong>{money(forecast)}</strong><small>{forecast>=monthTarget?'Obecne tempo prowadzi powyżej celu.':`Do tempa celu brakuje ${money(Math.max(0,monthTarget-forecast))}.`}</small></div></div>
  <div className="financeKpis"><FinanceKpi tone="green" label="Marża kontrybucyjna" value={money(margin)} detail={rev?`${marginPct.toFixed(1)}% wartości zleceń`:'Brak sprzedaży w miesiącu'} progress={marginPct} onClick={()=>setSelectedKpi('margin')}/><FinanceKpi tone="gold" label="Średnie zlecenie" value={money(a.current.avg_ticket)} detail={`${a.current.orders||0} zleceń w miesiącu`} onClick={()=>setSelectedKpi('average')}/><FinanceKpi tone="blue" label="Marża na częściach" value={money(a.current.parts_margin)} detail={`${money(a.current.parts_sale)} sprzedaży części`} onClick={()=>setSelectedKpi('parts')}/><FinanceKpi tone="violet" label="Robocizna i usługi" value={money(a.current.labor_services_revenue??a.current.labor_revenue)} detail={actual?`${money(rev/actual)} obrotu / realną godzinę`:'Uruchom timer pracy, aby policzyć ELR'} onClick={()=>setSelectedKpi('labor')}/></div>
  <div className="financeCharts"><article className="financePanel financeTrend"><header><div><small>TREND 30 DNI</small><h3>Wartość otwartych zleceń według dnia</h3></div><div className="trendStats"><span>Aktywne dni <b>{activeDays}</b></span><span>Najlepszy dzień <b>{best&&Number(best.revenue)>0?money(best.revenue):'—'}</b></span></div></header><div className={'financeChartPlot '+(activeDays?'':'isEmpty')}>{a.daily.map((row,index)=>{const value=Number(row.revenue||0),showLabel=index%5===0||index===a.daily.length-1,height=value?Math.max(7,value/maxDay*100):1;return <div className="financeChartBar" key={row.day} title={`${row.day}: ${money(value)}`} aria-label={`${row.day}: ${money(value)}`}><div className="barValue" style={{'--bar-height':`${height}%`}}>{value>0&&<span>{money(value)}</span>}<i style={{height:`${height}%`}}/></div><small>{showLabel?String(row.day).slice(8):''}</small></div>})}{!activeDays&&<div className="financeChartEmpty"><b>Brak obrotu w tym okresie</b><span>Wykres uzupełni się po zapisaniu wartości zleceń.</span></div>}</div></article><article className="financePanel financeMix"><header><div><small>STRUKTURA SPRZEDAŻY</small><h3>Miks zleceń</h3></div><b>{a.current.orders||0}</b></header>{a.mix.length?<div className="mixList">{a.mix.map((row,index)=>{const share=rev?Number(row.revenue||0)/rev*100:0;return <div className="mixItem" key={row.category} style={{'--mix':`${Number(row.revenue||0)/maxMix*100}%`,'--mix-color':['#b9ef79','#dfb95c','#6fb4a0','#8e98d9'][index%4]}}><div className="mixLabel"><span><i/>{row.category}</span><b>{money(row.revenue)}</b></div><div className="mixTrack"><i/></div><small>{row.count} {row.count===1?'zlecenie':'zleceń'} · {share.toFixed(0)}% wartości</small></div>})}</div>:<div className="financeMixEmpty"><span>◌</span><b>Brak zleceń w tym miesiącu</b><small>Struktura sprzedaży pojawi się automatycznie.</small></div>}</article></div>
  <article className="financePanel financeThresholds"><header><div><small>SKALA WARSZTATU</small><h3>Progi miesięcznego obrotu</h3></div>{nextThreshold?<span>Następny próg <b>{money(nextThreshold)}</b></span>:<span><b>Najwyższy próg osiągnięty</b></span>}</header><div className="thresholdList">{thresholds.map(value=>{const hit=rev>=value,next=value===nextThreshold;return <div key={value} className={hit?'hit':next?'next':''}><i>{hit?'✓':value/1000+'k'}</i><div><b>{money(value)}</b><span>{hit?'Osiągnięty':`Brakuje ${money(value-rev)}`}</span></div></div>})}</div></article>{selectedKpi&&<FinanceBreakdownModal money={money} Modal={Modal} Empty={Empty} kind={selectedKpi} analytics={a} close={()=>setSelectedKpi('')}/>}
 </section>
}
function FinanceKpi({tone,label,value,detail,progress,onClick}){return <button type="button" data-finance-kpi={label} className={`financeKpi ${tone}`} onClick={onClick}><div className="financeKpiTop"><span>{label}</span><i/></div><b>{value}</b><small>{detail}</small>{progress!==undefined&&<div className="financeKpiMeter"><i style={{width:`${Math.max(0,Math.min(100,progress))}%`}}/></div>}<em>Pokaż rozbicie →</em></button>}
function FinanceBreakdownModal({kind,analytics,close,money,Modal,Empty}){
 const configs={margin:{title:'Marża kontrybucyjna — szczegóły',value:row=>Number(row.total||0)-Number(row.cost||0),columns:['Sprzedaż','Koszt','Marża'],cells:row=>[money(row.total),money(row.cost),money(Number(row.total||0)-Number(row.cost||0))]},average:{title:'Średnie zlecenie — szczegóły',value:row=>Number(row.total||0),columns:['Data','Wartość','Udział'],cells:row=>[new Date(row.opened_at).toLocaleDateString('pl-PL'),money(row.total),analytics.current.revenue?`${(Number(row.total||0)/Number(analytics.current.revenue)*100).toFixed(1)}%`:'0%']},parts:{title:'Marża na częściach — szczegóły',filter:row=>Number(row.parts_sale||0)||Number(row.parts_cost||0),value:row=>Number(row.parts_sale||0)-Number(row.parts_cost||0),columns:['Sprzedaż części','Zakup części','Marża'],cells:row=>[money(row.parts_sale),money(row.parts_cost),money(Number(row.parts_sale||0)-Number(row.parts_cost||0))]},labor:{title:'Robocizna i usługi — szczegóły',filter:row=>Number(row.legacy_labor||0)||Number(row.item_labor||0)||Number(row.service_sale||0)||Number(row.diagnosis_sale||0),value:row=>Number(row.legacy_labor||0)+Number(row.item_labor||0)+Number(row.service_sale||0)+Number(row.diagnosis_sale||0),columns:['Robocizna','Usługi / diagnoza','Razem'],cells:row=>{const labor=Number(row.legacy_labor||0)+Number(row.item_labor||0),services=Number(row.service_sale||0)+Number(row.diagnosis_sale||0);return[money(labor),money(services),money(labor+services)]}}},config=configs[kind]||configs.margin,rows=(analytics.details||[]).filter(config.filter||(()=>true)),total=rows.reduce((sum,row)=>sum+config.value(row),0)
 return <Modal wide title={config.title} close={close}><div className="financeBreakdown"><div className="financeBreakdownSummary"><div><small>BIEŻĄCY MIESIĄC</small><b>{money(total)}</b><span>{rows.length} {rows.length===1?'zlecenie':'zleceń'} w rozbiciu</span></div><p>Klikalne zestawienie pokazuje, z których zleceń powstał wynik. Kwoty odpowiadają bieżącym danym zapisanym w zleceniach.</p></div><div className="financeBreakdownTable"><table><thead><tr><th>Zlecenie</th>{config.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.plate||`#${row.id}`} · {row.make} {row.model}</b><small>{row.customer||'Klient nieprzypisany'} · {row.title}</small></td>{config.cells(row).map((value,index)=><td key={config.columns[index]} className={index===config.columns.length-1?'result':''}>{value}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty text="Brak pozycji tworzących ten wynik w bieżącym miesiącu."/>}</div><div className="actionrow right"><button onClick={close}>Zamknij</button></div></div></Modal>
}

export function Documents({api,Panel,Loading}){
 const[docs,setDocs]=useState(null),[error,setError]=useState('')
 useEffect(()=>{api.documents.list().then(setDocs).catch(e=>setError(e.message))},[])
 if(error)return <Panel title="Dokumenty"><div className="warnbox">{error}</div></Panel>
 if(!docs)return <Loading/>
 const groups=[...new Set(docs.map(d=>d.category))]
 return <section>
   <div className="documentHero"><div><span className="eyebrow">AUTOLOGIKA KNOWLEDGE PACK</span><h2>Dokumentacja warsztatu</h2><p>Wszystkie przygotowane strategie, plany i formularze PDF są dostępne bezpośrednio z aplikacji. Pliki są przechowywane lokalnie razem z Autologika OS.</p></div><div className="docCount"><strong>{docs.length}</strong><span>PDF</span></div></div>
   {groups.map(group=><div key={group} className="docGroup"><div className="docGroupTitle"><span>{group}</span><i/></div><div className="documentGrid">{docs.filter(d=>d.category===group).map(d=><article className="documentCard" key={d.id}><div className="docIcon">PDF</div><div className="docBody"><small>{d.category}</small><h3>{d.title}</h3><p>{d.description}</p><code>{d.file}</code></div><div className="docActions">{d.exists?<><button className="primary" onClick={()=>api.documents.open(d.id)}>Otwórz PDF</button><button onClick={()=>api.documents.reveal(d.id)}>Pokaż plik</button></>:<span className="docMissing">Brak pliku</span>}</div></article>)}</div></div>)}
 </section>
}

export function Employees({api,Card,money,durText,Panel,Empty,Modal}){
 const[rows,setRows]=useState([]),[prod,setProd]=useState([]),[bays,setBays]=useState([]),[show,setShow]=useState(false);const load=()=>Promise.all([api.employees.list(),api.worklog.productivity(),api.employees.bays()]).then(([a,b,c])=>{setRows(a);setProd(b);setBays(c)});useEffect(()=>{load()},[])
 return <section><div className="metrics"><Card title="Aktywni pracownicy" value={rows.filter(x=>x.active).length} sub="zarejestrowani"/><Card title="Czas zespołu / miesiąc" value={durText(prod.reduce((s,x)=>s+Number(x.minutes||0),0))} sub="wg timerów"/><Card title="Zlecenia obsłużone" value={prod.reduce((s,x)=>s+Number(x.jobs||0),0)} sub="licznik per pracownik"/><Card title="Koszt czasu" value={money(prod.reduce((s,x)=>s+Number(x.labor_cost||0),0))} sub="stawki kosztowe × timer"/></div><div className="toolbar"><div className="grow"/><button className="primary" onClick={()=>setShow(true)}>+ Pracownik</button></div><Panel title="Wydajność zespołu — bieżący miesiąc">{prod.length?<div className="teamGrid">{prod.map(e=><div className="employeeCard" key={e.id}><b>{e.name}</b><span>{e.role}</span><strong>{durText(e.minutes)}</strong><small>{e.jobs} zleceń · koszt czasu {money(e.labor_cost)}</small><div className="progress"><i style={{width:`${Math.min(100,(Number(e.minutes||0)/(22*8*60))*100)}%`}}/></div></div>)}</div>:<Empty/>}</Panel><Panel title="Wydajność stanowisk — bieżący miesiąc">{bays.length?<div className="teamGrid">{bays.map(b=><div className="employeeCard" key={b.bay}><b>{b.bay}</b><strong>{Number(b.booked_hours||0).toFixed(1)} h</strong><small>{b.appointments} terminów · {b.linked_orders} zleceń powiązanych</small><span>Przychód powiązanych zleceń: {money(b.linked_revenue)}</span><div className="progress"><i style={{width:`${Math.min(100,(Number(b.booked_hours||0)/(22*8))*100)}%`}}/></div></div>)}</div>:<Empty text="Brak terminów w bieżącym miesiącu."/>}</Panel>{show&&<NewEmployee api={api} Modal={Modal} close={()=>setShow(false)} saved={()=>{setShow(false);load()}}/>}</section>
}
function NewEmployee({api,Modal,close,saved}){const[d,setD]=useState({name:'',role:'Mechanik',hourly_cost:0});return <Modal title="Nowy pracownik" close={close}><div className="formgrid"><label className="wide">Imię / nazwa<input value={d.name} onChange={e=>setD({...d,name:e.target.value})}/></label><label>Rola<input value={d.role} onChange={e=>setD({...d,role:e.target.value})}/></label><label>Koszt 1 h dla firmy<input type="number" value={d.hourly_cost} onChange={e=>setD({...d,hourly_cost:e.target.value})}/></label></div><div className="modalactions"><button onClick={close}>Anuluj</button><button className="primary" disabled={!d.name} onClick={()=>api.employees.create(d).then(saved)}>Dodaj</button></div></Modal>}

