import React,{useEffect,useState} from 'react'
import {analyzeScan} from './zebra-scanner.js'

export function Diagnostics({api,Panel,DiagnosisEditor}){const[orders,setOrders]=useState([]),[id,setId]=useState(''),[d,setD]=useState({});useEffect(()=>{api.orders.list().then(r=>{setOrders(r.filter(x=>x.status!=='WYDANE'));if(r[0])setId(r[0].id)})},[]);useEffect(()=>{if(id)api.diagnostics.get(id).then(x=>setD(x||{symptom_confirmed:'',dtcs:'',measurements:'',hypothesis:'',conclusion:'',recommendation:'',time_hours:0}))},[id]);return <section><div className="toolbar"><select value={id} onChange={e=>setId(e.target.value)}>{orders.map(o=><option key={o.id} value={o.id}>{o.plate} — {o.title}</option>)}</select></div>{id&&<Panel title="Karta diagnostyczna"><DiagnosisEditor diag={d} setDiag={setD} recordKey={id} onSave={()=>api.diagnostics.save(Number(id),d)}/></Panel>}</section>}
export function Knowledge({api,Modal}){const[q,setQ]=useState(''),[rows,setRows]=useState([]),[show,setShow]=useState(false);const load=()=>api.knowledge.list(q).then(setRows);useEffect(()=>{load()},[q]);return <section><div className="toolbar"><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Szukaj objawu, DTC, marki, tagu…"/><button className="primary" onClick={()=>setShow(true)}>+ Przypadek</button></div><div className="knowledgeGrid">{rows.map(x=><div className="case" key={x.id}><small>{x.vehicle} {x.engine}</small><h3>{x.symptom}</h3>{x.dtcs&&<p><b>DTC:</b> {x.dtcs}</p>}<p><b>Przyczyna:</b> {x.cause||'—'}</p><p><b>Rozwiązanie:</b> {x.solution||'—'}</p><em>{x.tags}</em></div>)}</div>{show&&<NewCase api={api} Modal={Modal} close={()=>setShow(false)} saved={()=>{setShow(false);load()}}/>}</section>}
function NewCase({api,Modal,close,saved}){const[d,setD]=useState({vehicle:'',engine:'',symptom:'',dtcs:'',measurements:'',cause:'',solution:'',tags:''});return <Modal wide title="Nowy przypadek diagnostyczny" close={close}><div className="formgrid">{[['vehicle','Pojazd'],['engine','Silnik'],['symptom','Objaw'],['dtcs','DTC'],['tags','Tagi']].map(([k,l])=><label key={k} className={k==='symptom'?'wide':''}>{l}<input value={d[k]} onChange={e=>setD({...d,[k]:e.target.value})}/></label>)}{[['measurements','Pomiary'],['cause','Przyczyna'],['solution','Rozwiązanie']].map(([k,l])=><label className="wide" key={k}>{l}<textarea value={d[k]} onChange={e=>setD({...d,[k]:e.target.value})}/></label>)}</div><button className="primary" disabled={!d.symptom} onClick={async()=>{await api.knowledge.create(d);saved()}}>Zapisz przypadek</button></Modal>}

export function AssistantKnowledge({api,Panel,Empty}){
 const[q,setQ]=useState(''),[res,setRes]=useState(null),[loading,setLoading]=useState(false)
 const go=async()=>{if(!q.trim())return;setLoading(true);setRes(await api.assistant.search(q));setLoading(false)}
 return <section><Panel title="Asystent wiedzy — offline" action={<span className="tag gotowe">bez chmury</span>}><p className="muted">Przeszukuje Twoją lokalną bazę przypadków i szereguje podobne naprawy po objawach, DTC, silniku, pomiarach i przyczynie. To moduł retrieval, nie model generatywny — nie wymyśla danych serwisowych.</p><div className="askrow"><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Np. Touran 2.0 TDI brak mocy P0299 po rozgrzaniu…"/><button className="primary" onClick={go}>{loading?'Szukam…':'Analizuj bazę'}</button></div></Panel>{res&&<div className="grid2"><Panel title={`Najbardziej podobne przypadki (${res.results.length})`}>{res.results.length?res.results.map(c=><div className="caseResult" key={c.id}><div><b>{c.vehicle||'Pojazd'} · {c.engine||''}</b><em>score {c.score}</em></div><strong>{c.symptom}</strong>{c.dtcs&&<span>DTC: {c.dtcs}</span>}{c.cause&&<span>Przyczyna: {c.cause}</span>}{c.solution&&<small>Rozwiązanie: {c.solution}</small>}</div>):<Empty text="Brak podobnych przypadków. Po zapisaniu kolejnych diagnostyk baza będzie coraz bardziej użyteczna."/>}</Panel><Panel title="Checklista startowa">{res.hints.length?res.hints.map((h,i)=><div className="hint" key={i}>✓ {h}</div>):<p className="muted">Brak reguły podpowiedzi dla tego opisu. Najważniejszym wynikiem są przypadki z Twojej bazy.</p>}<div className="notice">Tryb: lokalne wyszukiwanie przypadków. W kolejnej wersji można podłączyć lokalny model lub wybrany model API.</div></Panel></div>}</section>
}

export function VinScanner({onUseScan,api,Panel,Empty}){
 const[last,setLast]=useState(null),[history,setHistory]=useState([]),[manual,setManual]=useState(''),[env,setEnv]=useState(null),[capturePath,setCapturePath]=useState(''),[saved,setSaved]=useState(false),[decoding,setDecoding]=useState(false),[decodeError,setDecodeError]=useState('')
 const accept=async raw=>{let x=analyzeScan(raw);setLast(x);setSaved(false);setDecodeError('');api.zebra?.recordCapture?.(x).then(result=>{setCapturePath(result.path);setSaved(true)}).catch(()=>setSaved(false));if(x.kind!=='VIN'&&(x.length>=40||x.byteLength>=20)){setDecoding(true);try{const registration=await api.zebra.decodeRegistration({raw:x.raw,hex:x.sdk?.hex||''});x={...x,registration,vin:registration.form.vin||x.vin,kind:'DOWÓD REJ.'};setLast(x)}catch(error){setDecodeError(error.message||String(error))}finally{setDecoding(false)}}setHistory(h=>[x,...h].slice(0,20))}
 useEffect(()=>{Promise.all([api.zebra?.environment?.(),api.zebra?.capturePath?.()]).then(([environment,file])=>{setEnv(environment);setCapturePath(file)}).catch(()=>setEnv({ready:false}))},[])
 return <div className="zebraScannerPage">
  <div className="scannerHero"><div><span className="eyebrow">ZEBRA / USB HID / SNAPI</span><h2>AZTEC / VIN — Scanner Lab</h2><p>Skaner HID działa globalnie w całej aplikacji. Poprawny VIN lub AZTEC automatycznie otwiera Szybkie przyjęcie. Moduł rozpoznaje też XML BarcodeEvent z Zebra CoreScanner/SNAPI i odtwarza bajty RAW bez utraty danych.</p></div><span className="globalHidStatus">● HID GLOBALNY</span></div>
  <div className="scannerGrid"><Panel title="Ostatni skan">{last?<><div className="scanResult"><span>{last.kind}</span><b>{last.registration?.form?.plate||last.vin||`${last.byteLength||last.length} ${last.byteLength?'B':'zn.'}`}</b><small>{new Date(last.capturedAt).toLocaleString('pl-PL')}</small></div>{last.sdk&&<div className="sdkMeta"><b>{last.sdk.model||'Zebra scanner'}</b><span>SN: {last.sdk.serial||'—'}</span><span>datatype: {last.sdk.datatype||'—'}</span><span>RAW: {last.sdk.bytes.length} B</span></div>}{decoding&&<div className="aztecDecoding">Dekodowanie polskiego dowodu rejestracyjnego…</div>}{last.registration?.ok&&<div className="registrationDecoded"><div><small>REJESTRACJA</small><b>{last.registration.form.plate||'—'}</b></div><div><small>VIN</small><b>{last.registration.form.vin||'—'}</b></div><div><small>POJAZD</small><b>{last.registration.form.make} {last.registration.form.model}</b></div><div><small>ROK / MOC</small><b>{last.registration.form.year||'—'} · {last.registration.form.power_hp||'—'} KM</b></div><div className="wide"><small>POSIADACZ</small><b>{last.registration.form.customer_name||'—'}</b></div></div>}{decodeError&&<p className="muted">{decodeError} Surowy skan pozostaje zapisany.</p>}<textarea className="scanRaw" value={last.raw} readOnly/><div className="actionrow"><button onClick={()=>api.system.copyText(last.raw)}>Kopiuj tekst</button>{last.sdk?.hex&&<button onClick={()=>api.system.copyText(last.sdk.hex)}>Kopiuj HEX RAW</button>}{last.vin&&<button onClick={()=>api.system.copyText(last.vin)}>Kopiuj VIN</button>}{(last.vin||last.registration?.ok)&&<button className="primary" onClick={()=>onUseScan?.(last)}>Autofill szybkiego przyjęcia →</button>}</div><div className={'scanSaved '+(saved?'ok':'')}><span>{saved?'✓ Skan zapisany do analizy':'Zapisywanie śladu skanu…'}</span>{capturePath&&<code>{capturePath}</code>}</div></>:<Empty text="Czekam na pierwszy skan z urządzenia Zebra…"/>}</Panel>
  <Panel title="Zebra SDK / CoreScanner"><div className={'sdkStatus '+(env?.ready?'ok':'warn')}><b>{env?.ready?'✓ GOTOWE DO SNAPI':'○ SNAPI NIEAKTYWNE'}</b><span>{!env?'Sprawdzanie środowiska…':env.platform!=='win32'?'Natywny Zebra SDK jest przeznaczony dla Windows.':env.sdkInstalled?`CoreScanner: ${env.coreScannerService}`:'Nie wykryto Zebra Scanner SDK.'}</span></div>{env?.paths?.map(x=><code key={x}>{x}</code>)}<p className="muted">Po instalacji Zebra Scanner SDK przełączymy urządzenie na USB SNAPI. CoreScanner przekazuje w BarcodeEvent typ kodu, data label i RAW bytes — to jest właściwa droga dla binarnego AZTEC z dowodu.</p></Panel></div>
  <div className="scannerGrid"><Panel title="Laboratorium RAW / BarcodeEvent"><p className="muted">Wklej payload HID albo cały XML <code>pscanData</code> z Zebra BarcodeEvent. Parser automatycznie wyciągnie &lt;rawdata&gt; 0xNN, rozpozna polski dowód i zachowa surowy skan.</p><textarea className="scanRaw lab" value={manual} onChange={e=>setManual(e.target.value)} placeholder={'<outArgs>...<rawdata>0x.. 0x..</rawdata>...</outArgs>\nlub payload AZTEC z HID'}/><button className="primary" disabled={!manual.trim()} onClick={()=>{accept(manual);setManual('')}}>Dekoduj RAW</button></Panel>
  <Panel title="Obsługa dowodu rejestracyjnego"><div className="checkPlan"><span>1</span><p><b>Odbiór</b><small>HID i SNAPI przekazują pełny payload AZTEC.</small></p><span>2</span><p><b>Dekodowanie</b><small>System rozpakowuje standard polskiego dowodu rejestracyjnego.</small></p><span>3</span><p><b>Kontrola</b><small>Przed zapisem pokazuje odczytane dane pojazdu i posiadacza.</small></p><span>4</span><p><b>Autofill</b><small>Jednym kliknięciem uzupełnia Szybkie przyjęcie.</small></p></div></Panel></div>
  <Panel title="Historia tej sesji">{history.length?<div className="scanHistory">{history.map((x,i)=><div key={x.capturedAt+i}><b>{x.kind}</b><span>{x.vin||x.raw.slice(0,80)}</span><small>{x.byteLength?`${x.byteLength} B`:`${x.length} zn.`}</small></div>)}</div>:<Empty text="Brak skanów w tej sesji."/>}</Panel>
  <div className="scannerInfo"><b>Tryb odbioru sprzętu gotowy</b><span>Podłącz Zebrę przez USB, pozostaw aktywny HID i zeskanuj najpierw zwykły kod, a potem AZTEC z dowodu. Każdy wynik zapisuje się z długością oraz surową treścią. Rozpoznany VIN można od razu wysłać do Szybkiego przyjęcia. Pełny live SNAPI uruchomimy po instalacji Zebra Scanner SDK i pierwszym skanie z urządzenia.</span></div>
 </div>
}
