import React,{useCallback,useEffect,useMemo,useState} from 'react'
import {WORK_CATALOG} from './work-catalog.js'
import {procedureFor} from './work-procedures.js'
import {LoadingState} from './ui.jsx'

const lines=value=>String(value||'').split('\n').map(item=>item.trim()).filter(Boolean)

export function WorkshopLive({openOrder,api,labels,refresh}){
 const[data,setData]=useState({orders:[],appointments:[],active:[],parts:[]}),[now,setNow]=useState(new Date()),[stageFilter,setStageFilter]=useState('')
 const[liveState,setLiveState]=useState({loading:true,error:'',updated:null})
 const load=useCallback(async(manual=false)=>{if(manual)setLiveState(x=>({...x,loading:true,error:''}));try{const from=new Date();from.setHours(0,0,0,0);const to=new Date(from);to.setDate(to.getDate()+1);const [orders,appointments,active,parts]=await Promise.all([api.orders.list(),api.appointments.list(from.toISOString(),to.toISOString()),api.worklog.active(),api.jobParts.list('OTWARTE')]);setData({orders:orders.filter(x=>x.status!=='WYDANE'),appointments,active,parts});setLiveState({loading:false,error:'',updated:new Date()})}catch(error){console.error('Workshop LIVE refresh failed',error);setLiveState(x=>({...x,loading:false,error:'Nie udało się odświeżyć danych. Spróbuj ponownie.',updated:x.updated}))}},[api])
 useEffect(()=>{load(true);const poll=()=>{if(!document.hidden)load(false)},tick=()=>{if(!document.hidden)setNow(new Date())},visible=()=>{if(!document.hidden){setNow(new Date());load(false)}};const a=setInterval(poll,5000),b=setInterval(tick,1000);document.addEventListener('visibilitychange',visible);return()=>{clearInterval(a);clearInterval(b);document.removeEventListener('visibilitychange',visible)}},[load,refresh])
 const waiting=data.orders.filter(x=>x.wait_state&&x.wait_state!=='BRAK'),lateParts=data.parts.filter(x=>x.expected_at&&new Date(x.expected_at)<now&&!['ODEBRANE','ZAMONTOWANE','ANULOWANE'].includes(x.status)),next=data.appointments.filter(x=>new Date(x.end_at)>=now).sort((a,b)=>new Date(a.start_at)-new Date(b.start_at)).slice(0,6)
 const activeFor=orderId=>data.active.find(x=>Number(x.order_id)===Number(orderId)),appointmentFor=order=>data.appointments.find(x=>Number(x.order_id)===Number(order.id)||Number(x.vehicle_id)===Number(order.vehicle_id))
 const visibleOrders=[...data.orders].filter(order=>!stageFilter||order.status===stageFilter).sort((a,b)=>Number(Boolean(activeFor(b.id)))-Number(Boolean(activeFor(a.id)))||Number(Boolean(b.wait_state&&b.wait_state!=='BRAK'))-Number(Boolean(a.wait_state&&a.wait_state!=='BRAK'))||Number(a.id)-Number(b.id))
 const waitText=state=>state==='CZESCI'?'Części':state==='KLIENT'?'Klient':state==='DECYZJA'?'Decyzja':'Blokada'
 const elapsed=start=>{const mins=Math.max(0,Math.floor((now-new Date(start))/60000));return mins<60?`${mins} min`:`${Math.floor(mins/60)} h ${String(mins%60).padStart(2,'0')} min`}
 const stages=[['PRZYJETE','Przyjęte'],['DIAGNOZA','Diagnoza'],['AKCEPTACJA','Akceptacja'],['NAPRAWA','Naprawa'],['GOTOWE','Gotowe']]
 const statusIndex=status=>Math.max(0,stages.findIndex(([key])=>key===status))
 const loadPct=Math.min(100,Math.round(data.orders.length/8*100))
 const radarPositions=[[50,14],[77,30],[83,60],[65,82],[34,82],[17,59],[22,29],[50,90]]
 const timerWord=count=>count===1?'timer':count%10>=2&&count%10<=4&&(count%100<12||count%100>14)?'timery':'timerów'
 const full=()=>{const el=document.querySelector('.workshopLive');if(!document.fullscreenElement)el?.requestFullscreen?.();else document.exitFullscreen?.()}
 if(liveState.loading&&!liveState.updated&&!liveState.error)return <LoadingState label="Łączę dane hali" detail="Pobieram aktywne zlecenia, terminy, timery i dostawy części."/>
 return <section className="workshopLive">
  <div className="wlBackdrop"><i/><i/><i/></div>
  <div className="wlTop"><div className="wlClock"><small>AUTOLOGIKA / WORKSHOP LIVE</small><h2>{now.toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})}<span>:{now.toLocaleTimeString('pl-PL',{second:'2-digit'}).slice(-2)}</span></h2><p>{now.toLocaleDateString('pl-PL',{weekday:'long',day:'2-digit',month:'long'})}</p></div><div className={'wlHeadline '+(liveState.error?'error':'')}><span><i/> {liveState.error?'PROBLEM Z DANYMI':'CENTRUM OPERACYJNE ONLINE'}</span><b>{liveState.error?'Ostatni poprawny stan pozostaje widoczny':data.active.length?'Praca trwa na hali':'Warsztat gotowy do pracy'}</b><small>{liveState.error||liveState.updated?liveState.error||`Ostatnia aktualizacja ${liveState.updated.toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'Łączenie z bazą warsztatu…'}</small></div><div className="wlTopActions"><button className="wlRefresh" data-live-refresh disabled={liveState.loading} onClick={()=>load(true)}>{liveState.loading?'↻':'↻'} <span>{liveState.loading?'Odświeżanie':'Odśwież'}</span></button><button className="wlFullscreen" onClick={full}>⛶ <span>Pełny ekran</span></button></div></div>
  {liveState.error&&<div className="wlDataError" role="alert"><span>!</span><b>{liveState.error}</b><button onClick={()=>load(true)}>Spróbuj ponownie</button></div>}
  <div className="wlOverview">
   <div className="wlRadar" aria-label={`${visibleOrders.length} widocznych pojazdów na radarze`}><div className="wlRadarGrid"/><i className="wlRing outer"/><i className="wlRing one"/><i className="wlRing two"/><i className="wlSweep"/>{visibleOrders.slice(0,8).map((o,i)=>{const [x,y]=radarPositions[i];return <button key={o.id} data-live-radar-order={o.id} className={'wlBlip '+String(o.status||'').toLowerCase()+(activeFor(o.id)?' working':'')+(o.wait_state&&o.wait_state!=='BRAK'?' waiting':'')} style={{'--x':`${x}%`,'--y':`${y}%`,'--delay':`${i*70}ms`}} aria-label={`Otwórz zlecenie ${o.plate||o.id}: ${o.title}`} title={`${o.plate} · ${o.title}`} onClick={()=>openOrder?.(o.id)}><i/><span>{o.plate||`#${o.id}`}</span><small>{labels[o.status]||o.status}</small></button>})}<div className="wlRadarCore"><b>{visibleOrders.length}</b><span>{stageFilter?'W ETAPIE':'AUT NA HALI'}</span><small>{visibleOrders.length>8?`+${visibleOrders.length-8} poza mapą`:`${data.active.length} ${timerWord(data.active.length)}`}</small></div></div>
   <div className="wlKpis"><article><small>AKTYWNE AUTA</small><b>{data.orders.length}</b><span>{data.appointments.length} terminów dzisiaj</span></article><article className="green"><small>AKTYWNE TIMERY</small><b>{data.active.length}</b><span>{data.active.length?'mechanicy rejestrują czas':'brak pracy w toku'}</span></article><article className={waiting.length?'amber':''}><small>BLOKERY</small><b>{waiting.length}</b><span>{waiting.length?'wymagają reakcji':'przepływ bez blokad'}</span></article><article className={lateParts.length?'red':''}><small>OPÓŹNIONE CZĘŚCI</small><b>{lateParts.length}</b><span>{lateParts.length?'sprawdź dostawy':'dostawy pod kontrolą'}</span></article></div>
   <div className="wlCapacity"><div><small>OBCIĄŻENIE HALI</small><b>{loadPct}%</b></div><span><i style={{width:`${loadPct}%`}}/></span><p>{Math.max(0,8-data.orders.length)} wolnych miejsc w planie operacyjnym</p></div>
  </div>
  <div className="wlFlow">{stages.map(([key,name],i)=>{const count=data.orders.filter(o=>o.status===key).length;return <button type="button" data-live-stage={key} aria-pressed={stageFilter===key} className={'wlStage '+(count?'active':'')+(stageFilter===key?' selected':'')} key={key} onClick={()=>setStageFilter(current=>current===key?'':key)}><span>0{i+1}</span><b>{count}</b><small>{name}</small>{i<stages.length-1&&<i>›</i>}</button>})}</div>
  <div className="wlLayout"><div className="wlMain"><div className="wlSectionHead"><div><small>HALA / STATUS NA ŻYWO</small><h3>Mapa bieżącej pracy</h3></div><div className="wlMapState"><span><i/> {visibleOrders.length} z {data.orders.length} pojazdów</span>{stageFilter&&<button onClick={()=>setStageFilter('')}>× {labels[stageFilter]}</button>}</div></div><div className="wlCars">{visibleOrders.slice(0,10).map((o,index)=>{const active=activeFor(o.id),appointment=appointmentFor(o),progress=statusIndex(o.status),open=()=>openOrder?.(o.id);return <article key={o.id} role="button" tabIndex="0" aria-label={`Otwórz zlecenie ${o.plate||o.id}`} onClick={open} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}}} className={'wlCar '+String(o.status).toLowerCase()+(active?' isWorking':'')+(o.wait_state&&o.wait_state!=='BRAK'?' isWaiting':'')} style={{animationDelay:`${index*55}ms`}}><div className="wlCarTop"><span className="wlBay">{appointment?.bay||`Kolejka ${String(index+1).padStart(2,'0')}`}</span><em>{labels[o.status]||o.status}</em></div><div className="wlVehicle"><div><b>{o.plate||'BEZ NR'}</b><span>{o.make} {o.model}</span></div>{active&&<div className="wlTimer"><i/><b>{elapsed(active.started_at)}</b><small>{active.worker}</small></div>}</div><p>{o.title}</p><div className="wlProgress">{stages.map((s,i)=><i key={s[0]} className={i<=progress?'done':''}/>)}</div><footer>{o.wait_state&&o.wait_state!=='BRAK'?<strong>⚠ Czeka: {waitText(o.wait_state)}</strong>:active?<strong className="running">● Praca w toku</strong>:<span>Następny etap: {stages[Math.min(progress+1,stages.length-1)][1]}</span>}<b>Otwórz zlecenie →</b></footer></article>})}{!visibleOrders.length&&<div className="wlEmpty"><span>◇</span><b>{stageFilter?'Brak aut na tym etapie':'Hala jest wolna'}</b><p>{stageFilter?'Wybierz inny etap albo pokaż wszystkie pojazdy.':'Brak aktywnych samochodów.'}</p>{stageFilter&&<button onClick={()=>setStageFilter('')}>Pokaż wszystkie auta</button>}</div>}</div></div>
   <aside className="wlSide"><section><div className="wlSectionHead"><div><small>PLAN DNIA</small><h3>Najbliższe terminy</h3></div><b>{next.length}</b></div><div className="wlNext">{next.map((a,i)=><article key={a.id}><time>{new Date(a.start_at).toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})}</time><i className={new Date(a.start_at)<=now?'now':''}/><div><b>{a.plate||'Termin'}</b><span>{a.title}</span><small>{a.bay}</small></div></article>)}{!next.length&&<p className="wlMuted">Brak kolejnych terminów na dziś.</p>}</div></section><section className={(waiting.length||lateParts.length)?'attention':''}><div className="wlSectionHead"><div><small>ALERTY OPERACYJNE</small><h3>Wymaga reakcji</h3></div><b>{waiting.length+lateParts.length}</b></div><div className="wlAlerts">{waiting.slice(0,5).map(o=><button key={o.id} onClick={()=>openOrder?.(o.id)}><i>!</i><div><b>{o.plate||`#${o.id}`} · {waitText(o.wait_state)}</b><span>{o.title}</span></div><em>→</em></button>)}{lateParts.slice(0,4).map(p=><button className="danger" key={'p'+p.id} onClick={()=>openOrder?.(p.order_id)} aria-label={`Otwórz zlecenie z opóźnioną częścią ${p.name}`}><i>!</i><div><b>{p.plate||p.name} · dostawa</b><span>{p.name}</span></div><em>→</em></button>)}{!waiting.length&&!lateParts.length&&<div className="wlAllClear"><i>✓</i><b>Wszystko pod kontrolą</b><span>Brak aktywnych blokerów.</span></div>}</div></section></aside>
  </div>
 </section>
}

export function ProcedureTemplates({api,money,Modal}){
 const[rows,setRows]=useState([]),[edit,setEdit]=useState(null),[mode,setMode]=useState('CATALOG'),[query,setQuery]=useState(''),[group,setGroup]=useState('WSZYSTKIE'),[limit,setLimit]=useState(48),[preview,setPreview]=useState(null);const empty={name:'',group_name:'Własne',variant:'standard',scope:'',hours:1,rate:220,pre:'',steps:'',qc:'',parts:'',materials:'',recommendations:'',safety:''}
 const load=()=>api.workTemplates.list().then(setRows);useEffect(()=>{load()},[])
 const toEdit=x=>({...x,pre:(x.pre||[]).join('\n'),steps:(x.steps||[]).join('\n'),qc:(x.qc||[]).join('\n'),parts:(x.parts||[]).map(y=>y.name||y).join('\n'),materials:(x.materials||[]).map(y=>y.name||y).join('\n'),recommendations:(x.recommendations||[]).join('\n'),safety:(x.safety||[]).join('\n')})
 const payload=x=>({...x,pre:lines(x.pre),steps:lines(x.steps),qc:lines(x.qc),parts:lines(x.parts).map(name=>({name,qty:1,selected:true})),materials:lines(x.materials).map(name=>({name,qty:1,selected:true})),recommendations:lines(x.recommendations),safety:lines(x.safety)})
 const catalog=useMemo(()=>WORK_CATALOG.flatMap(g=>g.jobs.flatMap(job=>job.variants.map(variant=>({group:g.group,job,variant,procedure:procedureFor(job,variant)})))),[])
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('pl');return catalog.filter(x=>(group==='WSZYSTKIE'||x.group===group)&&(!q||`${x.group} ${x.job.name} ${x.variant.name} ${x.variant.customer_description}`.toLocaleLowerCase('pl').includes(q)))},[catalog,query,group])
 useEffect(()=>setLimit(48),[query,group])
 const copyBuiltIn=async x=>{const h=Number(x.variant.hours||x.job.hours||1),price=Number(x.variant.price||x.job.price||h*220),p=x.procedure;await api.workTemplates.create({name:x.job.name,group_name:x.group,variant:x.variant.name,scope:p.customerScope||x.variant.customer_description||x.job.scope||'',hours:h,rate:h?price/h:220,pre:p.pre,steps:p.steps,qc:p.qc,parts:p.parts,materials:p.materials,recommendations:p.recommendations,safety:p.safety});await load();setPreview(null);setMode('CUSTOM')}
 const selectedProcedure=preview?.procedure
 const list=(title,items,kind='')=><div className={'ptPreviewList '+kind}><h4>{title}<span>{items?.length||0}</span></h4>{items?.length?items.map((item,i)=><p key={i}><i>{String(i+1).padStart(2,'0')}</i><span>{item.name||item}</span></p>):<small>Brak dodatkowych pozycji.</small>}</div>
 return <section className="procedureTemplates"><div className="ptHero"><div><small>AUTOLOGIKA / BIBLIOTEKA STANDARDÓW</small><h2>Szablony prac i procedur</h2><p>Gotowe zakresy pracy, checklisty, części, materiały i kontrola jakości dla całego katalogu Autologiki.</p></div><div className="ptStats"><div><b>{WORK_CATALOG.reduce((n,g)=>n+g.jobs.length,0)}</b><span>prac</span></div><div><b>{catalog.length}</b><span>wariantów</span></div><div><b>{rows.length}</b><span>własnych</span></div></div><button className="primary" onClick={()=>setEdit({...empty})}>＋ Własny szablon</button></div>
  <div className="ptMode"><button className={mode==='CATALOG'?'active':''} onClick={()=>setMode('CATALOG')}><span>◆</span><div><b>Katalog Autologiki</b><small>{catalog.length} gotowych wariantów</small></div></button><button className={mode==='CUSTOM'?'active':''} onClick={()=>setMode('CUSTOM')}><span>✦</span><div><b>Moje szablony</b><small>{rows.length} zapisanych standardów</small></div></button></div>
  {mode==='CATALOG'?<><div className="ptToolbar"><div><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Szukaj pracy, układu lub wariantu…"/></div><select value={group} onChange={e=>setGroup(e.target.value)}><option value="WSZYSTKIE">Wszystkie grupy ({WORK_CATALOG.length})</option>{WORK_CATALOG.map(g=><option key={g.group}>{g.group}</option>)}</select><b>{filtered.length} wyników</b></div><div className="ptCatalogGrid">{filtered.slice(0,limit).map((x,index)=>{const p=x.procedure;return <article className="ptCatalogCard" key={x.variant.id} style={{animationDelay:`${Math.min(index,12)*30}ms`}}><header><span>{x.group}</span><em>{Number(x.variant.hours||x.job.hours||0).toFixed(1)} h · {money(x.variant.price||x.job.price)}</em></header><h3>{x.job.name}</h3><p>{x.variant.name}</p><div className="ptCounts"><span><b>{p.pre.length}</b> przed</span><span><b>{p.steps.length}</b> kroków</span><span><b>{p.qc.length}</b> QC</span><span><b>{p.parts.length}</b> części</span></div><small>{x.variant.customer_description||x.job.scope}</small><footer><button onClick={()=>setPreview(x)}>Podgląd procedury</button><button className="primary" onClick={()=>copyBuiltIn(x)}>＋ Kopia własna</button></footer></article>})}</div>{limit<filtered.length&&<button className="ptMore" onClick={()=>setLimit(x=>x+48)}>Pokaż kolejne 48 <span>{filtered.length-limit} pozostało</span></button>}</>:<div className="ptCustomGrid">{rows.map(x=><article className="ptCustomCard" key={x.id}><header><span>{x.group_name}</span><em>WŁASNY</em></header><h3>{x.name}</h3><p>{x.variant||'standard'}</p><div className="ptCounts"><span><b>{x.pre?.length||0}</b> przed</span><span><b>{x.steps?.length||0}</b> kroków</span><span><b>{x.qc?.length||0}</b> QC</span><span><b>{x.parts?.length||0}</b> części</span></div><footer><button onClick={()=>setEdit(toEdit(x))}>Edytuj</button><button className="danger" onClick={()=>confirm('Usunąć własny szablon?')&&api.workTemplates.remove(x.id).then(load)}>Usuń</button></footer></article>)}{!rows.length&&<div className="ptEmpty"><span>✦</span><h3>Brak własnych szablonów</h3><p>Wybierz gotową procedurę z katalogu i utwórz kopię do edycji albo zacznij od pustego szablonu.</p><button className="primary" onClick={()=>setMode('CATALOG')}>Przejdź do katalogu</button></div>}</div>}
  {preview&&<Modal wide title="Podgląd gotowej procedury" close={()=>setPreview(null)}><div className="ptPreviewHead"><div><small>{preview.group}</small><h2>{preview.job.name}</h2><p>{preview.variant.name} · {Number(preview.variant.hours||preview.job.hours||0).toFixed(1)} h · {money(preview.variant.price||preview.job.price)}</p></div><button className="primary" onClick={()=>copyBuiltIn(preview)}>＋ Utwórz własną kopię</button></div><div className="ptScope"><small>OPIS DLA KLIENTA / PROTOKOŁU</small><p>{selectedProcedure.customerScope||preview.variant.customer_description}</p></div><div className="ptPreviewGrid">{list('Przed rozpoczęciem',selectedProcedure.pre)}{list('Przebieg pracy',selectedProcedure.steps)}{list('Kontrola jakości',selectedProcedure.qc,'qc')}{list('Sugerowane części',selectedProcedure.parts)}{list('Materiały / chemia',selectedProcedure.materials)}{list('Bezpieczeństwo',selectedProcedure.safety,'warning')}</div><div className="actionrow right"><button onClick={()=>setPreview(null)}>Zamknij</button></div></Modal>}
  {edit&&<Modal title={edit.id?'Edytuj szablon':'Nowy szablon Autologiki'} close={()=>setEdit(null)}><div className="formgrid"><label>Nazwa<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Grupa<input value={edit.group_name} onChange={e=>setEdit({...edit,group_name:e.target.value})}/></label><label>Wariant<input value={edit.variant} onChange={e=>setEdit({...edit,variant:e.target.value})}/></label><label>Czas [h]<input type="number" step="0.1" value={edit.hours} onChange={e=>setEdit({...edit,hours:e.target.value})}/></label><label>Stawka [zł/h]<input type="number" step="10" value={edit.rate} onChange={e=>setEdit({...edit,rate:e.target.value})}/></label><label className="wide">Opis do protokołu<textarea value={edit.scope} onChange={e=>setEdit({...edit,scope:e.target.value})}/></label><label>Przed rozpoczęciem <small>1 punkt / linia</small><textarea value={edit.pre} onChange={e=>setEdit({...edit,pre:e.target.value})}/></label><label>Przebieg pracy<textarea value={edit.steps} onChange={e=>setEdit({...edit,steps:e.target.value})}/></label><label>QC<textarea value={edit.qc} onChange={e=>setEdit({...edit,qc:e.target.value})}/></label><label>Sugerowane części<textarea value={edit.parts} onChange={e=>setEdit({...edit,parts:e.target.value})}/></label><label>Materiały / chemia<textarea value={edit.materials} onChange={e=>setEdit({...edit,materials:e.target.value})}/></label><label>Zalecenia<textarea value={edit.recommendations} onChange={e=>setEdit({...edit,recommendations:e.target.value})}/></label><label className="wide">Uwagi bezpieczeństwa<textarea value={edit.safety} onChange={e=>setEdit({...edit,safety:e.target.value})}/></label></div><div className="actionrow right"><button onClick={()=>setEdit(null)}>Anuluj</button><button className="primary" disabled={!edit.name.trim()} onClick={async()=>{const p=payload(edit);if(edit.id)await api.workTemplates.update(edit.id,p);else await api.workTemplates.create(p);setEdit(null);await load();setMode('CUSTOM')}}>Zapisz szablon</button></div></Modal>}
 </section>
}

export function Kanban({changed,openOrder,api,statuses,labels,money,refresh}){
 const[rows,setRows]=useState([]);const load=()=>api.orders.list().then(setRows);useEffect(()=>{load()},[refresh])
 const drop=async(id,status)=>{await api.orders.updateStatus(id,status);load();changed()}
 const stages=statuses.slice(0,-1),activeRows=rows.filter(x=>x.status!=='WYDANE'),inProgress=activeRows.filter(x=>x.status==='DIAGNOZA'||x.status==='NAPRAWA').length,waiting=activeRows.filter(x=>x.status==='AKCEPTACJA').length,ready=activeRows.filter(x=>x.status==='GOTOWE').length
 const focusStage=stage=>document.querySelector(`[data-workflow-column="${stage}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})
 return <section className="workflowPage">
  <div className="workflowSummary"><div><small>PRZEPŁYW PRACY / NA ŻYWO</small><h2>{activeRows.length} aktywnych zleceń</h2><p>Przeciągnij kartę do kolejnego etapu albo otwórz zlecenie, aby zobaczyć pełny zakres prac.</p></div><div className="workflowPulse"><div><span>W realizacji</span><b>{inProgress}</b></div><div className="amber"><span>Akceptacja</span><b>{waiting}</b></div><div className="green"><span>Gotowe</span><b>{ready}</b></div></div></div>
  <nav className="workflowLegend" aria-label="Przejdź do etapu zleceń">{stages.map((stage,index)=>{const count=activeRows.filter(row=>row.status===stage).length;return <button type="button" className={`stage-${stage.toLowerCase()}`} key={stage} onClick={()=>focusStage(stage)}><i/><span><small>ETAP {String(index+1).padStart(2,'0')}</small>{labels[stage]}</span><b>{count}</b></button>})}</nav>
  <div className="kanban">{stages.map(s=>{const stageRows=activeRows.filter(x=>x.status===s);return <div data-workflow-column={s} className={'kanCol stage-'+s.toLowerCase()} key={s} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(Number(e.dataTransfer.getData('text/plain')),s)}><div className="kanHead"><div><small>ETAP {stages.indexOf(s)+1}</small><b>{labels[s]}</b></div><span>{stageRows.length}</span></div>{stageRows.map(o=><article className="kanCard" draggable key={o.id} onDragStart={e=>e.dataTransfer.setData('text/plain',String(o.id))}><div className="kanCardTop"><b>{o.plate||'bez nr'}</b><span className={'tag '+String(o.status).toLowerCase()}>{labels[o.status]}</span></div><h3>{o.title||'Bez opisu zlecenia'}</h3><small>{o.customer||'Klient nieprzypisany'}</small><div className="kanCardBottom"><em>{money(o.total)}</em><button type="button" onClick={()=>openOrder?.(o.id)}>Otwórz →</button></div></article>)}{!stageRows.length&&<div className="kanEmpty"><span>✓</span><b>Brak zleceń</b><small>Upuść tutaj kartę z poprzedniego etapu.</small></div>}</div>})}</div>
 </section>
}
