import React,{useState} from 'react'
import {Icon} from './ui.jsx'
import './order-workspace.css'

const money=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:0}).format(Number(n||0))
const stages=[['PRZYJETE','Przyjęte'],['DIAGNOZA','Diagnoza'],['AKCEPTACJA','Akceptacja'],['NAPRAWA','Naprawa'],['GOTOWE','Gotowe'],['WYDANE','Wydane']]
const openLabels={diagnosis:'diagnostykę',quote:'kosztorys',parts:'części',time:'czas pracy',approval:'akceptacje',payment:'płatność',qc:'kontrolę jakości',closeout:'zamknięcie',timeline:'historię',contact:'kontakt'}
const groups=[
 ['Realizacja',[['overview','Przegląd','dashboard'],['diagnosis','Diagnostyka','diagnostics'],['quote','Kosztorys','orders'],['parts','Części','inventory'],['time','Czas pracy','reminders']]],
 ['Dokumentacja i klient',[['docs','Zdjęcia i pliki','documents'],['contact','Kontakt','customers'],['approval','Akceptacje','check'],['reminders','Przypomnienia','schedule']]],
 ['Rozliczenie i wydanie',[['payment','Płatność','debtors'],['qc','Kontrola jakości','check'],['closeout','Zamknięcie','car'],['money','Rentowność','finance'],['timeline','Oś czasu','center']]],
]

export function OrderWorkspaceHeader({order,orders,selectOrder,advice,applyAdvice,setTab,payments,activeCount,actualMinutes,exportPdf,updateStatus,updateWait}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('')
 const run=async fn=>{if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
 const paid=payments.reduce((sum,p)=>sum+Number(p.amount||0),0),due=Math.max(0,Number(order.total||0)-paid)
 const stageIndex=stages.findIndex(([s])=>s===order.status)
 return <div className="orderWorkspaceHeader">
  <div className="workspacePicker"><label><Icon name="orders"/><span className="srOnly">Wybierz zlecenie</span><select aria-label="Wybierz zlecenie" value={order.id} onChange={e=>selectOrder(Number(e.target.value))}>{orders.map(o=><option key={o.id} value={o.id}>#{o.id} · {o.plate||'Bez rejestracji'} · {o.make} {o.model} · {o.title}</option>)}</select></label><details className="workspaceExports"><summary><Icon name="documents" size={16}/>Dokumenty PDF<Icon name="chevron" size={13}/></summary><div>{[['intake','Przyjęcie pojazdu'],['order','Karta zlecenia'],['release','Wydanie pojazdu']].map(([kind,title])=><button key={kind} disabled={busy} onClick={()=>run(()=>exportPdf(kind))}><Icon name="documents" size={15}/>{title}<Icon name="arrow" size={14}/></button>)}</div></details></div>
  <div className="workspaceHero"><div className="workspaceIdentity"><div className="workspaceCarIcon"><Icon name="car" size={30}/></div><div><div className="sectionEyebrow">ZLECENIE {String(order.id).padStart(4,'0')} <span> / </span> {order.priority==='PILNY'?'PRIORYTET PILNY':'KARTA POJAZDU'}</div><h2>{order.plate||'Bez rejestracji'}<span>{order.make} {order.model}</span></h2><p>{order.title}</p></div></div><div className="workspaceStatus"><span className={'tag '+order.status.toLowerCase()}>{stages.find(([s])=>s===order.status)?.[1]||order.status}</span><span>{order.due_at?`Termin: ${new Date(order.due_at).toLocaleDateString('pl-PL',{day:'2-digit',month:'short'})}`:'Bez ustalonego terminu'}</span></div><div className="workspaceMeta"><span><Icon name="customers" size={14}/>{order.customer||'Klient nieokreślony'}</span><span>VIN <b>{order.vin||'Nie uzupełniono'}</b></span><span>{order.engine||'Silnik nieokreślony'}</span><span>{order.mileage?`${Number(order.mileage).toLocaleString('pl-PL')} km`:'Przebieg nieokreślony'}</span><button onClick={()=>setTab('contact')}>Kontakt z klientem <Icon name="arrow" size={14}/></button></div></div>
  <div className="workspaceSummary">{[['Wartość zlecenia',money(order.total),'Kosztorys i sprzedaż','quote','orders'],['Pozostało do zapłaty',money(due),`Wpłaty: ${money(paid)}`,'payment','debtors'],['Czas pracy',`${Math.floor(actualMinutes/60)} h ${Math.floor(actualMinutes%60)} min`,activeCount?`${activeCount} aktywnych timerów`:'Brak uruchomionego timera','time','reminders']].map(([title,value,sub,tab,icon])=><button key={tab} onClick={()=>setTab(tab)}><Icon name={icon} size={19}/><div><span>{title}</span><strong>{value}</strong><small>{tab==='time'&&activeCount>0&&<i className="studioLiveDot"/>}{sub}</small></div><Icon name="arrow" size={15}/></button>)}</div>
  <div className="workspaceAdvice"><div className="adviceSymbol"><Icon name="bolt" size={21}/></div><div><span className="sectionEyebrow">NASTĘPNY KROK</span><h3>{advice.title}</h3><p>{advice.detail}</p></div><div className="workspaceAdviceActions">{advice.tab&&<button disabled={busy} className={advice.status||advice.wait?'':'primary'} onClick={()=>setTab(advice.tab)}>Otwórz {openLabels[advice.tab]||'etap'}<Icon name="arrow" size={15}/></button>}{(advice.status||advice.wait)&&<button disabled={busy} className="primary" onClick={()=>run(applyAdvice)}>{busy?'Zapisywanie…':advice.status==='WYDANE'?'Potwierdź wydanie':'Zastosuj krok'}<Icon name="arrow" size={15}/></button>}</div></div>
  {error&&<div className="workspaceError" role="alert">{error}</div>}
  <details className="workspaceProcess"><summary><Icon name="kanban" size={16}/><span>Etapy i oczekiwanie</span><b>{stages[Math.max(0,stageIndex)][1]}</b>{order.wait_state&&order.wait_state!=='BRAK'&&<em>{{KLIENT:'Na klienta',CZESCI:'Na części',DECYZJA:'Na decyzję'}[order.wait_state]}</em>}<Icon name="chevron" size={13}/></summary><div><div className="workspaceStages">{stages.map(([s,label],i)=><button key={s} disabled={busy} aria-pressed={order.status===s} className={order.status===s?'current':i<stageIndex?'completed':''} onClick={()=>run(()=>updateStatus(s))}><span>{i<stageIndex?<Icon name="check" size={12}/>:String(i+1).padStart(2,'0')}</span>{label}</button>)}</div><div className="workspaceWait"><span>Oczekiwanie</span>{[['BRAK','Bez blokady'],['KLIENT','Na klienta'],['CZESCI','Na części'],['DECYZJA','Na decyzję']].map(([s,label])=><button disabled={busy} key={s} aria-pressed={(order.wait_state||'BRAK')===s} onClick={()=>run(()=>updateWait(s))}>{label}</button>)}</div></div></details>
 </div>
}

export function OrderWorkspaceNav({tab,setTab,partsCount,activeCount}){
 return <nav className="workspaceNav" aria-label="Sekcje zlecenia">{groups.map(([title,tabs])=><div key={title}><small>{title}</small>{tabs.map(([key,label,icon])=><button key={key} aria-current={tab===key?'page':undefined} data-order-tab={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon name={icon} size={16}/><span>{label}</span>{key==='parts'&&partsCount>0&&<b>{partsCount}</b>}{key==='time'&&activeCount>0&&<b className="timerBadge">{activeCount}</b>}</button>)}</div>)}</nav>
}

export function OrderWorkspaceOverview({order,diag,parts,items,approvals,notes,files,timeline,setTab,openQuote,openPart}){
 const waiting=parts.filter(p=>!['ODEBRANE','ZAMONTOWANE','ZWROT_ZAKONCZONY','ANULOWANE'].includes(p.status))
 const pending=approvals.filter(a=>a.status==='PENDING')
 const checks=[['diagnosis','diagnostics','Diagnoza',!!diag?.conclusion,diag?.conclusion?'Wniosek diagnostyczny zapisany':'Uzupełnij wniosek diagnostyczny'],['approval','check','Akceptacja',approvals.some(a=>a.status==='APPROVED'),pending.length?`${pending.length} oczekujących decyzji`:'Sprawdź historię decyzji klienta'],['parts','inventory','Części',!waiting.length,waiting.length?`${waiting.length} pozycji wymaga reakcji`:'Brak oczekujących dostaw'],['qc','car','Kontrola jakości',!!String(notes.qc_notes||'').trim(),notes.qc_notes?'Wynik kontroli zapisany':'Zapisz wynik przed wydaniem']]
 return <div className="workspaceOverview">
  <section className="workspaceCard"><div className="workspaceCardHeading"><span className="sectionEyebrow">PUNKT WYJŚCIA</span><Icon name="diagnostics"/></div><h3>Zgłoszenie klienta</h3><p className="workspaceComplaint">{order.complaint||'Opis objawu nie został jeszcze uzupełniony.'}</p><div className="workspaceDiagnostic"><span>Wniosek diagnostyczny</span><p>{diag?.conclusion||'Diagnoza przed nami. Zapisz pomiary i potwierdź przyczynę usterki.'}</p><button className="studioTextButton" onClick={()=>setTab('diagnosis')}>{diag?.conclusion?'Otwórz kartę diagnostyczną':'Przejdź do diagnostyki'}<Icon name="arrow" size={15}/></button></div><div className="workspaceLimit"><span>Limit diagnostyki</span><b>{money(order.diagnosis_limit)}</b></div></section>
  <section className="workspaceCard"><div className="workspaceCardHeading"><span className="sectionEyebrow">GOTOWOŚĆ DO KOLEJNEGO ETAPU</span><span className="countBadge">{checks.filter(x=>x[3]).length} / 4</span></div><h3>Stan realizacji</h3><div className="workspaceChecks">{checks.map(([tab,icon,title,done,sub])=><button key={tab} onClick={()=>setTab(tab)} className={done?'done':''}><span className="workspaceCheckIcon"><Icon name={done?'check':icon} size={16}/></span><div><b>{title}</b><small>{sub}</small></div><Icon name="chevron" size={14}/></button>)}</div></section>
  <section className="workspaceCard workspaceQuickCard"><div><span className="sectionEyebrow">POD RĘKĄ</span><h3>Przejdź do działania</h3></div><div className="workspaceQuickActions">{[['orders','Przygotuj kosztorys','Zakres i decyzja klienta',openQuote],['inventory','Zamów część','Zakup pod to zlecenie',openPart],['documents','Dokumentacja',`${files.length} zdjęć i plików`,()=>setTab('docs')],['reminders','Zarejestruj czas','Praca zespołu',()=>setTab('time')]].map(([icon,title,sub,action])=><button key={title} onClick={action}><Icon name={icon} size={20}/><b>{title}</b><span>{sub}</span><Icon name="arrow" size={14}/></button>)}</div></section>
  <section className="workspaceCard"><div className="workspaceCardHeading"><span className="sectionEyebrow">CZĘŚCI I ZAKRES</span><Icon name="inventory"/></div><h3>{waiting.length?'Czekamy na części':'Zakres pod kontrolą'}</h3>{waiting.length?waiting.slice(0,3).map(p=><button className="workspacePartLink" key={p.id} onClick={()=>setTab('parts')}><div><b>{p.name}</b><small>{p.status.replaceAll('_',' ')}{p.expected_at?` · ${new Date(p.expected_at).toLocaleDateString('pl-PL')}`:''}</small></div><Icon name="arrow" size={14}/></button>):<p className="workspaceMuted">Brak części oczekujących na zamówienie, dostawę lub obsługę zwrotu.</p>}<div className="workspaceLimit"><span>Pozycje zlecenia</span><button className="studioTextButton" onClick={()=>setTab('money')}>{items.length} pozycji <Icon name="arrow" size={14}/></button></div></section>
  <section className="workspaceCard"><div className="workspaceCardHeading"><span className="sectionEyebrow">OSTATNIE ZDARZENIA</span><button className="studioTextButton" onClick={()=>setTab('timeline')}>Historia<Icon name="arrow" size={14}/></button></div><h3>Co się wydarzyło</h3>{timeline.length?<div className="workspaceRecent">{timeline.slice(0,3).map((t,i)=><div key={`${t.type}-${t.id}-${i}`}><i/><div><b>{t.title}</b><small>{new Date(t.created_at).toLocaleString('pl-PL',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div></div>)}</div>:<p className="workspaceMuted">Kolejne działania pojawią się na osi czasu tego zlecenia.</p>}</section>
 </div>
}
