import React,{useEffect,useRef,useState} from 'react'
import {Icon} from './ui.jsx'
import './parts-workspace.css'

const money=value=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:2}).format(Number(value||0))
const emptyPart={barcode:'',part_no:'',name:'',brand:'',category:'',description:'',image_url:'',lookup_source:'',lookup_url:'',stock:0,min_stock:0,unit_cost:0,sell_price:0,supplier_id:'',location:'',notes:''}

export function PartsWorkspace({api,initialScan,OrdersView}){
 const[tab,setTab]=useState('STOCK'),[rows,setRows]=useState([]),[suppliers,setSuppliers]=useState([]),[query,setQuery]=useState(''),[barcode,setBarcode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(null),[editor,setEditor]=useState(null),[selected,setSelected]=useState(null)
 const lastScan=useRef('')
 const load=()=>Promise.all([api.inventory.list(query),api.suppliers.list()]).then(([parts,sup])=>{setRows(parts);setSuppliers(sup)})
 useEffect(()=>{if(tab==='STOCK')load()},[tab,query])
 useEffect(()=>{const code=initialScan?.barcode;if(code&&initialScan?.nonce!==lastScan.current){lastScan.current=initialScan.nonce;setTab('STOCK');setBarcode(code);lookup(code)}},[initialScan])
 const lookup=async value=>{const code=String(value||barcode).trim();if(!code||busy)return;setBusy(true);setMessage(null);setSelected(null);try{const result=await api.inventory.lookupBarcode(code);if(result.found&&result.source==='local'){setSelected(result.item.id);setMessage({tone:'local',title:'Część jest już w Twoim magazynie',detail:`${result.item.name} · stan ${result.item.stock} · ${result.item.location||'bez lokalizacji'}`});setQuery(result.item.barcode)}else if(result.found){setEditor({...emptyPart,...result.item});setMessage({tone:'online',title:'Znaleziono produkt w internecie',detail:'Sprawdź dane i zapisz część w swoim magazynie.'})}else{setEditor({...emptyPart,barcode:result.barcode});setMessage({tone:'missing',title:'Nie znaleziono gotowego opisu',detail:'Kod jest poprawny. Uzupełnij nazwę ręcznie, aby zapamiętać go na przyszłość.'})}}catch(error){setMessage({tone:'error',title:'Nie udało się wyszukać kodu',detail:error.message||String(error)})}finally{setBusy(false)}}
 const saved=()=>{setEditor(null);setMessage({tone:'local',title:'Część zapisana',detail:'Kolejne zeskanowanie pokaże ją od razu z aktualnym stanem.'});load()}
 const adjust=async(row,delta)=>{await api.inventory.adjust(row.id,delta);setSelected(row.id);load()}
 const total=rows.reduce((sum,row)=>sum+Number(row.stock||0)*Number(row.unit_cost||0),0),low=rows.filter(row=>Number(row.stock)<=Number(row.min_stock)).length
 return <section className="partsWorkspace">
  <div className="partsTabs"><button className={tab==='STOCK'?'active':''} onClick={()=>setTab('STOCK')}><Icon name="inventory"/>Magazyn własny</button><button className={tab==='ORDERS'?'active':''} onClick={()=>setTab('ORDERS')}><Icon name="orders"/>Części do zleceń</button></div>
  {tab==='ORDERS'?<OrdersView/>:<>
   <div className="stockHero"><div><span className="sectionEyebrow">SKANER ZEBRA / EAN · UPC · GTIN</span><h2>Zeskanuj część. <em>Resztę zrobi system.</em></h2><p>Najpierw sprawdzamy Twój magazyn. Nieznany kod wyszukujemy online i pokazujemy dane przed zapisaniem.</p></div><div className="stockScan"><label>Kod produktu<input autoFocus value={barcode} onChange={e=>setBarcode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&lookup()} placeholder="Zeskanuj lub wpisz kod"/></label><button className="primary" disabled={busy||!barcode.trim()} onClick={()=>lookup()}>{busy?'Wyszukiwanie…':'Szukaj kodu'}</button></div></div>
   {message&&<div className={`stockLookupMessage ${message.tone}`}><Icon name={message.tone==='error'?'notifications':'inventory'} size={22}/><div><b>{message.title}</b><span>{message.detail}</span></div><button aria-label="Zamknij komunikat" onClick={()=>setMessage(null)}>×</button></div>}
   <div className="stockMetrics"><div><span>Pozycje w bazie</span><b>{rows.length}</b></div><div><span>Wartość zakupu</span><b>{money(total)}</b></div><div className={low?'warn':''}><span>Niski stan</span><b>{low}</b></div><button onClick={()=>setEditor({...emptyPart})}>+ Dodaj ręcznie</button></div>
   <div className="stockToolbar"><label><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nazwa, marka, numer lub kod…"/></label><span>{rows.length} pozycji</span></div>
   <div className="stockGrid">{rows.map(row=><article key={row.id} className={'stockCard '+(selected===row.id?'selected ':'')+(Number(row.stock)<=Number(row.min_stock)?'low':'')} onClick={()=>setSelected(row.id)}><div className="stockCardHead"><span>{row.brand||row.category||'CZĘŚĆ'}</span>{row.barcode&&<code>{row.barcode}</code>}</div><h3>{row.name}</h3><p>{row.part_no||'Brak numeru katalogowego'} · {row.location||'Brak lokalizacji'}</p><div className="stockCardFoot"><div><small>STAN</small><b>{Number(row.stock).toLocaleString('pl-PL')}</b><em>min. {Number(row.min_stock).toLocaleString('pl-PL')}</em></div><div><small>ZAKUP / SPRZEDAŻ</small><strong>{money(row.unit_cost)} / {money(row.sell_price)}</strong><em>{row.supplier||'dostawca nieustalony'}</em></div></div><div className="stockActions"><button onClick={e=>{e.stopPropagation();adjust(row,-1)}} disabled={Number(row.stock)<=0}>−1</button><button className="primary" onClick={e=>{e.stopPropagation();adjust(row,1)}}>+1 przyjęta</button><button onClick={e=>{e.stopPropagation();setEditor(row)}}>Edytuj</button></div></article>)}{!rows.length&&<div className="stockEmpty"><Icon name="inventory" size={34}/><b>Magazyn jest pusty</b><span>Zeskanuj pierwszy kod kreskowy albo dodaj część ręcznie.</span></div>}</div>
   {editor&&<PartEditor api={api} part={editor} suppliers={suppliers} close={()=>setEditor(null)} saved={saved}/>} 
  </>}
 </section>
}

function PartEditor({api,part,suppliers,close,saved}){
 const[d,setD]=useState({...emptyPart,...part,supplier_id:part.supplier_id||''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const save=async e=>{e.preventDefault();if(!d.name.trim()||busy)return;setBusy(true);setError('');try{if(d.id)await api.inventory.update(d.id,d);else await api.inventory.create(d);saved()}catch(err){setError(err.message||String(err));setBusy(false)}}
 return <div className="stockModalShade" onMouseDown={e=>e.target===e.currentTarget&&!busy&&close()}><div className="stockModal" role="dialog" aria-modal="true" aria-labelledby="stock-editor-title"><header><div><span>{d.lookup_source==='upc.dev'?'WYNIK WYSZUKIWANIA ONLINE':d.id?'KARTA MAGAZYNOWA':'NOWA CZĘŚĆ'}</span><h2 id="stock-editor-title">{d.name||'Uzupełnij dane części'}</h2></div><button type="button" onClick={close} disabled={busy}>×</button></header>{d.lookup_source==='upc.dev'&&<div className="onlineSource"><i/>Dane znalezione w upc.dev. Zweryfikuj zgodność z opakowaniem przed zapisem.</div>}<form onSubmit={save}><div className="formgrid"><label>Kod kreskowy<input value={d.barcode||''} onChange={e=>setD({...d,barcode:e.target.value})}/></label><label>Numer katalogowy<input value={d.part_no||''} onChange={e=>setD({...d,part_no:e.target.value})}/></label><label className="wide">Nazwa części<input autoFocus required value={d.name||''} onChange={e=>setD({...d,name:e.target.value})}/></label><label>Marka / producent<input value={d.brand||''} onChange={e=>setD({...d,brand:e.target.value})}/></label><label>Kategoria<input value={d.category||''} onChange={e=>setD({...d,category:e.target.value})}/></label><label>Stan początkowy<input type="number" step="0.01" value={d.stock} disabled={!!d.id} onChange={e=>setD({...d,stock:e.target.value})}/></label><label>Stan minimalny<input type="number" step="0.01" value={d.min_stock} onChange={e=>setD({...d,min_stock:e.target.value})}/></label><label>Cena zakupu<input type="number" step="0.01" value={d.unit_cost} onChange={e=>setD({...d,unit_cost:e.target.value})}/></label><label>Cena sprzedaży<input type="number" step="0.01" value={d.sell_price} onChange={e=>setD({...d,sell_price:e.target.value})}/></label><label>Dostawca<select value={d.supplier_id||''} onChange={e=>setD({...d,supplier_id:e.target.value})}><option value="">— nieustalony —</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Lokalizacja / półka<input value={d.location||''} onChange={e=>setD({...d,location:e.target.value})} placeholder="np. A-03"/></label><label className="wide">Opis<textarea value={d.description||''} onChange={e=>setD({...d,description:e.target.value})}/></label><label className="wide">Uwagi własne<textarea value={d.notes||''} onChange={e=>setD({...d,notes:e.target.value})}/></label></div>{error&&<div className="stockError">{error}</div>}<footer><button type="button" onClick={close} disabled={busy}>Anuluj</button><button className="primary" type="submit" disabled={busy||!d.name.trim()}>{busy?'Zapisywanie…':'Zapisz w magazynie'}</button></footer></form></div></div>
}
