import React,{useEffect,useState} from 'react'
import {VoiceTextarea} from './voice-entry.jsx'
import {vehicleMakes,vehicleModels} from './vehicle-catalog.js'
import {clearIntakeCustomer,clearIntakeVehicle,filterIntakeCustomers,findActiveIntakeOrder,findScannedIntakeVehicle,intakeCustomerLabel,intakeMileageState,selectIntakeCustomer,selectIntakeVehicle,vehiclesForIntakeCustomer} from './quick-intake-model.js'

const catalogKey=value=>String(value||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleUpperCase('pl-PL').replace(/[^A-Z0-9]/g,'')
const catalogMatch=(items,value)=>items.find(item=>catalogKey(item)===catalogKey(value))||String(value||'').trim()
const canonicalVehicleForm=form=>{const make=catalogMatch(vehicleMakes,form?.make),model=catalogMatch(vehicleModels(make),form?.model);return {...form,make,model}}

export function QuickIntake({changed,initialScan,openOrder,api,Panel,VehicleIntakePanel}){
 const blank={customer_id:'',vehicle_id:'',customer_name:'',customer_phone:'',customer_email:'',company:'',plate:'',vin:'',make:'',model:'',generation:'',year:'',engine:'',power_hp:'',engine_code:'',mileage:'',title:'Diagnostyka / naprawa',complaint:'',diagnosis_limit:350,labor_rate:220,diagnosis_fee:0,priority:'NORMALNY',source:'nieznane',due_at:'',intake_notes:''}
 const initial=()=>{const registration=canonicalVehicleForm(initialScan?.registration?.form||{});return {...blank,...registration,vin:registration.vin||initialScan?.vin||'',intake_notes:registration.intake_notes||(initialScan?.vin?`VIN odczytany skanerem Zebra ${new Date(initialScan.capturedAt||Date.now()).toLocaleString('pl-PL')}`:'')}}
 const[d,setD]=useState(initial),[saving,setSaving]=useState(false),[created,setCreated]=useState(null),[customers,setCustomers]=useState([]),[vehicles,setVehicles]=useState([]),[activeOrders,setActiveOrders]=useState([]),[customerQuery,setCustomerQuery]=useState(''),[loadingRecords,setLoadingRecords]=useState(true),[loadError,setLoadError]=useState(''),[saveError,setSaveError]=useState(''),[allowDuplicate,setAllowDuplicate]=useState(false)
 useEffect(()=>{let alive=true;setLoadingRecords(true);Promise.all([api.customers.list(''),api.vehicles.list(),api.orders.list('ACTIVE')]).then(([customerRows,vehicleRows,orderRows])=>{if(!alive)return;setCustomers(customerRows);setVehicles(vehicleRows);setActiveOrders(orderRows);const scanned=findScannedIntakeVehicle(vehicleRows,initialScan);if(scanned)setD(current=>selectIntakeVehicle(current,scanned,customerRows))}).catch(error=>alive&&setLoadError(error.message||String(error))).finally(()=>alive&&setLoadingRecords(false));return()=>{alive=false}},[])
 const selectedCustomer=customers.find(customer=>String(customer.id)===String(d.customer_id)),selectedVehicle=vehicles.find(vehicle=>String(vehicle.id)===String(d.vehicle_id))
 const customerOptions=filterIntakeCustomers(customers,customerQuery),vehicleOptions=vehiclesForIntakeCustomer(vehicles,d.customer_id)
 const activeVehicleOrder=findActiveIntakeOrder(activeOrders,d.vehicle_id)
 const mileageState=intakeMileageState(selectedVehicle,d.mileage)
 const chooseCustomer=value=>{const customer=customers.find(row=>String(row.id)===String(value));setD(current=>customer?selectIntakeCustomer(current,customer):clearIntakeCustomer(current));setAllowDuplicate(false);setSaveError('')}
 const chooseVehicle=value=>{const vehicle=vehicles.find(row=>String(row.id)===String(value));setD(current=>vehicle?selectIntakeVehicle(current,vehicle,customers):clearIntakeVehicle(current));setAllowDuplicate(false);setSaveError('')}
 const save=async()=>{if(!d.customer_name||!d.title||(!d.plate&&!d.vin))return;setSaving(true);setSaveError('');try{const r=await api.intake.create(d);setCreated(r);changed?.()}catch(error){setSaveError(error.message||String(error))}finally{setSaving(false)}}
 if(created)return <section><div className="successIntake"><b>✓ Zlecenie #{created.order_id} utworzone</b><span>Wybrany klient, pojazd i zlecenie są już połączone w bazie.</span><div><button onClick={()=>{setD(blank);setCreated(null);setCustomerQuery('')}}>Przyjmij kolejne auto</button><button className="primary" onClick={()=>openOrder?.(created.order_id)}>Otwórz Centrum zlecenia →</button></div></div></section>
 const duplicateWarning=activeVehicleOrder&&<div className="intakeDuplicateWarning"><div><span>AKTYWNE ZLECENIE DLA TEGO AUTA</span><b>#{activeVehicleOrder.id} · {activeVehicleOrder.title}</b><small>Status: {activeVehicleOrder.status} · rozpoczęte {new Date(activeVehicleOrder.opened_at).toLocaleDateString('pl-PL')}</small></div><div><button type="button" onClick={()=>openOrder?.(activeVehicleOrder.id)}>Otwórz istniejące zlecenie</button>{allowDuplicate?<button type="button" onClick={()=>setAllowDuplicate(false)}>Anuluj tworzenie drugiego</button>:<button type="button" className="danger" onClick={()=>setAllowDuplicate(true)}>Utwórz osobne zlecenie</button>}</div></div>
 const vehiclePicker=<div className="intakeRecordPicker"><label><small>POJAZDY WYBRANEGO KLIENTA</small><select value={d.vehicle_id||''} onChange={e=>chooseVehicle(e.target.value)} disabled={loadingRecords}><option value="">＋ Dodaj nowy pojazd</option>{vehicleOptions.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.plate||'bez rejestracji'} — {vehicle.make} {vehicle.model}{vehicle.vin?` — VIN ${vehicle.vin}`:''}</option>)}</select></label><div className="intakeRecordState"><i/><span>{d.customer_id?`${vehicleOptions.length} pojazdów w kartotece klienta`:`${vehicles.length} pojazdów w całej bazie`}</span></div>{selectedVehicle&&<div className="intakeSelectedHint"><span>Wybrano zapisany pojazd: <b>{selectedVehicle.plate||selectedVehicle.vin} · {selectedVehicle.make} {selectedVehicle.model}</b></span><button type="button" onClick={()=>chooseVehicle('')}>Wprowadź nowe auto</button></div>}{duplicateWarning}</div>
 return <section className="intakePage">{(initialScan?.vin||initialScan?.registration?.ok)&&<div className="scannerIntakeNotice"><span>✓</span><div><b>{selectedVehicle?'Rozpoznano pojazd zapisany w kartotece':initialScan?.registration?.ok?'Dowód rejestracyjny odczytany automatycznie':'VIN pobrany ze skanera Zebra'}</b><small>{d.plate?`${d.plate} · `:''}{d.vin} · sprawdź zgodność z dokumentem przed zapisaniem</small></div></div>}<div className="intakeIntro"><div><b>PRZYJĘCIE W JEDNYM EKRANIE</b><h2>Klient → auto → zlecenie</h2><p>Wybierz klienta i jego auto z kartoteki. Formularz uzupełni dane automatycznie, a nowe rekordy możesz nadal dodać bez opuszczania przyjęcia.</p></div><div className="intakeBadge">KARTOTEKA LIVE</div></div>
 <div className="intakeSections">
  <Panel title="1. Klient"><div className="intakeRecordPicker"><label><small>SZUKAJ W KARTOTECE</small><input value={customerQuery} onChange={e=>setCustomerQuery(e.target.value)} placeholder="Nazwisko, firma, telefon lub e-mail"/></label><label><small>WYBIERZ KLIENTA</small><select autoFocus value={d.customer_id||''} onChange={e=>chooseCustomer(e.target.value)} disabled={loadingRecords}><option value="">＋ Dodaj nowego klienta</option>{customerOptions.map(customer=><option key={customer.id} value={customer.id}>{intakeCustomerLabel(customer)}</option>)}</select></label><button type="button" onClick={()=>{chooseCustomer('');setCustomerQuery('')}}>Nowy klient</button><div className="intakeRecordState"><i/><span>{loadingRecords?'Wczytywanie kartoteki…':loadError?`Nie udało się pobrać kartoteki: ${loadError}`:`${customers.length} klientów dostępnych · ${customerOptions.length} na liście`}</span></div></div>{selectedCustomer&&<div className="intakeSelectedHint"><span>Wybrano klienta: <b>{selectedCustomer.name}</b> · dane kontaktowe uzupełnione</span><button type="button" onClick={()=>chooseCustomer('')}>Zmień na nowego</button></div>}<div className="formgrid"><label className="wide">Imię / firma<input value={d.customer_name} readOnly={!!d.customer_id} onChange={e=>setD({...d,customer_name:e.target.value})}/></label><label>Telefon<input inputMode="tel" value={d.customer_phone} readOnly={!!d.customer_id} onChange={e=>setD({...d,customer_phone:e.target.value})}/></label><label>E-mail<input inputMode="email" value={d.customer_email} readOnly={!!d.customer_id} onChange={e=>setD({...d,customer_email:e.target.value})}/></label><label className="wide">Firma / nazwa dodatkowa<input value={d.company} readOnly={!!d.customer_id} onChange={e=>setD({...d,company:e.target.value})}/></label></div></Panel>
  <VehicleIntakePanel d={d} setD={setD} picker={vehiclePicker} mileageState={mileageState}/>
  <Panel title="3. Zlecenie"><div className="formgrid"><label className="wide">Tytuł<input value={d.title} onChange={e=>setD({...d,title:e.target.value})}/></label><label className="wide">Objaw słowami klienta<VoiceTextarea className="bigComplaint" value={d.complaint} onChange={value=>setD({...d,complaint:value})} ariaLabel="Objaw słowami klienta" placeholder="Wpisz objaw lub użyj mikrofonu…"/></label><label>Limit diagnostyki<input type="number" value={d.diagnosis_limit} onChange={e=>setD({...d,diagnosis_limit:e.target.value})}/></label><label>Stawka zł/h<input type="number" value={d.labor_rate} onChange={e=>setD({...d,labor_rate:e.target.value})}/></label><label>Priorytet<select value={d.priority} onChange={e=>setD({...d,priority:e.target.value})}><option>NORMALNY</option><option>PILNY</option></select></label><label>Źródło<select value={d.source} onChange={e=>setD({...d,source:e.target.value})}><option>nieznane</option><option>Google</option><option>polecenie</option><option>social</option><option>B2B</option><option>powrót</option></select></label><label className="wide">Notatka przyjęcia<VoiceTextarea value={d.intake_notes} onChange={value=>setD({...d,intake_notes:value})} ariaLabel="Notatka przyjęcia"/></label></div></Panel>
 </div>
 {saveError&&<div className="notice">Nie udało się utworzyć zlecenia: {saveError}</div>}
 <div className="stickyIntake"><span>{d.plate||d.vin||'Pojazd bez identyfikacji'} · {d.customer_name||'Klient'}{selectedVehicle?' · AUTO Z KARTOTEKI':''}</span><button className="primary megaButton" disabled={saving||!d.customer_name||!d.title||(!d.plate&&!d.vin)||(activeVehicleOrder&&!allowDuplicate)||mileageState.invalid} onClick={save}>{mileageState.invalid?'POPRAW PRZEBIEG':activeVehicleOrder&&!allowDuplicate?'NAJPIERW SPRAWDŹ AKTYWNE ZLECENIE':saving?'Zapisywanie…':'UTWÓRZ ZLECENIE'}</button></div>
 </section>
}
