import React,{useEffect,useState} from 'react'

function UpdateSettings({api,Panel}){
 const empty={state:'IDLE',currentVersion:'',availableVersion:'',channel:'STABLE',percent:0,lastChecked:'',releaseNotes:'',message:'Ładowanie informacji o aktualizacjach…',configured:false,canCheck:false,canDownload:false,canInstall:false}
 const[update,setUpdate]=useState(empty),[busy,setBusy]=useState(false),[postponed,setPostponed]=useState(false)
 useEffect(()=>{api.updater.getStatus().then(setUpdate);const cleanup=api.updater.onStatus(next=>{setUpdate(next);setBusy(false);if(next.state==='DOWNLOADED')setPostponed(false)});return cleanup},[])
 const act=async fn=>{setBusy(true);try{const result=await fn();if(result?.state)setUpdate(result)}finally{setBusy(false)}}
 const statusNames={IDLE:'Gotowy',CHECKING:'Sprawdzanie',UPDATE_AVAILABLE:'Dostępna aktualizacja',NO_UPDATE:'Program jest aktualny',DOWNLOADING:'Pobieranie',DOWNLOADED:'Gotowa do instalacji',ERROR:'Problem z aktualizacją'}
 return <Panel title="Aktualizacje programu">
   <div className="updateHero"><div className="updateBrand"><div className="brandMark">A</div><div><small>AUTOLOGIKA OS</small><h2>Wersja {update.currentVersion||'—'}</h2><label className="updateChannel">Kanał: <select value={update.channel} disabled={update.state==='CHECKING'||update.state==='DOWNLOADING'} onChange={async e=>setUpdate(await api.updater.setChannel(e.target.value))}><option value="STABLE">STABILNY</option><option value="BETA">BETA</option></select></label></div></div><div className={'updateState '+String(update.state).toLowerCase()}><i/><span>{statusNames[update.state]||update.state}</span></div></div>
   <div className="updateMeta"><div><span>Aktualna wersja</span><b>{update.currentVersion||'—'}</b></div><div><span>Dostępna wersja</span><b>{update.availableVersion||'—'}</b></div><div><span>Ostatnie sprawdzenie</span><b>{update.lastChecked?new Date(update.lastChecked).toLocaleString('pl-PL'):'jeszcze nie sprawdzano'}</b></div></div>
   <div className="updateMessage"><b>{update.message}</b>{!update.configured&&<span>Właściciela i nazwę repozytorium ustawisz w sekcji <code>build.publish</code> pliku package.json.</span>}</div>
   {update.state==='DOWNLOADING'&&<div className="updateProgress"><div><i style={{width:`${Math.round(update.percent||0)}%`}}/></div><b>{Math.round(update.percent||0)}%</b></div>}
   {update.releaseNotes&&<div className="releaseNotes"><small>INFORMACJE O WERSJI {update.availableVersion}</small><div className="releaseNotesText">{update.releaseNotes}</div></div>}
   <div className="actionrow updateActions"><button className="primary" disabled={busy||!update.canCheck||update.state==='CHECKING'||update.state==='DOWNLOADING'} onClick={()=>act(()=>api.updater.check())}>{update.state==='CHECKING'?'Sprawdzanie…':'Sprawdź aktualizacje'}</button>{update.canDownload&&<button className="primary" disabled={busy} onClick={()=>act(()=>api.updater.download())}>Pobierz aktualizację</button>}{update.canInstall&&!postponed&&<><button className="primary installUpdate" disabled={busy} onClick={()=>act(()=>api.updater.install())}>Zainstaluj i uruchom ponownie</button><button onClick={()=>setPostponed(true)}>Później</button></>}{postponed&&<span className="statusTag">Instalacja odłożona. Pobrana wersja pozostaje gotowa.</span>}</div>
 </Panel>
}

export function Settings({api,Panel,money,fileSize}){
 const[path,setPath]=useState(''),[msg,setMsg]=useState(''),[monthTarget,setMonthTarget]=useState(50000),[targetSaved,setTargetSaved]=useState(''),[srv,setSrv]=useState({running:false,port:8787,pin:null,urls:[],remoteUrls:[]}),[port,setPort]=useState(8787),[busy,setBusy]=useState(false),[remoteCfg,setRemoteCfg]=useState({port:8787,pin:'',autoStart:false}),[cloudCfg,setCloudCfg]=useState({enabled:false,url:'',key:'',keyConfigured:false,keyLength:0,keyHint:'',intervalSeconds:30,deviceName:'',workshopId:''}),[cloudStatus,setCloudStatus]=useState({configured:false,loggedIn:false,pending:0,failed:0,lastSync:'',queue:[],groups:[],lastResult:null}),[cloudBusy,setCloudBusy]=useState(false),[cloudAuth,setCloudAuth]=useState({email:'',password:''}),[cloudTest,setCloudTest]=useState(null),[cloudDeployment,setCloudDeployment]=useState(null)
 const[dbHealth,setDbHealth]=useState(null),[healthBusy,setHealthBusy]=useState(false)
 const[workshop,setWorkshop]=useState({bays:['Stanowisko 1','Stanowisko 2','Diagnostyka','Plac / oczekuje'],openingHour:8,closingHour:18,defaultAppointmentMinutes:60}),[workshopSaved,setWorkshopSaved]=useState('')
 const[archive,setArchive]=useState({path:'',custom:false,total:0,available:0,missing:0,incomplete:0,corrupt:0,healthy:0}),[archiveBusy,setArchiveBusy]=useState(false)
  const reportError=(action,error)=>setMsg(`${action}: ${error?.message||error||'nieznany błąd'}`)
 const load=async()=>{try{setPath(await api.system.dbPath())}catch{};try{setMonthTarget(Number(await api.settings.monthlyTarget())||50000)}catch{};try{setWorkshop(await api.settings.workshopLayout())}catch{};try{const [location,status]=await Promise.all([api.settings.approvalArchive(),api.approvals.archiveStatus()]);setArchive({...status,...location})}catch{};try{const c=await api.mobileServer.config();setRemoteCfg(c);setPort(c.port||8787)}catch{};try{const r=await api.mobileServer.status();setSrv(r);if(r.running)setPort(r.port||8787)}catch{};try{setCloudCfg(await api.cloudSync.config());setCloudStatus(await api.cloudSync.status())}catch{};try{setDbHealth(await api.system.health())}catch{}}
 useEffect(()=>{load();const timer=setInterval(()=>api.cloudSync.status().then(setCloudStatus).catch(()=>{}),5000);return()=>clearInterval(timer)},[])
  const start=async()=>{setBusy(true);try{const r=await api.mobileServer.start(Number(port)||8787);setSrv(r)}catch(e){reportError('Nie udało się uruchomić serwera',e)}finally{setBusy(false)}}
  const stop=async()=>{setBusy(true);try{setSrv(await api.mobileServer.stop())}catch(e){reportError('Nie udało się zatrzymać serwera',e)}finally{setBusy(false)}}
  const saveRemote=async()=>{try{const c=await api.mobileServer.saveConfig({...remoteCfg,port:Number(port)||8787});setRemoteCfg(c);setMsg('Ustawienia zdalnego dostępu zapisane.')}catch(e){reportError('Nie udało się zapisać dostępu zdalnego',e)}}
  const saveCloud=async()=>{setCloudBusy(true);setCloudTest(null);try{const c=await api.cloudSync.saveConfig(cloudCfg);setCloudCfg(c);setCloudStatus(await api.cloudSync.status());setMsg('Konfiguracja synchronizacji zapisana.')}catch(e){reportError('Nie udało się zapisać konfiguracji Cloud',e)}finally{setCloudBusy(false)}}
 const testCloud=async()=>{setCloudBusy(true);setCloudTest(null);try{const r=await api.cloudSync.test();setCloudTest({ok:true,text:`Połączenie OK · HTTP ${r.status} · ${r.ms} ms · klucz ${r.keyKind} (${r.keyLength} znaków)`});setMsg('Supabase odpowiada prawidłowo. Możesz utworzyć konto lub się zalogować.')}catch(e){setCloudTest({ok:false,text:e.message});setMsg('Test połączenia nieudany.')}finally{setCloudBusy(false)}}
 const checkCloudDeployment=async()=>{setCloudBusy(true);try{const result=await api.cloudSync.approvalDeployment();setCloudDeployment(result);setMsg(result.message)}catch(e){setCloudDeployment({ok:false,approvalTable:false,approvalFunction:false,message:e.message||String(e)});setMsg(`Kontrola modułów Cloud nieudana: ${e.message||e}`)}finally{setCloudBusy(false)}}
  const syncNow=async()=>{setCloudBusy(true);try{const r=await api.cloudSync.now();setCloudStatus(await api.cloudSync.status());setMsg(r.ok?`Synchronizacja: wysłano ${r.pushed}, pobrano ${r.pulled}, konflikty rozstrzygnięte na korzyść nowszych danych ${r.conflicts||0}, oczekuje ${r.pending}.`:`Synchronizacja nieudana: ${r.error||'nieznany błąd'}`)}catch(e){reportError('Synchronizacja nie powiodła się',e)}finally{setCloudBusy(false)}}
 const retryCloud=async id=>{setCloudBusy(true);try{const r=await api.cloudSync.retry(id);setCloudStatus(await api.cloudSync.status());setMsg(r.ok?'Zmiana została wysłana.':`Ponowienie nieudane: ${r.error||'nieznany błąd'}`)}catch(e){setMsg(`Ponowienie nieudane: ${e.message||e}`)}finally{setCloudBusy(false)}}
 const enableAutoCloud=async()=>{setCloudBusy(true);try{const c=await api.cloudSync.saveConfig({...cloudCfg,enabled:true});setCloudCfg(c);const r=await api.cloudSync.now();setCloudStatus(await api.cloudSync.status());setMsg(r.ok?'Automatyczna synchronizacja jest włączona, a kolejka została wysłana.':`Automatyczna synchronizacja jest włączona. Wysyłanie nieudane: ${r.error||'nieznany błąd'}`)}catch(e){setMsg(`Nie udało się włączyć synchronizacji: ${e.message||e}`)}finally{setCloudBusy(false)}}
 const copyCloudSchema=async()=>{try{const r=await api.system.copyCloudSchema();setMsg(`Skopiowano pełną migrację Cloud do schowka (${r.characters} znaków). Wklej ją w SQL Editorze Supabase i wybierz Run.`)}catch(e){setMsg(`Nie udało się skopiować migracji: ${e.message||e}`)}}
 const syncNames={app_settings:'Ustawienia',customers:'Klienci',suppliers:'Dostawcy',inventory_parts:'Magazyn',vehicles:'Pojazdy',orders:'Zlecenia',diagnostics:'Diagnostyka',order_notes:'Notatki',job_part_orders:'Zamówienia części',payments:'Płatności',appointments:'Terminarz',order_items:'Pozycje zleceń',work_logs:'Czas pracy',communications:'Kontakt',approvals:'Akceptacje',order_events:'Historia',sales_refs:'Dokumenty sprzedaży',service_reminders_v2:'Przypomnienia',attachments:'Załączniki',signatures:'Podpisy',work_procedure_runs:'Procedury',technical_data_entries:'Dane techniczne',vehicle_findings:'Stan pojazdu',order_qc:'Kontrola jakości',work_templates:'Szablony prac',technical_manual_pages:'Strony dokumentacji',technical_manual_hotspots:'Punkty dokumentacji',technical_manual_steps:'Kroki dokumentacji'}
 const checkDatabase=async()=>{setHealthBusy(true);try{setDbHealth(await api.system.health());setMsg('Kontrola bazy została zakończona.')}catch(e){setMsg(`Kontrola bazy nieudana: ${e.message||e}`)}finally{setHealthBusy(false)}}
  const saveTarget=async()=>{try{const v=await api.settings.setMonthlyTarget(monthTarget);setMonthTarget(v);setTargetSaved(`Cel miesięczny zapisany: ${money(v)}`);setTimeout(()=>setTargetSaved(''),2500)}catch(e){reportError('Nie udało się zapisać celu miesięcznego',e)}}
 const resizeBays=value=>{const count=Math.max(1,Math.min(20,Math.round(Number(value)||1)));setWorkshop(current=>({...current,bays:Array.from({length:count},(_,index)=>current.bays[index]||`Stanowisko ${index+1}`)}))}
 const renameBay=(index,value)=>setWorkshop(current=>({...current,bays:current.bays.map((name,i)=>i===index?value:name)}))
  const saveWorkshop=async()=>{try{const value=await api.settings.setWorkshopLayout(workshop);setWorkshop(value);setWorkshopSaved('Konfiguracja warsztatu zapisana i gotowa do synchronizacji.');setTimeout(()=>setWorkshopSaved(''),3000)}catch(e){reportError('Nie udało się zapisać organizacji warsztatu',e)}}
 const openArchive=async()=>{try{await api.settings.openApprovalArchive()}catch(e){setMsg(e.message||String(e))}}
 const chooseArchive=async()=>{const result=await api.settings.chooseApprovalArchive();if(!result.canceled){setArchive(current=>({...current,path:result.path,custom:true}));setMsg('Nowe dokumenty akceptacji będą zapisywane w wybranym folderze.')}}
 const syncArchive=async()=>{setArchiveBusy(true);try{const result=await api.approvals.syncArchive(),status=await api.approvals.archiveStatus();setArchive(current=>({...current,...status}));setMsg(result.errors?.length?`Uzupełniono ${result.completed||0} pakietów; błędy: ${result.errors.length}.`:`Archiwum uzupełnione. Kompletne pakiety: ${result.completed||0}, pobrane PDF: ${result.downloaded||0}.`)}catch(e){setMsg(e.message||String(e))}finally{setArchiveBusy(false)}}
 const syncLimited=!!(cloudStatus.lastResult?.ok&&cloudStatus.lastResult?.approvalModuleUnavailable)
 const syncTone=cloudStatus.failed?'hasErrors':cloudStatus.pending?'hasPending':syncLimited?'limited':'healthy'
 const cloudProjectRef=String(cloudCfg.url||'').match(/^https:\/\/([a-z0-9-]+)\.supabase\.co\/?$/i)?.[1]||''
 const cloudSqlEditor=cloudProjectRef?`https://supabase.com/dashboard/project/${cloudProjectRef}/sql/new`:''
 return <section>
   <UpdateSettings api={api} Panel={Panel}/>
    {msg&&<div className="notice settingsFeedback" role="status"><span>{msg}</span><button type="button" aria-label="Zamknij komunikat ustawień" onClick={()=>setMsg('')}>×</button></div>}
   <Panel title="Dokumenty i archiwum akceptacji">
     <div className="notice"><b>Lokalny pakiet dowodowy</b><span>Po akceptacji PDF, podpis klienta i manifest z sumami SHA-256 są automatycznie pobierane z prywatnego magazynu Supabase. Folder pojazdu pozostaje ten sam także po zmianie numeru rejestracyjnego.</span></div>
     <div className="archivePath"><small>FOLDER ARCHIWUM</small><code>{archive.path||'Ładowanie…'}</code></div>
     <div className="actionrow"><button onClick={openArchive}>Otwórz folder</button><button onClick={chooseArchive}>Zmień folder</button><button className="primary" disabled={archiveBusy||!cloudStatus.loggedIn} onClick={syncArchive}>Uzupełnij pakiety dowodowe</button><span className="statusTag">W chmurze: {archive.available||0} · kompletne: {archive.healthy||0} · niepełne: {archive.incomplete||0} · brak: {archive.missing||0} · uszkodzone: {archive.corrupt||0}</span></div>
   </Panel>
   <Panel title="Organizacja warsztatu">
     <div className="notice"><b>Stanowiska i terminarz</b><span>Ustaw liczbę oraz nazwy stanowisk, godziny pracy i standardową długość nowej wizyty. Terminarz zastosuje zmiany automatycznie.</span></div>
     <div className="formgrid workshopSettingsGrid"><label>Liczba stanowisk<input type="number" min="1" max="20" value={workshop.bays.length} onChange={e=>resizeBays(e.target.value)}/></label><label>Domyślna długość wizyty [min]<input type="number" min="15" max="480" step="15" value={workshop.defaultAppointmentMinutes} onChange={e=>setWorkshop({...workshop,defaultAppointmentMinutes:Number(e.target.value)||60})}/></label><label>Otwarcie<input type="number" min="0" max="22" value={workshop.openingHour} onChange={e=>setWorkshop({...workshop,openingHour:Number(e.target.value)})}/></label><label>Zamknięcie<input type="number" min="1" max="24" value={workshop.closingHour} onChange={e=>setWorkshop({...workshop,closingHour:Number(e.target.value)})}/></label></div>
     <div className="workshopBaySettings">{workshop.bays.map((name,index)=><label key={index}><span>{String(index+1).padStart(2,'0')}</span><input aria-label={`Nazwa stanowiska ${index+1}`} value={name} onChange={e=>renameBay(index,e.target.value)} placeholder={`Stanowisko ${index+1}`}/></label>)}</div>
     <div className="actionrow"><button className="primary" onClick={saveWorkshop}>Zapisz organizację warsztatu</button>{workshopSaved&&<span className="statusTag">✓ {workshopSaved}</span>}</div>
   </Panel>
   <Panel title="Cele warsztatu">
     <div className="notice"><b>Cel miesięczny</b><span>Ta wartość steruje paskiem realizacji i wymaganym tempem dziennym w Centrum Dowodzenia. Ustawienie synchronizuje się przez Autologika Cloud z Androidem.</span></div>
     <div className="formgrid targetSettings"><label>Cel przychodu / miesiąc [zł]<input type="number" min="1000" max="10000000" step="1000" value={monthTarget} onChange={e=>setMonthTarget(Math.max(0,Number(e.target.value)||0))}/></label><div className="targetPresets">{[30000,50000,75000,100000,150000].map(x=><button key={x} className={Number(monthTarget)===x?'primary':''} onClick={()=>setMonthTarget(x)}>{x/1000}k</button>)}</div></div>
     <div className="actionrow"><button className="primary" onClick={saveTarget}>Zapisz cel miesięczny</button>{targetSaved&&<span className="statusTag">✓ {targetSaved}</span>}</div>
   </Panel>
   <Panel title="Chmura i synchronizacja PC ↔ Android">
     <div className="notice"><b>Architektura 0.20.1:</b> PC i tablet mają własną bazę offline. Zmiany trafiają do wspólnej bazy chmurowej rekord po rekordzie, więc komputer w warsztacie może być wyłączony, gdy pracujesz w domu.</div>
     <div className="formgrid">
       <label className="wide">Supabase URL<input placeholder="https://twoj-projekt.supabase.co" value={cloudCfg.url||''} onChange={e=>setCloudCfg({...cloudCfg,url:e.target.value})}/></label>
       <label className="wide">Publishable key<input type="password" autoComplete="off" spellCheck={false} placeholder={cloudCfg.keyConfigured?"Klucz jest zapisany — wklej tutaj tylko jeśli chcesz go zastąpić":"wklej cały sb_publishable_..."} value={cloudCfg.key||''} onChange={e=>setCloudCfg({...cloudCfg,key:e.target.value})}/>{cloudCfg.keyConfigured&&<small className="cloudKeyInfo">Zapisany klucz: <code>{cloudCfg.keyHint}</code> · {cloudCfg.keyLength} znaków. Pole pozostaje puste celowo — aplikacja nie pokazuje pełnego klucza.</small>}</label>
       <label>Nazwa urządzenia<input value={cloudCfg.deviceName||''} onChange={e=>setCloudCfg({...cloudCfg,deviceName:e.target.value})}/></label><label>ID warsztatu z konta Cloud<input readOnly value={cloudStatus.loggedIn?cloudStatus.workshopId||'':'Po zalogowaniu'} /></label>
       <label>Synchronizacja automatyczna<select value={cloudCfg.enabled?'TAK':'NIE'} onChange={e=>setCloudCfg({...cloudCfg,enabled:e.target.value==='TAK'})}><option>TAK</option><option>NIE</option></select></label>
       <label>Interwał (sek.)<input type="number" min="10" max="3600" value={cloudCfg.intervalSeconds||30} onChange={e=>setCloudCfg({...cloudCfg,intervalSeconds:Number(e.target.value)||30})}/></label>
     </div>
      <div className="actionrow"><button className="primary" disabled={cloudBusy} onClick={saveCloud}>Zapisz konfigurację chmury</button><button disabled={cloudBusy||!cloudStatus.configured} onClick={testCloud}>Test połączenia</button><button disabled={cloudBusy||!cloudStatus.configured||!cloudStatus.loggedIn} onClick={checkCloudDeployment}>Sprawdź moduły akceptacji</button><button disabled={cloudBusy||!cloudStatus.configured||!cloudStatus.loggedIn} onClick={syncNow}>↻ Synchronizuj teraz</button></div>{cloudTest&&<div className={cloudTest.ok?'notice cloudTestOk':'warnbox'}><b>{cloudTest.ok?'✓ Supabase działa':'✕ Problem z połączeniem'}</b><span>{cloudTest.text}</span></div>}{cloudDeployment&&<div className={'cloudDeployment '+(cloudDeployment.ok?'ready':'incomplete')}><div><span className={cloudDeployment.approvalTable?'ready':''}><i>{cloudDeployment.approvalTable?'✓':'!'}</i><b>Tabela akceptacji</b><small>{cloudDeployment.approvalTable?'gotowa':'brak migracji SQL'}</small></span><span className={cloudDeployment.approvalFunction?'ready':''}><i>{cloudDeployment.approvalFunction?'✓':'!'}</i><b>Strona klienta</b><small>{cloudDeployment.approvalFunction?'Edge Function działa':cloudDeployment.functionStatus===401?'wymaga verify_jwt=false':'funkcja niewdrożona'}</small></span></div><p>{cloudDeployment.message}</p></div>}
      <div className="formgrid"><label>E-mail<input value={cloudAuth.email} onChange={e=>setCloudAuth({...cloudAuth,email:e.target.value})}/></label><label>Hasło<input type="password" value={cloudAuth.password} onChange={e=>setCloudAuth({...cloudAuth,password:e.target.value})}/></label></div><div className="actionrow">{!cloudStatus.loggedIn?<><button className="primary" onClick={async()=>{try{await api.cloudSync.login(cloudAuth.email,cloudAuth.password);setCloudStatus(await api.cloudSync.status());setMsg('Zalogowano do Autologika Cloud.')}catch(e){reportError('Logowanie nie powiodło się',e)}}}>Zaloguj</button><button onClick={async()=>{try{const r=await api.cloudSync.signup(cloudAuth.email,cloudAuth.password);setMsg(r.needsConfirmation?'Konto utworzone — potwierdź e-mail i zaloguj się.':'Konto utworzone.');setCloudStatus(await api.cloudSync.status())}catch(e){reportError('Nie udało się utworzyć konta',e)}}}>Utwórz konto</button></>:<><span className="statusTag">{cloudStatus.email}</span><button className="danger" onClick={async()=>{await api.cloudSync.logout();setCloudStatus(await api.cloudSync.status())}}>Wyloguj</button></>}</div>
     <div className="mobileFeatureGrid"><div><b>{cloudStatus.configured?'✓':'○'} Chmura</b><span>{cloudStatus.configured?(cloudStatus.loggedIn?'skonfigurowana i zalogowana':'skonfigurowana — zaloguj się'):'wymaga URL i anon key'}</span></div><div><b>⇅ {cloudStatus.pending||0}</b><span>lokalnych zmian oczekuje na wysłanie</span></div><div><b>◷ Ostatnia synchronizacja</b><span>{cloudStatus.lastSync?new Date(cloudStatus.lastSync).toLocaleString('pl-PL'):'jeszcze nie wykonano'}</span></div><div><b>Offline-first</b><span>brak internetu nie blokuje pracy na lokalnej bazie</span></div></div>
      <div className={'syncHealth '+syncTone}><div className="syncHealthHead"><div><small>STAN WYMIANY DANYCH</small><b>{cloudStatus.failed?`${cloudStatus.failed} zmian wymaga uwagi`:cloudStatus.pending?`${cloudStatus.pending} zmian czeka na wysłanie`:syncLimited?'Dane zsynchronizowane · akceptacje online ograniczone':'Wszystkie lokalne zmiany wysłane'}</b><span>{cloudStatus.lastResult?.at?`${cloudStatus.lastResult.ok?'Ostatnia próba udana':'Ostatnia próba nieudana'} · ${new Date(cloudStatus.lastResult.at).toLocaleString('pl-PL')}`:'Brak zapisanej próby synchronizacji'}</span></div><i>{cloudStatus.running?'SYNCHRONIZACJA…':cloudStatus.failed?'BŁĄD':cloudStatus.pending?'OCZEKUJE':syncLimited?'OGRANICZONE':'GOTOWE'}</i></div>{!cloudCfg.enabled&&cloudStatus.pending>0&&<div className="syncPausedNotice"><div><b>Automatyczne wysyłanie jest wyłączone</b><span>Zmiany pozostaną tylko na tym urządzeniu, dopóki nie uruchomisz synchronizacji ręcznie.</span></div><button className="primary" disabled={cloudBusy} onClick={enableAutoCloud}>Włącz i wyślij teraz</button></div>}{syncLimited&&<div className="syncModuleNotice"><b>Dane warsztatowe synchronizują się prawidłowo</b><span>Chmura nie ma jeszcze modułu linków akceptacji klienta. Zlecenia, pojazdy, części i terminarz nadal wymieniają dane między urządzeniami.</span><div className="syncModuleActions"><button onClick={copyCloudSchema}>Kopiuj pełną migrację SQL</button><button onClick={checkCloudDeployment}>Sprawdź po wdrożeniu</button>{cloudSqlEditor&&<button className="primary" onClick={()=>api.system.openExternal(cloudSqlEditor)}>Otwórz SQL Editor Supabase ↗</button>}</div></div>}{cloudStatus.lastResult&&!cloudStatus.lastResult.ok&&<div className="syncLastError"><b>Ostatni błąd</b><span>{cloudStatus.lastResult.error}</span></div>}{cloudStatus.groups?.length>0&&<div className="syncGroups">{cloudStatus.groups.map(group=><span key={group.entity_type} className={group.failed?'failed':''}><b>{syncNames[group.entity_type]||group.entity_type}</b>{group.total}{group.failed?` · błędy ${group.failed}`:''}</span>)}</div>}{cloudStatus.queue?.length>0&&<div className="syncQueue"><div className="syncQueueHeader"><b>Ostatnie zmiany w kolejce</b><span>{cloudStatus.oldestPending?`najstarsza: ${new Date(cloudStatus.oldestPending).toLocaleString('pl-PL')}`:''}</span></div>{cloudStatus.queue.map(row=><div className={row.last_error?'failed':''} key={row.id}><span><b>{syncNames[row.entity_type]||row.entity_type}</b><small>{row.operation==='DELETE'?'usunięcie':'aktualizacja'} · rekord #{row.row_id||'—'} · prób {row.attempts||0}</small>{row.last_error&&<em>{row.last_error}</em>}</span>{row.last_error&&<button disabled={cloudBusy} onClick={()=>retryCloud(row.id)}>Ponów</button>}</div>)}</div>}</div>
     <p className="muted">Plik <code>cloud_schema_supabase.sql</code> w paczce tworzy tabelę synchronizacji. Wersja 0.20.1 synchronizuje zdjęcia/załączniki przez prywatny Supabase Storage, podpisy z Androida oraz propaguje usunięcia plików. Android 0.5 używa tego samego konta i nadal działa offline.</p>
   </Panel>
   <Panel title="Serwer mobilny LAN — tryb zgodności">
     <div className={'serverState '+(srv.running?'on':'off')}><div><i/><span>{srv.running?'SERWER WŁĄCZONY':'SERWER WYŁĄCZONY'}</span></div><b>{srv.running?'Tablet może pracować bezpośrednio na bazie danych komputera.':'Serwer nie przyjmuje połączeń.'}</b></div>
     <div className="serverControls"><label>Port<input type="number" min="1024" max="65535" disabled={srv.running} value={port} onChange={e=>setPort(e.target.value)}/></label>{!srv.running?<button className="primary serverButton" disabled={busy} onClick={start}>▶ WŁĄCZ SERWER</button>:<button className="danger serverButton" disabled={busy} onClick={stop}>■ WYŁĄCZ SERWER</button>}</div>
     {srv.running&&<div className="serverAccess"><div className="pinCard"><span>PIN dostępu</span><b>{srv.pin}</b></div><div className="urlCards">{srv.urls?.length?srv.urls.map(u=><div className="urlCard" key={u}><code>{u}</code><button onClick={()=>api.system.copyText(u)}>Kopiuj</button></div>):<div className="warnbox">Nie wykryto adresu IPv4.</div>}</div></div>}
   </Panel>
   <Panel title="Zdalny dostęp VPN — tryb zgodności">
     <div className="notice"><b>Najbezpieczniejszy układ:</b> komputer w warsztacie pozostaje serwerem danych, a tablet łączy się z nim przez prywatny VPN mesh (np. Tailscale). Nie przekierowuj portu 8787 bezpośrednio w routerze.</div>
     <div className="formgrid">
       <label>Stały PIN zdalny<input disabled={srv.running} inputMode="numeric" placeholder="np. 8 cyfr" value={remoteCfg.pin||''} onChange={e=>setRemoteCfg({...remoteCfg,pin:e.target.value.replace(/\D/g,'').slice(0,12)})}/></label>
       <label>Automatycznie uruchamiaj serwer<select disabled={srv.running} value={remoteCfg.autoStart?'TAK':'NIE'} onChange={e=>setRemoteCfg({...remoteCfg,autoStart:e.target.value==='TAK'})}><option>TAK</option><option>NIE</option></select></label>
     </div>
     {!srv.running&&<button className="primary" onClick={saveRemote}>Zapisz ustawienia zdalne</button>}
     {srv.running&&srv.remoteUrls?.length>0&&<div className="serverAccess"><p><b>Wykryto prywatny adres zdalny:</b></p>{srv.remoteUrls.map(u=><div className="urlCard" key={u}><code>{u}</code><button onClick={()=>api.system.copyText(u)}>Kopiuj adres zdalny</button></div>)}</div>}
     {srv.running&&(!srv.remoteUrls||srv.remoteUrls.length===0)&&<div className="warnbox">Nie wykryto jeszcze adresu Tailscale (100.64.0.0/10). Zainstaluj i zaloguj Tailscale na PC oraz tablecie, a potem odśwież ten ekran.</div>}
     <p className="muted">Żeby działało z domu: PC musi być włączony, Autologika OS musi działać, serwer mobilny musi być uruchomiony i Windows nie może usypiać komputera. Połączenie przez Tailscale jest szyfrowane pomiędzy urządzeniami.</p>
   </Panel>
   <Panel title="Autologika Cloud 0.20.1 — PC + Android"><div className="mobileFeatureGrid"><div><b>⌂ Praca z domu</b><span>Android pracuje na własnej bazie lokalnej nawet przy wyłączonym PC</span></div><div><b>⇄ Synchronizacja rekordów</b><span>po uruchomieniu PC obie aplikacje wymieniają tylko zmienione rekordy</span></div><div><b>🧰 Pełniejsze zlecenie</b><span>sync obejmuje części, czas pracy, płatności, komunikację i historię</span></div><div><b>↻ Offline-first</b><span>brak internetu nie blokuje pracy na żadnym urządzeniu</span></div></div></Panel>
   <Panel title="Dane i kondycja bazy"><div className={'databaseHealth '+String(dbHealth?.status||'checking').toLowerCase()}><div><small>KONTROLA SQLITE</small><b>{dbHealth?.status==='OK'?'Baza jest zdrowa':dbHealth?.status==='WARN'?'Baza działa, ale wymaga uwagi':dbHealth?.status==='ERROR'?'Wykryto problem z bazą':'Sprawdzanie kondycji…'}</b><span>{dbHealth?.checkedAt?`Sprawdzono ${new Date(dbHealth.checkedAt).toLocaleString('pl-PL')}`:'Oczekiwanie na wynik'}</span></div><i>{dbHealth?.status||'…'}</i></div>{dbHealth&&<><div className="databaseMetrics"><div><span>Integralność</span><b>{dbHealth.integrityOk?'✓ poprawna':'✕ błąd'}</b></div><div><span>Schemat</span><b>{dbHealth.schemaOk?`✓ wersja ${dbHealth.schemaVersion}`:`✕ ${dbHealth.schemaVersion}/${dbHealth.expectedSchemaVersion}`}</b></div><div><span>Klucze obce</span><b>{dbHealth.foreignKeyErrors?`${dbHealth.foreignKeyErrors} błędów`:'✓ poprawne'}</b></div><div><span>Rozmiar danych</span><b>{fileSize(dbHealth.databaseBytes)}</b></div><div><span>Plik WAL</span><b>{fileSize(dbHealth.walBytes)}</b></div><div><span>Kopie zapasowe</span><b>{dbHealth.backupCount}</b></div></div>{dbHealth.missingColumns?.length>0&&<div className="warnbox"><b>Brakujące pola schematu</b><span>{dbHealth.missingColumns.join(', ')}</span></div>}<div className="databaseRecords">{Object.entries(dbHealth.counts||{}).map(([name,count])=><span key={name}><b>{count??'—'}</b>{syncNames[name]||name}</span>)}</div><div className="backupTimeline"><div><b>Ostatnie kopie</b><span>{dbHealth.lastBackup?`${dbHealth.lastBackup.name} · ${fileSize(dbHealth.lastBackup.bytes)} · ${dbHealth.lastBackupAgeHours} h temu`:'Brak kopii zapasowej'}</span></div>{dbHealth.backups?.slice(0,4).map(file=><small key={file.name}>{file.name}<b>{fileSize(file.bytes)}</b></small>)}</div></>}<p>Baza danych:</p><code className="pathCode">{path}</code><p className="muted">Aplikacja tworzy jedną spójną kopię SQLite dziennie i zachowuje 14 ostatnich kopii automatycznych. Kontrola obejmuje integralność, relacje między rekordami i pola wymagane przez najważniejsze moduły.</p><div className="actionrow"><button className="primary" disabled={healthBusy} onClick={checkDatabase}>Sprawdź bazę</button><button disabled={healthBusy} onClick={async()=>{const r=await api.system.backup();if(!r.canceled){setMsg(`Backup zapisany: ${r.filePath}`);await checkDatabase()}}}>Utwórz backup ręczny</button><button disabled={healthBusy} onClick={async()=>{const r=await api.system.autoBackup();setMsg(`Kopia automatyczna: ${r.file}`);await checkDatabase()}}>Wykonaj backup dzienny</button><button onClick={()=>api.system.openBackupFolder()}>Otwórz folder kopii</button></div></Panel>
 </section>
}
