import React,{useEffect,useMemo,useState} from 'react'

const api=window.autologika
const LEVELS=['OEM_VERIFIED','VERIFIED','CORROBORATED_SECONDARY','WORKSHOP','UNVERIFIED']
const levelText={OEM_VERIFIED:'OEM VERIFIED',VERIFIED:'ZWERYFIKOWANE',CORROBORATED_SECONDARY:'ŹRÓDŁO WTÓRNE',WORKSHOP:'WŁASNE / WARSZTAT',UNVERIFIED:'NIEZWERYFIKOWANE'}
const kindText={TORQUE:'MOMENT',ANGLE:'KĄT',TOOL:'NARZĘDZIE',NOTE:'UWAGA',SEQUENCE:'KOLEJNOŚĆ',FLUID:'PŁYN',MEASUREMENT:'POMIAR',PART:'CZĘŚĆ'}
const emptyMeta={title:'',section:'Silnik',subsection:'',make:'',model:'',generation:'',year_from:'',year_to:'',engine:'',engine_code:'',gearbox_code:'',work_tags:'',source_type:'CAPTURED',source_name:'',source_ref:'',source_date:'',verification_level:'WORKSHOP',notes:'',sort_order:0}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v))

function GenericEngineDiagram(){
 return <svg viewBox="0 0 1200 760" role="img" aria-label="Schemat poglądowy zespołu silnika">
  <defs><linearGradient id="metal" x1="0" x2="1"><stop offset="0" stopColor="#b9c4cb"/><stop offset=".5" stopColor="#f1f4f5"/><stop offset="1" stopColor="#8b989f"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="10" stdDeviation="12" floodOpacity=".35"/></filter></defs>
  <g filter="url(#shadow)" stroke="#29343b" strokeWidth="8" fill="url(#metal)"><path d="M220 205 Q245 130 350 120 L865 120 Q960 132 980 215 L1010 480 Q1018 545 950 568 L255 568 Q190 545 200 472Z"/><path d="M290 200 L890 200 L918 330 L270 330Z" fill="#dce3e7"/><circle cx="370" cy="270" r="58"/><circle cx="600" cy="270" r="58"/><circle cx="830" cy="270" r="58"/><circle cx="370" cy="270" r="22" fill="#68757d"/><circle cx="600" cy="270" r="22" fill="#68757d"/><circle cx="830" cy="270" r="22" fill="#68757d"/><path d="M290 365 H910 V510 H290Z" fill="#c8d1d6"/><circle cx="360" cy="440" r="48" fill="#f4f6f7"/><circle cx="520" cy="440" r="48" fill="#f4f6f7"/><circle cx="680" cy="440" r="48" fill="#f4f6f7"/><circle cx="840" cy="440" r="48" fill="#f4f6f7"/><path d="M270 590 H930 L880 650 H330Z" fill="#7c8b94"/></g>
  <g fill="#58666f">{[[270,175],[930,175],[245,285],[955,285],[245,440],[955,440],[310,540],[890,540]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r="16"/>)}</g>
 </svg>
}
function VerificationBadge({level}){return <span className={'manualVerify '+String(level||'WORKSHOP').toLowerCase()}>{levelText[level]||level||'WARSZTAT'}</span>}

function ManualTree({rows,selectedId,onSelect}){
 const groups=useMemo(()=>{const root={};for(const r of rows){const make=r.make||'OGÓLNE',model=r.model||'Wszystkie modele',engine=r.engine_code||r.engine||'Wszystkie silniki',section=r.section||'Ogólne';root[make]??={};root[make][model]??={};root[make][model][engine]??={};root[make][model][engine][section]??=[];root[make][model][engine][section].push(r)}return root},[rows])
 const[open,setOpen]=useState({});const toggle=k=>setOpen(x=>({...x,[k]:x[k]===false?true:false}))
 const visible=k=>open[k]!==false
 return <aside className="manualTree manualTreeV2"><div className="manualTreeHead"><b>Biblioteka pojazdów</b><span>{rows.length}</span></div>{Object.entries(groups).map(([make,models])=>{const mk='m:'+make;return <div className="manualBranch" key={mk}><button className="manualBranchHead" onClick={()=>toggle(mk)}><span>{visible(mk)?'▾':'▸'}</span><b>{make}</b><em>{Object.values(models).flatMap(x=>Object.values(x)).flatMap(x=>Object.values(x)).flat().length}</em></button>{visible(mk)&&Object.entries(models).map(([model,engines])=>{const mo=mk+'/'+model;return <div className="manualBranchDepth1" key={mo}><button className="manualBranchHead small" onClick={()=>toggle(mo)}><span>{visible(mo)?'▾':'▸'}</span><b>{model}</b></button>{visible(mo)&&Object.entries(engines).map(([engine,sections])=>{const en=mo+'/'+engine;return <div className="manualBranchDepth2" key={en}><button className="manualBranchHead tiny" onClick={()=>toggle(en)}><span>{visible(en)?'▾':'▸'}</span><b>{engine}</b></button>{visible(en)&&Object.entries(sections).map(([section,pages])=><div className="manualSectionGroup" key={en+'/'+section}><small>{section}</small>{pages.map(r=><button key={r.id} className={'manualLeaf '+(selectedId===r.id?'active':'')} onClick={()=>onSelect(r.id)}><span>{r.page_type==='PDF'?'PDF':r.page_type==='DIAGRAM'?'◫':'IMG'}</span><div><b>{r.title}</b><em>{r.hotspot_count||0} pkt · {r.step_count||0} kroków</em></div></button>)}</div>)}</div>})}</div>})}</div>})}{!rows.length&&<div className="manualEmpty">Brak stron dla bieżących filtrów.</div>}</aside>
}

export default function TechnicalManual({context=null,onClearContext}){
 const[rows,setRows]=useState([]),[query,setQuery]=useState(''),[selectedId,setSelectedId]=useState(null),[detail,setDetail]=useState(null),[editMeta,setEditMeta]=useState(null),[addMode,setAddMode]=useState(false),[hotspotDraft,setHotspotDraft]=useState(null),[stepDraft,setStepDraft]=useState(null),[showImport,setShowImport]=useState(false),[importMeta,setImportMeta]=useState({...emptyMeta}),[busy,setBusy]=useState(false),[techMatches,setTechMatches]=useState([]),[vehicleOnly,setVehicleOnly]=useState(Boolean(context)),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(0),[contrast,setContrast]=useState(100),[brightness,setBrightness]=useState(100),[invert,setInvert]=useState(false)
 const filter=()=>({query,...(vehicleOnly&&context?{make:context.make||'',model:context.model||'',engine_code:context.engine_code||''}:{})})
 const load=async()=>{let r=await api.technicalManual.list(filter());if(vehicleOnly&&context&&!r.length&&context.make)r=await api.technicalManual.list({query,make:context.make});setRows(r);if(!selectedId&&r[0])setSelectedId(r[0].id);if(selectedId&&!r.some(x=>x.id===selectedId)&&r[0])setSelectedId(r[0].id)}
 const loadDetail=async id=>{if(!id){setDetail(null);return}setDetail(await api.technicalManual.get(id))}
 const page=detail?.page,hotspots=detail?.hotspots||[],steps=detail?.steps||[]
 useEffect(()=>{load()},[vehicleOnly,context?.make,context?.model,context?.engine_code])
 useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[query])
 useEffect(()=>{loadDetail(selectedId);setZoom(1);setRotation(0);setContrast(100);setBrightness(100);setInvert(false)},[selectedId])
 useEffect(()=>{if(!page){setTechMatches([]);return}const q=[page.make,page.model,page.engine_code,page.section,page.subsection].filter(Boolean).join(' ');if(!q){setTechMatches([]);return}api.technicalData.search(q).then(setTechMatches).catch(()=>setTechMatches([]))},[page?.id])
 const sections=useMemo(()=>Array.from(new Set(rows.map(x=>x.section).filter(Boolean))),[rows])
 const saveMeta=async()=>{await api.technicalManual.update(editMeta.id,editMeta);setEditMeta(null);await load();await loadDetail(selectedId)}
 const importAsset=async(mode)=>{setBusy(true);try{let r;if(mode==='clipboard')r=await api.technicalManual.captureClipboard(importMeta);else r=await api.technicalManual.pickAsset(importMeta);if(r?.id){setShowImport(false);setImportMeta({...emptyMeta});await load();setSelectedId(r.id)}else if(r?.error)alert(r.error)}finally{setBusy(false)}}
 const diagramClick=e=>{if(!addMode||!page)return;const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height;setHotspotDraft({x,y,label:'',kind:'TORQUE',value:'',unit:'Nm',angle:'',note:'',part_hint:'',tool_hint:'',sequence_ref:'',source_type:page.source_type||'WORKSHOP',source_name:page.source_name||'',source_ref:page.source_ref||'',verification_level:page.verification_level||'WORKSHOP'});setAddMode(false)}
 const saveHotspot=async()=>{if(!hotspotDraft?.label?.trim())return;await api.technicalManual.addHotspot(page.id,hotspotDraft);setHotspotDraft(null);loadDetail(page.id)}
 const saveStep=async()=>{if(!stepDraft?.title?.trim())return;await api.technicalManual.addStep(page.id,stepDraft);setStepDraft(null);loadDetail(page.id)}
 const torqueCount=hotspots.filter(x=>x.kind==='TORQUE'||x.kind==='ANGLE').length
 const resetView=()=>{setZoom(1);setRotation(0);setContrast(100);setBrightness(100);setInvert(false)}
 const visualStyle={transform:`scale(${zoom}) rotate(${rotation}deg)`,filter:`contrast(${contrast}%) brightness(${brightness}%) ${invert?'invert(1)':''}`}
 const seededMeta=context?{...emptyMeta,make:context.make||'',model:context.model||'',generation:context.generation||'',engine:context.engine||'',engine_code:context.engine_code||'',title:'',section:'Silnik'}:{...emptyMeta}
 return <section className="manualModule manualModuleV2">
  {context&&<div className="manualContext"><div><small>DOKUMENTACJA OTWARTA Z CENTRUM ZLECENIA</small><b>{context.plate||'bez rej.'} · {context.make} {context.model}</b><span>{context.vin||'VIN brak'} · {context.engine_code||context.engine||'silnik —'}</span></div><div><label><input type="checkbox" checked={vehicleOnly} onChange={e=>setVehicleOnly(e.target.checked)}/> tylko to auto / silnik</label>{onClearContext&&<button onClick={onClearContext}>Odłącz kontekst</button>}</div></div>}
  <div className="manualHero"><div><small>TECHNICAL DOCUMENTATION / VISUAL SERVICE MANUAL 2.0</small><h2>Dokumentacja techniczna Autologiki</h2><p>Drzewo pojazdu → instrukcja → hotspot → moment / część / narzędzie → źródło → procedura.</p></div><div className="manualHeroStats"><div><b>{rows.length}</b><span>stron</span></div><div><b>{sections.length}</b><span>działów</span></div><div><b>{rows.reduce((a,x)=>a+Number(x.hotspot_count||0),0)}</b><span>punktów</span></div></div></div>
  <div className="manualToolbar"><div className="manualSearch"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Szukaj: AVQ, rozrząd, głowica, DSG, hamulce…"/></div><button onClick={()=>{setImportMeta({...seededMeta});setShowImport(true)}}>＋ Import obrazu / PDF</button><button onClick={()=>{setImportMeta({...seededMeta});setShowImport(true)}}>▣ Przechwyć ze schowka</button><button className="primary" onClick={async()=>{const r=await api.technicalManual.create({...seededMeta,title:'Nowy diagram',section:'Własne',page_type:'DIAGRAM'});await load();setSelectedId(r.id)}}>＋ Pusta strona</button></div>
  <div className="manualWorkspace manualWorkspaceV2"><ManualTree rows={rows} selectedId={selectedId} onSelect={setSelectedId}/>
   <main className="manualCanvasArea">{page?<><div className="manualPageHeader"><div><small>{page.section}{page.subsection?` / ${page.subsection}`:''}</small><h3>{page.title}</h3><p>{[page.make,page.model,page.generation,page.engine_code,page.gearbox_code].filter(Boolean).join(' · ')||'Strona ogólna / własna'}</p></div><div className="manualPageActions"><VerificationBadge level={page.verification_level}/><button onClick={()=>setEditMeta({...page})}>Metadane</button>{page.file_path&&<button onClick={()=>api.technicalManual.openAsset(page.id)}>Oryginał</button>}{page.source_ref&&<button onClick={()=>api.technicalManual.openSource(page.id)}>Źródło ↗</button>}<button className={addMode?'primary':''} onClick={()=>setAddMode(x=>!x)}>＋ Punkt</button></div></div>
    <div className="manualViewTools"><button onClick={()=>setZoom(z=>clamp(z-.15,.4,3))}>−</button><b>{Math.round(zoom*100)}%</b><button onClick={()=>setZoom(z=>clamp(z+.15,.4,3))}>＋</button><button onClick={()=>setRotation(r=>(r+90)%360)}>↻ 90°</button><label>Kontrast <input type="range" min="50" max="180" value={contrast} onChange={e=>setContrast(Number(e.target.value))}/></label><label>Jasność <input type="range" min="50" max="180" value={brightness} onChange={e=>setBrightness(Number(e.target.value))}/></label><button className={invert?'active':''} onClick={()=>setInvert(x=>!x)}>Negatyw</button><button onClick={resetView}>Reset</button></div>
    <div className={'manualFigure manualFigureV2 '+(addMode?'placing':'')} onClick={diagramClick}><div className="manualVisualLayer" style={visualStyle}>{detail.assetData?(page.page_type==='PDF'?<iframe title={page.title} src={detail.assetData} className="manualPdfFrame"/>:<img src={detail.assetData}/>):<GenericEngineDiagram/>}</div>{page.page_type!=='PDF'&&hotspots.map((h,i)=><button key={h.id} className={'manualHotspot '+String(h.kind).toLowerCase()} style={{left:`${Number(h.x)*100}%`,top:`${Number(h.y)*100}%`}} onClick={e=>{e.stopPropagation();setHotspotDraft({...h,_edit:true})}}><span>{i+1}</span><div><b>{h.label}</b><strong>{[h.value,h.unit,h.angle&&`+ ${h.angle}`].filter(Boolean).join(' ')||kindText[h.kind]||h.kind}</strong><small>{levelText[h.verification_level]||h.verification_level}</small></div></button>)}</div>
    <div className="manualLowerGrid"><div className="manualDataPanel"><header><div><small>PUNKTY TECHNICZNE</small><h3>{hotspots.length} punktów · {torqueCount} momentów/kątów</h3></div><button onClick={()=>setAddMode(true)}>＋ Dodaj</button></header>{hotspots.length?hotspots.map((h,i)=><article key={h.id} onClick={()=>setHotspotDraft({...h,_edit:true})}><span>{i+1}</span><div><b>{h.label}</b><small>{h.note||kindText[h.kind]||h.kind}{h.part_hint?` · część: ${h.part_hint}`:''}{h.tool_hint?` · narzędzie: ${h.tool_hint}`:''}</small></div><strong>{[h.value,h.unit,h.angle&&`+ ${h.angle}`].filter(Boolean).join(' ')||'—'}</strong><VerificationBadge level={h.verification_level}/></article>):<p className="manualMuted">Dodaj punkt na ilustracji albo utwórz go z Technical Data.</p>}</div>
     <div className="manualSteps"><header><div><small>PROCEDURA</small><h3>Kroki pracy</h3></div><button onClick={()=>setStepDraft({title:'',instruction:'',warning:'',tool:''})}>＋ Krok</button></header>{steps.length?steps.map(s=><article key={s.id}><span>{String(s.step_no).padStart(2,'0')}</span><div><b>{s.title}</b><p>{s.instruction||'—'}</p>{s.tool&&<small>🔧 {s.tool}</small>}{s.warning&&<em>⚠ {s.warning}</em>}</div><button onClick={()=>confirm('Usunąć krok?')&&api.technicalManual.removeStep(s.id).then(()=>loadDetail(page.id))}>×</button></article>):<p className="manualMuted">Dodaj kolejność demontażu, montażu, regulacji i kontroli.</p>}</div></div>
    {techMatches.length>0&&<div className="manualLinkedTech"><header><div><small>POWIĄZANE TECHNICAL DATA</small><h3>Wartości znalezione dla tej strony</h3></div><span>{techMatches.length} rekordów</span></header><div>{techMatches.slice(0,20).map(t=><article key={t.id}><div><b>{t.parameter}</b><small>{[t.make,t.model,t.engine_code,t.category].filter(Boolean).join(' · ')}</small></div><strong>{[t.value,t.unit].filter(Boolean).join(' ')||'—'} {t.notes?.match(/\+\s*\d+°/)?.[0]||''}</strong><VerificationBadge level={t.verification_level||(t.verified?'VERIFIED':'UNVERIFIED')}/><button onClick={()=>setHotspotDraft({x:.5,y:.5,label:t.parameter,kind:t.category==='TORQUE'?'TORQUE':'NOTE',value:t.value||'',unit:t.unit||'',angle:t.notes?.match(/\+\s*\d+°/)?.[0]?.replace('+','').trim()||'',note:t.notes||'',part_hint:'',tool_hint:'',sequence_ref:'',source_type:t.source_type||'WORKSHOP',source_name:t.source_name||'',source_ref:t.source_ref||'',verification_level:t.verification_level||(t.verified?'VERIFIED':'UNVERIFIED'),technical_data_id:t.id})}>＋ hotspot</button></article>)}</div></div>}
    <div className="manualSourceStrip"><div><small>ŹRÓDŁO</small><b>{page.source_name||'Własna dokumentacja warsztatowa'}</b><span>{page.source_ref||page.notes||'Brak dodatkowego odnośnika'}</span></div><VerificationBadge level={page.verification_level}/></div></>:<div className="manualWelcome"><div>◫</div><h2>Wizualny manual warsztatowy</h2><p>Importuj rysunki, PDF-y i przechwycone materiały, a następnie buduj z nich własną, przeszukiwalną dokumentację.</p></div>}</main></div>
  {showImport&&<div className="modalback" onMouseDown={e=>e.target===e.currentTarget&&setShowImport(false)}><div className="modal wide"><div className="modalhead"><h2>Dodaj stronę dokumentacji</h2><button onClick={()=>setShowImport(false)}>×</button></div><div className="formgrid">{[['title','Tytuł'],['section','Dział'],['subsection','Podrozdział'],['make','Marka'],['model','Model'],['generation','Generacja'],['engine','Silnik'],['engine_code','Kod silnika'],['gearbox_code','Kod skrzyni'],['work_tags','Tagi / operacje'],['source_name','Nazwa źródła'],['source_ref','Odnośnik / numer dokumentu']].map(([k,l])=><label key={k}>{l}<input value={importMeta[k]||''} onChange={e=>setImportMeta({...importMeta,[k]:e.target.value})}/></label>)}<label>Poziom weryfikacji<select value={importMeta.verification_level} onChange={e=>setImportMeta({...importMeta,verification_level:e.target.value})}>{LEVELS.map(x=><option key={x} value={x}>{levelText[x]}</option>)}</select></label><label className="wide">Uwagi<textarea value={importMeta.notes||''} onChange={e=>setImportMeta({...importMeta,notes:e.target.value})}/></label></div><div className="manualImportChoice"><button className="primary" disabled={busy} onClick={()=>importAsset('file')}>▣ Wybierz obraz / PDF</button><button disabled={busy} onClick={()=>importAsset('clipboard')}>▤ Pobierz obraz ze schowka</button></div></div></div>}
  {editMeta&&<div className="modalback" onMouseDown={e=>e.target===e.currentTarget&&setEditMeta(null)}><div className="modal wide"><div className="modalhead"><h2>Metadane dokumentacji</h2><button onClick={()=>setEditMeta(null)}>×</button></div><div className="formgrid">{[['title','Tytuł'],['section','Dział'],['subsection','Podrozdział'],['make','Marka'],['model','Model'],['generation','Generacja'],['engine','Silnik'],['engine_code','Kod silnika'],['gearbox_code','Kod skrzyni'],['work_tags','Tagi / operacje'],['source_name','Źródło'],['source_ref','URL / numer dokumentu']].map(([k,l])=><label key={k}>{l}<input value={editMeta[k]||''} onChange={e=>setEditMeta({...editMeta,[k]:e.target.value})}/></label>)}<label>Weryfikacja<select value={editMeta.verification_level||'WORKSHOP'} onChange={e=>setEditMeta({...editMeta,verification_level:e.target.value})}>{LEVELS.map(x=><option key={x} value={x}>{levelText[x]}</option>)}</select></label><label className="wide">Uwagi<textarea value={editMeta.notes||''} onChange={e=>setEditMeta({...editMeta,notes:e.target.value})}/></label></div><div className="actionrow right"><button className="danger" onClick={async()=>{if(confirm('Usunąć stronę dokumentacji?')){await api.technicalManual.remove(editMeta.id);setEditMeta(null);setSelectedId(null);setDetail(null);load()}}}>Usuń stronę</button><button onClick={()=>setEditMeta(null)}>Anuluj</button><button className="primary" onClick={saveMeta}>Zapisz</button></div></div></div>}
  {hotspotDraft&&<div className="modalback" onMouseDown={e=>e.target===e.currentTarget&&setHotspotDraft(null)}><div className="modal"><div className="modalhead"><h2>{hotspotDraft._edit?'Punkt techniczny':'Nowy punkt techniczny'}</h2><button onClick={()=>setHotspotDraft(null)}>×</button></div><div className="formgrid"><label className="wide">Element / opis<input autoFocus value={hotspotDraft.label||''} onChange={e=>setHotspotDraft({...hotspotDraft,label:e.target.value})}/></label><label>Typ<select value={hotspotDraft.kind||'TORQUE'} onChange={e=>setHotspotDraft({...hotspotDraft,kind:e.target.value})}>{Object.keys(kindText).map(x=><option key={x} value={x}>{kindText[x]}</option>)}</select></label><label>Wartość<input value={hotspotDraft.value||''} onChange={e=>setHotspotDraft({...hotspotDraft,value:e.target.value})} placeholder="np. 20"/></label><label>Jednostka<input value={hotspotDraft.unit||''} onChange={e=>setHotspotDraft({...hotspotDraft,unit:e.target.value})} placeholder="Nm / mm / bar"/></label><label>Kąt / kolejny etap<input value={hotspotDraft.angle||''} onChange={e=>setHotspotDraft({...hotspotDraft,angle:e.target.value})} placeholder="np. 90°"/></label><label>Weryfikacja<select value={hotspotDraft.verification_level||'WORKSHOP'} onChange={e=>setHotspotDraft({...hotspotDraft,verification_level:e.target.value})}>{LEVELS.map(x=><option key={x} value={x}>{levelText[x]}</option>)}</select></label><label>Część / numer<input value={hotspotDraft.part_hint||''} onChange={e=>setHotspotDraft({...hotspotDraft,part_hint:e.target.value})} placeholder="np. śruba jednorazowa / OE…"/></label><label>Narzędzie<input value={hotspotDraft.tool_hint||''} onChange={e=>setHotspotDraft({...hotspotDraft,tool_hint:e.target.value})} placeholder="np. blokada wału"/></label><label>Odwołanie do kroku<input value={hotspotDraft.sequence_ref||''} onChange={e=>setHotspotDraft({...hotspotDraft,sequence_ref:e.target.value})} placeholder="np. krok 7"/></label><label className="wide">Uwagi<textarea value={hotspotDraft.note||''} onChange={e=>setHotspotDraft({...hotspotDraft,note:e.target.value})}/></label></div><div className="actionrow right">{hotspotDraft._edit&&<button className="danger" onClick={async()=>{await api.technicalManual.removeHotspot(hotspotDraft.id);setHotspotDraft(null);loadDetail(page.id)}}>Usuń</button>}<button onClick={()=>setHotspotDraft(null)}>Anuluj</button><button className="primary" disabled={!hotspotDraft.label?.trim()} onClick={async()=>{if(hotspotDraft._edit)await api.technicalManual.updateHotspot(hotspotDraft.id,hotspotDraft);else await saveHotspot();setHotspotDraft(null);loadDetail(page.id)}}>Zapisz punkt</button></div></div></div>}
  {stepDraft&&<div className="modalback" onMouseDown={e=>e.target===e.currentTarget&&setStepDraft(null)}><div className="modal"><div className="modalhead"><h2>Dodaj krok procedury</h2><button onClick={()=>setStepDraft(null)}>×</button></div><div className="formgrid"><label className="wide">Tytuł<input autoFocus value={stepDraft.title||''} onChange={e=>setStepDraft({...stepDraft,title:e.target.value})}/></label><label className="wide">Instrukcja<textarea value={stepDraft.instruction||''} onChange={e=>setStepDraft({...stepDraft,instruction:e.target.value})}/></label><label className="wide">Narzędzie / wyposażenie<input value={stepDraft.tool||''} onChange={e=>setStepDraft({...stepDraft,tool:e.target.value})}/></label><label className="wide">Ostrzeżenie<textarea value={stepDraft.warning||''} onChange={e=>setStepDraft({...stepDraft,warning:e.target.value})}/></label></div><div className="actionrow right"><button onClick={()=>setStepDraft(null)}>Anuluj</button><button className="primary" disabled={!stepDraft.title?.trim()} onClick={saveStep}>Dodaj krok</button></div></div></div>}
 </section>
}

