-- Remote Approval 2.0: podpis, dowód, prywatny PDF i atomowa decyzja.
create extension if not exists pgcrypto;

alter table public.customer_approval_links add column if not exists token_hash text;
alter table public.customer_approval_links add column if not exists approval_cloud_id uuid;
alter table public.customer_approval_links add column if not exists order_cloud_id uuid;
alter table public.customer_approval_links add column if not exists snapshot_hash text;
alter table public.customer_approval_links add column if not exists hash_algorithm text not null default 'SHA-256';
alter table public.customer_approval_links add column if not exists terms_version text;
alter table public.customer_approval_links add column if not exists terms_text text;
alter table public.customer_approval_links add column if not exists document_no text;
alter table public.customer_approval_links add column if not exists approval_sequence integer not null default 1;
alter table public.customer_approval_links add column if not exists previously_approved_total numeric(14,2) not null default 0;
alter table public.customer_approval_links add column if not exists signature_storage_path text;
alter table public.customer_approval_links add column if not exists signature_hash text;
alter table public.customer_approval_links add column if not exists signature_point_count integer;
alter table public.customer_approval_links add column if not exists pdf_storage_path text;
alter table public.customer_approval_links add column if not exists pdf_hash text;
alter table public.customer_approval_links add column if not exists client_user_agent text;
alter table public.customer_approval_links add column if not exists opened_at timestamptz;
alter table public.customer_approval_links add column if not exists security_event text;

update public.customer_approval_links set token_hash=encode(digest(token,'sha256'),'hex') where token_hash is null;
update public.customer_approval_links set snapshot_hash=encode(digest(convert_to(snapshot::text,'UTF8'),'sha256'),'hex') where snapshot_hash is null;
alter table public.customer_approval_links alter column token_hash set not null;
alter table public.customer_approval_links alter column snapshot_hash set not null;
create unique index if not exists customer_approval_links_token_hash_idx on public.customer_approval_links(token_hash);

alter table public.customer_approval_links drop constraint if exists customer_approval_links_status_check;
alter table public.customer_approval_links add constraint customer_approval_links_status_check check (status in ('PENDING','APPROVED','DECLINED','EXPIRED','SUPERSEDED'));

create table if not exists public.customer_approval_events (
  id bigint generated by default as identity primary key,
  workshop_id uuid not null,
  approval_id uuid not null references public.customer_approval_links(id) on delete cascade,
  event_type text not null check (event_type in ('APPROVAL_CREATED','APPROVAL_OPENED','APPROVAL_APPROVED','APPROVAL_DECLINED','APPROVAL_EXPIRED','APPROVAL_PDF_CREATED','APPROVAL_SYNCED','APPROVAL_SECURITY_REJECTED')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists customer_approval_events_owner_idx on public.customer_approval_events(workshop_id,approval_id,created_at desc);
alter table public.customer_approval_events enable row level security;
drop policy if exists "approval_events_owner_select" on public.customer_approval_events;
drop policy if exists "approval_events_owner_sync_insert" on public.customer_approval_events;
create policy "approval_events_owner_select" on public.customer_approval_events for select to authenticated using (workshop_id=auth.uid());
create policy "approval_events_owner_sync_insert" on public.customer_approval_events for insert to authenticated with check (workshop_id=auth.uid() and event_type='APPROVAL_SYNCED');

drop policy if exists "approval_links_owner_all" on public.customer_approval_links;
drop policy if exists "approval_links_owner_select" on public.customer_approval_links;
drop policy if exists "approval_links_owner_insert" on public.customer_approval_links;
create policy "approval_links_owner_select" on public.customer_approval_links for select to authenticated using (workshop_id=auth.uid());
create policy "approval_links_owner_insert" on public.customer_approval_links for insert to authenticated with check (workshop_id=auth.uid());

create or replace function public.supersede_previous_approval_links() returns trigger language plpgsql security definer set search_path=public as $$
begin
  update public.customer_approval_links set status='SUPERSEDED',decided_at=now()
    where workshop_id=new.workshop_id and approval_local_id=new.approval_local_id and status='PENDING';
  return new;
end $$;
drop trigger if exists supersede_previous_approval_links_trigger on public.customer_approval_links;
create trigger supersede_previous_approval_links_trigger before insert on public.customer_approval_links for each row execute function public.supersede_previous_approval_links();

create or replace function public.approval_created_event() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.customer_approval_events(workshop_id,approval_id,event_type,details) values(new.workshop_id,new.id,'APPROVAL_CREATED',jsonb_build_object('snapshot_hash',new.snapshot_hash));
  return new;
end $$;
drop trigger if exists customer_approval_created_event on public.customer_approval_links;
create trigger customer_approval_created_event after insert on public.customer_approval_links for each row execute function public.approval_created_event();

create or replace function public.protect_finished_approval() returns trigger language plpgsql as $$
begin
  if old.status in ('APPROVED','DECLINED','EXPIRED','SUPERSEDED') and new is distinct from old then
    raise exception 'Finished approval evidence is immutable';
  end if;
  return new;
end $$;
drop trigger if exists protect_finished_approval_trigger on public.customer_approval_links;
create trigger protect_finished_approval_trigger before update on public.customer_approval_links for each row execute function public.protect_finished_approval();

create or replace function public.decide_customer_approval(
  p_token_hash text,p_decision text,p_note text,p_snapshot_hash text,p_signature_path text default null,p_signature_hash text default null,
  p_signature_points integer default null,p_pdf_path text default null,p_pdf_hash text default null,p_user_agent text default null
) returns public.customer_approval_links
language plpgsql security definer set search_path=public as $$
declare target public.customer_approval_links;
begin
  if p_decision not in ('APPROVED','DECLINED') then raise exception 'Invalid decision'; end if;
  select * into target from public.customer_approval_links where token_hash=p_token_hash for update;
  if target.id is null then raise exception 'Invalid token'; end if;
  if target.status<>'PENDING' then return target; end if;
  if target.expires_at<=now() then
    update public.customer_approval_links set status='EXPIRED',decided_at=now() where id=target.id returning * into target;
    insert into public.customer_approval_events(workshop_id,approval_id,event_type) values(target.workshop_id,target.id,'APPROVAL_EXPIRED');
    return target;
  end if;
  if target.snapshot_hash<>p_snapshot_hash then
    update public.customer_approval_links set status='SUPERSEDED',decided_at=now(),security_event='SNAPSHOT_HASH_MISMATCH' where id=target.id returning * into target;
    insert into public.customer_approval_events(workshop_id,approval_id,event_type,details) values(target.workshop_id,target.id,'APPROVAL_SECURITY_REJECTED',jsonb_build_object('reason','SNAPSHOT_HASH_MISMATCH'));
    return target;
  end if;
  if p_decision='APPROVED' and (coalesce(p_signature_path,'')='' or coalesce(p_signature_hash,'')='' or coalesce(p_signature_points,0)<3 or coalesce(p_pdf_path,'')='' or coalesce(p_pdf_hash,'')='') then
    raise exception 'Signature and PDF evidence are required';
  end if;
  update public.customer_approval_links set status=p_decision,customer_note=left(coalesce(p_note,''),1000),decided_at=now(),
    signature_storage_path=case when p_decision='APPROVED' then p_signature_path else null end,
    signature_hash=case when p_decision='APPROVED' then p_signature_hash else null end,
    signature_point_count=case when p_decision='APPROVED' then p_signature_points else null end,
    pdf_storage_path=case when p_decision='APPROVED' then p_pdf_path else null end,
    pdf_hash=case when p_decision='APPROVED' then p_pdf_hash else null end,
    client_user_agent=left(coalesce(p_user_agent,''),500)
    where id=target.id and status='PENDING' returning * into target;
  update public.customer_approval_links set status='SUPERSEDED',decided_at=now()
    where workshop_id=target.workshop_id and approval_local_id=target.approval_local_id and id<>target.id and status='PENDING';
  insert into public.customer_approval_events(workshop_id,approval_id,event_type,details) values(target.workshop_id,target.id,case when p_decision='APPROVED' then 'APPROVAL_APPROVED' else 'APPROVAL_DECLINED' end,jsonb_build_object('snapshot_hash',target.snapshot_hash));
  if p_decision='APPROVED' then insert into public.customer_approval_events(workshop_id,approval_id,event_type,details) values(target.workshop_id,target.id,'APPROVAL_PDF_CREATED',jsonb_build_object('pdf_hash',p_pdf_hash)); end if;
  return target;
end $$;
revoke all on function public.decide_customer_approval(text,text,text,text,text,text,integer,text,text,text) from public,anon,authenticated;
grant execute on function public.decide_customer_approval(text,text,text,text,text,text,integer,text,text,text) to service_role;

insert into storage.buckets(id,name,public) values('approval-evidence','approval-evidence',false) on conflict(id) do update set public=false;
drop policy if exists "approval_evidence_owner_select" on storage.objects;
create policy "approval_evidence_owner_select" on storage.objects for select to authenticated using (bucket_id='approval-evidence' and (storage.foldername(name))[1]=auth.uid()::text);
